### ISSUE TITLE
Add `source_path` (`path`) property to `ContractContainer`

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#1005]
### Overview

The path of a contract container (e.g. `MyContract`) in a project can be described like:

```python
project.contracts_folder / project.MyContract.contract_type.source_id
```

It would be convenient to be able to have access to the source path earlier on:

```python
source_path = project.MyContract.source_path
```

### Specification

```python
@cached_property
def source_path(self) -> Optional[Path]:
    """
    Returns the path to the local contract if determined that this container
    belongs to the active project.
    """
    contract_name = self.contract_type.name
    contract_type = self.project_manager._get_contract(contract_name)
    if contract_type and self.contract_type == contract_type:
        return self.project_manager.contracts_folder / contract_type.source_id
```

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by unparalleled-js** [comment]
@fubuloubu Would something like this ease the usage of ape with Titanboa?

**Comment by fubuloubu** [comment]
> @fubuloubu Would something like this ease the usage of ape with Titanboa?

Couldn't hurt, since it's needs to be able to read the file for interpreting

**Comment by sabotagebeats** [comment]
```
In [1]: project.Token.source_path
WARNING: Unable to find dependency 'solidity-bytes-utils/v0.8.0'.
Out[1]: PosixPath('/home/doge/ape/dummyproject/contracts/Token.sol')
```
looking good. will submit PR shortly.
