### ISSUE TITLE
Add support for EIP-1559

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#104]
depends: #192

### What went wrong?
The London hardfork will change the format for gas costs via [EIP-1559](https://eips.ethereum.org/EIPS/eip-1559). `eth-account` version 0.5.5 [added support](https://eth-account.readthedocs.io/en/latest/release_notes.html#eth-account-v0-5-5-2021-07-21) for these upgrades.

### How can it be fixed?
Add support to Transaction type for eip-1559 style gas abstractions. It might take some better abstractions to get it right.

**Comment by fubuloubu** [comment]
Idea: abstract the `gas_price` kwarg into a `GasStrategyAPI` plugin system, allowing users to select a gas strategy via kwarg e.g. `contract.my_transaction(..., gas_strategy=GasStrategyPlugin(), ...)` (with some handling for EIP1559 behaviors):

```python
contract.my_transaction(..., max_fee="10 gwei", ...)  # Use post-EIP1559 behavior (built-in Constant Conversion to `gas_strategy`)

contract.my_transaction(..., gas_strategy=GasNow("fast"), ...)  # Use gasnow API "fast" gas (no resends)

contract.my_transaction(..., gas_strategy=LinearGasStrategy(start_gas="10 gwei", end_gas="50 gwei"), ...)
```

**Comment by unparalleled-js** [comment]
This should probably be two separate issues, one for EIP-1559 alone and one for typed transactions.
