### ISSUE TITLE
Ape core reinstalls itself when there's a plugin installed that requires older versions of core

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1046]
### What went wrong?

When you install a plugin that is pinned to an older version of ape via `ape plugins install ...`, the installation will silent install the older version of ape specified in the pin

### How can it be fixed?

1. When installing a plugin without specifying a version, a minimum pin should be specified using ape core's version e.g. `f"ape-plugin>={ape.version}"`
2. When installing a plugin and specifying a version, that version should be >= the current version of ape, and tell the user to downgrade ape core if it isn't
3. We should probably have better methods to upgrade/downgrade all of ape core and plugins at once

**Comment by sabotagebeats** [comment]
Is this seeming to be the same issue? 

```
$ ape plugins install solidity vyper infura alchemy ens 
INFO: Installing solidity...
SUCCESS: Plugin 'solidity==0.5.0' has been installed.
INFO: Installing vyper...
SUCCESS: Plugin 'vyper==0.5.0' has been installed.
INFO: Installing infura...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ape-vyper 0.5.0 requires eth-ape<0.6.0,>=0.5.0, but you have eth-ape 0.4.5 which is incompatible.
ape-solidity 0.5.0 requires eth-ape<0.6,>=0.5.0, but you have eth-ape 0.4.5 which is incompatible.
SUCCESS: Plugin 'infura==0.4.0' has been installed.
INFO: Installing alchemy...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ape-infura 0.4.0 requires eth-ape<0.5.0,>=0.4.0, but you have eth-ape 0.5.1 which is incompatible.
SUCCESS: Plugin 'alchemy==0.5.0' has been installed.
INFO: Installing ens...
SUCCESS: Plugin 'ens==0.5.0' has been installed.
$ ape --version
0.5.1
```

**Comment by fubuloubu** [comment]
Yes, that's exactly the issue. It actually is downgrading eth-ape to 0.4.6 and then upgrading again to 0.5.1,depending on the order of the plugins. Trying installing infura last

**Comment by ef3n9r98** [comment]
Hi @fubuloubu, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!

**Comment by fubuloubu** [comment]
> Hi @fubuloubu, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much?
> 
> I'd put this issue up on [OpenQ](http://www.openq.dev/).
> 
> Thanks!

Not interested in OpenQ, thank you @ef3n9r98
