### ISSUE TITLE
Address return types are type `str` and not `AddressType`

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#1089]
### Environment information

Latest and greatest, Python 3.9 something, macOS

### What went wrong?

When a view method or something returns an `address` type in a contract, the result from Ape is a `str`.
I would expect it to be either an `AddressAPI` or an `AddressType`.

```python
In [6]: contract.theAddress()
Out[6]: '0x0000000000000000000000000000000000000000'

In [7]: addr = contract.theAddress()

In [8]: type(addr)
Out[8]: str
```

### How can it be fixed?

Use ABI to decode address values as higher level types so we can make nice assertions

**Comment by sabotagebeats** [comment]
I was able to replicate this problem.

**Comment by fubuloubu** [comment]
`AddressType` is a type constraint around `str` actually, so this is consistent behavior
