### ISSUE TITLE
Collect gas reporting information for view method calls

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1091]
### Overview

Currently, Ape's gas report feature is collecting gas information only for mutable transactions that are executing (due to how tracing works). However, it would be really useful to also profile read-only functions, which will not be executing this way (but will be called)

NOTE: This will also be helpful for test coverage

https://linear.app/apeworx/issue/APE-287/collect-gas-reporting-information-for-view-method-calls

### Specification

Intercept any read-only method calls and send them as a transaction (reverting back scope after the call)

### Dependencies
No dependencies

**Comment by unparalleled-js** [comment]
Question, what do we use as the sender? I guess it does not really matter since it gets reverted, but I am curious.

I wish there was a better way to do this. It feels hacky to use the EVM this way.

**Comment by fubuloubu** [comment]
> Question, what do we use as the sender? I guess it does not really matter since it gets reverted, but I am curious.

Many view methods it doesn't really matter. Could have it default to whatever the first account is if not specified. View methods can be contextual in this way, so it's probably best to have some sort of sender account baked in, even if it doesn't sign.

> I wish there was a better way to do this. It feels hacky to use the EVM this way.

Agreed. Titanoboa will let you perform aribtrary tracing using py-evm opcode extensions
