### ISSUE TITLE
Skip reporting gas for specific methods/contracts using a regex

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1092]
### Overview

Sometimes I might have additional test-only contracts or methods where I don't necessarily want them to be reported with the reporting feature. As an example, here's a capture I made with a project I am working on:

```sh
                       test/Token.vy Gas                        
                                                                
  Method         Times called    Min.    Max.    Mean   Median  
 ────────────────────────────────────────────────────────────── 
  DEBUG_mint                4   10473   44673   27573    27573  
  approve                   2   24273   24273   24273    24273  
  balanceOf                 2    2509    2509    2509     2509  
  transferFrom              2   26112   26112   26112    26112  
  transfer                  4   12263   29363   20813    20813  
                                                                
                          VyperVault.vy Gas                           
                                                                      
  Method               Times called    Min.    Max.    Mean   Median  
 ──────────────────────────────────────────────────────────────────── 
  deposit                         1   77727   77727   77727    77727  
  DEBUG_steal_tokens              2   17799   34899   26349    26349  
                                                                      
                        SolidityVault.sol Gas                         
                                                                      
  Method               Times called    Min.    Max.    Mean   Median  
 ──────────────────────────────────────────────────────────────────── 
  deposit                         1   80248   80248   80248    80248  
  DEBUG_steal_tokens              2   17651   34751   26201    26201  
```

### Specification

I'd like to be able to specify via config option and/or command-line flag when running `ape test` a specific set of contracts and/or contract methods to skip when executing the gas report feature

Using the above example, I would want to skip contracts under `test/*` and methods that start with `DEBUG_*`:

```yaml
test:
  skip_contract_types:
  - Token
  skip_method_names:
  - DEBUG_[a-z_]*
```

which would make the report look like:

```sh
                          VyperVault.vy Gas                           
                                                                      
  Method               Times called    Min.    Max.    Mean   Median  
 ──────────────────────────────────────────────────────────────────── 
  deposit                         1   77727   77727   77727    77727  
                                                                      
                        SolidityVault.sol Gas                         
                                                                      
  Method               Times called    Min.    Max.    Mean   Median  
 ──────────────────────────────────────────────────────────────────── 
  deposit                         1   80248   80248   80248    80248  
```

NOTE: Example not final

https://linear.app/apeworx/issue/APE-286/skip-reporting-gas-for-specific-methodscontracts-using-a-regex

### Dependencies

no dependencies

**Comment by unparalleled-js** [comment]
Additionally, it would be useful to have CLI options `--gas-exclude-contract "Token,OtherContract" --gas-exclude-method "DEBUG_[a-z_]*"` so that adhoc can skip things without having to edit the `ape-config.yaml` file.

Also, I am thinking the config should be something like:

```yaml
test:
  reports:
    gas:
        skip_contract_types:
        - Token
        skip_method_names:
        - DEBUG_[a-z_]*
```

**Comment by unparalleled-js** [comment]
hmm, one issue with this config design: If you wanted to skip a method with a certain pattern in 1 contract but not the other.... Rethinking the design...

**Comment by fubuloubu** [comment]
> hmm, one issue with this config design: If you wanted to skip a method with a certain pattern in 1 contract but not the other.... Rethinking the design...

Perhaps could be like `ContractTypeName:methodName` or something, split out the `:` chars

**Comment by unparalleled-js** [comment]
So like:

```yaml
test:
  skip_contracts:
    - ContractTypeA                   # Skip all methods in `ContractTypeA`
    - ContractTypeB:DEBUG_*  # Skip all methods starting with `DEBUG_` in `ContractTypeB`
```

**Comment by fubuloubu** [comment]
> So like:
> 
> ```yaml
> test:
>   gas:
>     skip_contracts:
>       - ContractTypeA                   # Skip all methods in `ContractTypeA`
>       - ContractTypeB:DEBUG_*  # Skip all methods starting with `DEBUG_` in `ContractTypeB`
> ```

Yes!
