### ISSUE TITLE
The `ape` shell command should go to console

### ISSUE THREAD

**Issue by delaaxe** [ApeWorX/ape#1095]
### Overview

When I feel like aping, I want to just type `ape` in my bash shell, not `ape console`.

### Specification

Running the `ape` command by itself goes to console, optionally printing a notice beforehand saying "Run `ape -h` to see the list of available commands".

The `ape console` command can still stay for consistency and backwards compatibility.

**Comment by gosuto-inzasheru** [comment]
you could just create an alias yourself, no?

**Comment by delaaxe** [comment]
> you could just create an alias yourself, no?

what would be the alias though? doing so break the rest of the commands:

```bash
alias ape="ape console"
```

@unparalleled-js also consider that running `python` and `ipython` commands by themselves also drop you into a shell, so it's natural for `ape` to do the same

**Comment by gosuto-inzasheru** [comment]
ah you are right, would need to be something different from `ape`.

i agree with your take on the bare `python` command also opening a console.

**Comment by unparalleled-js** [comment]
Let me bring this to request to the Council of Apes.

**Comment by delaaxe** [comment]
![image](https://user-images.githubusercontent.com/1091900/203142250-f97a3721-054a-4916-80d5-ad6e4531f902.gif)

**Comment by unparalleled-js** [comment]
I think others may add their thoughts, but we are leaning on `no`. My reason: why not have `ape test` be the default command? It makes sense too. The Ape framework is many things, the console is only one of them. Using a custom alias (perhaps `cape` ?) is your best bet.

**Comment by helloibis** [comment]
> what would the alias be though?

You can't use a straight alias and have it still accept non-`console` subcommands, but there is the possibility of redefining `ape` as a custom function:

```bash
ape() {
    if [ $# -eq 0 ]; then
        ape console
    else
        ape "$@"
    fi
}
```

Of course this is just to facilitate running `ape console` by default, if you need `ape --someflag` to still run `console` then the setup gets a bit more complicated unless you made an `alias cape="ape console"` as mentioned earlier

Basically like @unparalleled-js said, `ape` itself is more of a process that launches specific sub-tools than a tool itself

For this reason we have it set so running just `ape` defaults to printing out configuration and command documentation

**Comment by delaaxe** [comment]
Makes sense, I may just call my alias `iape` then. Feel free to close the issue if you think it's resolved
