### ISSUE TITLE
`parse_type` is buggy

### ISSUE THREAD

**Issue by nazariyv** [ApeWorX/ape#1122]
### Environment information

* OS: linux
* Python Version: 3.10.6
* `ape` and plugin versions:
`ape`: 0.5.3. But I could reproduce the same issue in 0.5.4

```
Installed Plugins:
  etherscan      0.5.2
  ens            0.5.1
  addressbook    0.5.0a1
```
But this bug has nothing to do with plugins

* Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

This also doesn't matter.

### What went wrong?

<img width="1073" alt="ape-bug" src="https://user-images.githubusercontent.com/13678461/200179295-8b9acb9c-4409-41c1-b91f-d900d72739c0.png">

And discord [link](https://discord.com/channels/922917176040640612/922928308109344778/1036431871665524817) to the above.

Essentially, this problem boils down to the fact that `parse_type` has a bug. I debugged it for a little while, but then realised that there is an easier way to solve the problem. There is no need to go from `canonical` type string back to Python representation. There is an `ABIType` that can be easily utilised to produce what `parse_type` was producing, but bug free.

### How can it be fixed?

Going to link the fix here shortly.

**Comment by unparalleled-js** [comment]
Transaction hash that fails: 0x998f1810cc06f7c0aa3a6094082278e882a53a35a57a4f1094213ec78ca45931
