### ISSUE TITLE
gas_limit param causes error in 0.5.7

### ISSUE THREAD

**Issue by r4VP4** [ApeWorX/ape#1176]
### Environment information

* OS: ubuntu 22.04
* Python Version: 3.9.15

```sh
$ ape --version
# 0.5.7

$ ape plugins list
#Installed Plugins:
  polygon      0.5.1a1
  hardhat      0.5.3
  foundry      0.5.2
  vyper        0.5.2
  alchemy      0.5.3
  solidity     0.5.2
  etherscan    0.5.4
```

* Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy  

foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy       
        
ethereum:
  mainnet:
    gas_limit: "max"
```

### What went wrong?

calling a contract in a script with gas_limit parameter 
```
mycontract.mymethod(
   myparam,
   sender=myaccount,
   gas_limit='auto' # or gas_limit=750000 makes no difference
)
```
```
ape run my_script --network ethereum:mainnet-fork:foundry
# or
ape run my_script --network ethereum:mainnet-fork:hardhat
```

leads to the following error

```
ERROR: (ConversionError) Type 'typing.Union[typing.Literal['auto', 'max'], int, str, NoneType]' must be one of [ChecksumAddress, bytes, int, Decimal, list, tuple].
```

**Comment by fubuloubu** [comment]
Taking a stab at this, but think it's originating from here: https://github.com/ApeWorX/ape/blob/main/src/ape/contracts/base.py#L25

**Comment by r4VP4** [comment]
i've seen your commits in #1180 but i'm not sure if this is the solution, because i have the problem always if i use the gas_limit parameter. it is not just for 'auto'. sorry for the misleading example.

**Comment by fubuloubu** [comment]
related: #1220
