### ISSUE TITLE
Show error when failing in interactive mode

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1182]
## What went wrong?

It would be extremely helpful to know which transaction has failed and why when entering interactive mode:

![IMG_20221209_065717_659.jpg](https://user-images.githubusercontent.com/3859395/206697607-1bd5ba6d-8add-4a9c-9dc3-b59dec32bd1f.jpg)

## How can it be fixed?

The display should be similar to when I a failure occurs in non-interactive mode:

![IMG_20221209_065722_067.jpg](https://user-images.githubusercontent.com/3859395/206697626-84d130ed-6904-410d-ba85-4c4b163364f9.jpg)

**Comment by antazoey** [comment]
I just double checked with all the providers and using both `-I` in scripts and tests and this is no longer a problem.
We fixed that way back when we added the source traceback adjustments.
But even when there is no source traceback (provider without tracing or whathaveyou), you still see the exception.

In your example, you are using Hardhat, which will even show you Vyper line numbers if you are using ape-vyper as well!
