### ISSUE TITLE
Add error type support to `ape.reverts`

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1223]
### Overview

Solidity v0.8.x series added a new type of item to the abi called custom errors: https://docs.soliditylang.org/en/v0.8.17/structure-of-a-contract.html#errors

We have support for parsing these errors from the ABI as of [ethpm-types v0.2.1](https://github.com/ApeWorX/ethpm-types/issues/22) 

The basic gist is that when a revert happens, Solidity will return abi-encoded dated corresponding to the error type with additional information about the error. Some of the built-in Solidity errors are as follows (it might be good to add an enum with these to `ape-ethereum` or `ape-solidity`):

<img width="552" alt="image" src="https://user-images.githubusercontent.com/3859395/212744399-381987c3-1ff7-4f19-b7dc-7abbc852dcfc.png">

### Specification

It would be nice to use these error types in tests w/ `ape.reverts`. Some examples might include:

```py
# succeds if `CustomError` is raised with any args
with ape.reverts(my_contract.CustomError):
    my_contract.call_that_raises_CustomError(...)

# succeds if `CustomError` is raised with `arg1 = some_value`, fails otherwise
with ape.reverts(my_contract.CustomError, arg1=some_value):
    my_contract.call_that_raises_CustomErrorWithArgs(...)
```

### Dependencies

n/a

**Comment by pcaversaccio** [comment]
To be specific, Solidity [`0.8.4`](https://github.com/ethereum/solidity/releases/tag/v0.8.4) introduced _Custom Errors_.

**Comment by fubuloubu** [comment]
Alternative syntax:

```py
with my_contract.CustomError(_, _, ..., _):
    my_contract.call_that_raises_CustomError(...)

with my_contract.CustomError(some_value, _, ..., _):
    my_contract.call_that_raises_CustomErrorWithArgs(...)
```

But the use of the wildcard `_` might be complex

**Comment by pcaversaccio** [comment]
KISS - I would definitely go with version 1.

**Comment by fubuloubu** [comment]
> KISS - I would definitely go with version 1.

Yeah I agree, but I did like the ability to do `with CustomErrorType: ...` which I think it's a bit nicer looking syntax

**Comment by pcaversaccio** [comment]
I see - maybe worth introducing an alias later?

**Comment by unparalleled-js** [comment]
> @fubuloubu any progress/news on this?

PR open
