### ISSUE TITLE
Allow using bytecode from JSON artifacts.

### ISSUE THREAD

**Issue by sajal** [ApeWorX/ape#1227]
### Overview

I am trying to use a JSON artifact created using hardhat(from a much larger project), as my test dependency.

The current JSON compiler only allows using JSON artifacts as interfaces, and ignores the bytecode.

Here is an example JSON artifact : https://gist.github.com/sajal/8c793c5066c3684a6178906aa248f347

When deploying using `deployer.deploy(project.MockLinearPool, ..... args ...)` the following warning is emitted `WARNING  ape:base.py:45 Deploying an empty contract (no bytecode)` and when trying to call the contract the following error happens

`ape.exceptions.ContractError: Unable to make contract call. '0x6Af9BB9Cf7307AC439cc7E37859bdD844874ebc1' is not a contract on network 'local'.`

### Specification

I propose adapting the [InterfaceCompiler](https://github.com/ApeWorX/ape/blob/0e31f26578aa41d9015489de5ff1dd6f9ee725da/src/ape_pm/compiler.py#L12-L50) so that `bytecode` and `deployedBytecode` fields (if present in JSON) are included in the final compiled output.

I do not think this change breaks anything.

### Dependencies

I do not think there are any dependencies for this.

**Comment by unparalleled-js** [comment]
Fixed in https://github.com/ApeWorX/ape/pull/1261
Please let us know if you have any more issues! Thank you for reporting and contributing to the fix.
