### ISSUE TITLE
Make `Contract` a fixture

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1241]
### Overview

For fork mode testing it's often handy to load on-chain contracts with the chain you are working with, which requires using `ape.Contract`. However, it's not currently a fixture.

### Specification

Add this method to the set of pytest-registered fixtures, so that people can use it like this:

```py
@pytest.fixture(scope="session")
def on_chain_contract(Contract):
    return Contract("<some address>")
```

### Dependencies
n/a

**Comment by SaturnCassini** [comment]
probably this is the place where to add such fixture 
https://github.com/ApeWorX/ape/blob/f2c586d14a0fe1348c4c1f2fce07438a017f3fb8/src/ape/pytest/fixtures.py

**Comment by unparalleled-js** [comment]
can do `chain.contracts.instance_at` in the short term.
`chain` is a fixture
