### ISSUE TITLE
Fix docs that link to 2nd and 3rd party packages

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1263]
Someone mentioned to me that on occasion in our docs or docstrings, we link to types imported from other packages, such as EF-managed dependencies, which causes a 404 when you try to click on the hyperlink. Track down and instances of this and link over to the correct package

**Comment by antazoey** [comment]
the majority of this work was completed here:

fixed by https://github.com/ApeWorX/ape/pull/1456
and https://github.com/ApeWorX/ape/pull/1321

but I am going through and seeing if any remain

**Comment by antazoey** [comment]
> Wonder if there can be a test to trace through all the links for 404

There are, but it would a task to set this up. I am not sure we are ready for adding a whole tool just for this.
