### ISSUE TITLE
Add `NetworkManager.use_fork_provider(str | None)` context manager

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1269]
### Overview

It's pretty useful to be able to active a forked network on-command, but a little awkward right now, so create a shortcut `networks.fork_network`

### Specification

```py
class NetworkManager(...):

    def fork_network(self, provider_name: Optional[str] = None) -> ProviderContextManager:
        forked_network = getattr(self.provider.network.ecosystem, f"{self.provider.network.name}-fork")

        if provider_name:
            return forked_network.use_provider(provider_name)

        return forked_network.use_default_provider()
```

### Dependencies

n/a

**Comment by unparalleled-js** [comment]
The spec will have issue on this line:

```python
forked_network = getattr(self.provider.network.ecosystem, f"{self.provider.network.name}-fork"
```

as it is references `self.provider` before potentially being connected.

We may have to include the `ecosystem` as a param or make this method part of `EcosystemAPI` instead.

**Comment by fubuloubu** [comment]
Hmm, maybe on `NetworkAPI` instead?

```py
forked_network = getattr(self.ecosystem, f"{self.name}-fork")
```

**Comment by unparalleled-js** [comment]
> Hmm, maybe on `NetworkAPI` instead?

Yes, this seems neat!

> forked_network = getattr(self.ecosystem, f"{self.name}-fork")

However, you don't need to use `getattr` here, you can do `self.ecosystem.get_network(f"{self.name}-fork")`

Full example now:

```python
class NetworkAPI:

    def fork(self, provider_name: Optional[str] = None):
        forked_network = self.ecosystem.get_network(f"{self.name}-fork")
        if provider_name:
            return forked_network.use_provider(provider_name)

        return forked_network.use_default_provider()
```

And then usage:

```
with networks.mainnet.fork():
    ...
```

This seems not too bad?

**Comment by fubuloubu** [comment]
> > Hmm, maybe on `NetworkAPI` instead?
> 
> Yes, this seems neat!
> 
> > forked_network = getattr(self.ecosystem, f"{self.name}-fork")
> 
> However, you don't need to use `getattr` here, you can do `self.ecosystem.get_network(f"{self.name}-fork")`
> 
> Full example now:
> 
> ```python
> class NetworkAPI:
> 
>     def fork(self, provider_name: Optional[str] = None):
>         forked_network = self.ecosystem.get_network(f"{self.name}-fork")
>         if provider_name:
>             return forked_network.use_provider(provider_name)
> 
>         return forked_network.use_default_provider()
> ```
> 
> And then usage:
> 
> ```
> with networks.mainnet.fork():
>     ...
> ```
> 
> This seems not too bad?

Yes, I think this is a good API
