### ISSUE TITLE
Ape gas estimation doesn't work well in times of instability

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1272]
### Environment information

- OS: linux
- Python Version: 3.8.16

```sh
$ ape --version
0.6.0
```

### What went wrong?

Goerli has been having some weird activity today where the gas price has been fluctuating pretty wildly. Ape tends to fail under these circumstances, in ways that look like a dropped transaction (but it's really not):
```
ERROR: (TransactionNotFoundError) Transaction '0x1762....151f' not found.
```

Also, when you try to pick up a session where this issue is encountered, it doesn't see to detect that there is a previous transaction in the mempool, or give good indication on how to solve that scenario (increasing gas usage past the previous txn) in order to get unblocked and move past the issue.

### How can it be fixed?

Can do a bit of caching for transactions "in motion" i.e. we have broadcasted them out there, but they took longer than expected to confirm, so we'll make a notice like "This is taking longer to confirm than usual, press Ctrl+C to exit"

Additionally, use that transaction from a previous session to alert the user that another transaction may be in the mempool at the same nonce, and to replace it the gas price needs to out-price that transaction so it will be dropped.

Very difficult thing to solve completely, but we can give some better tools to alert users to what is happening, and help them work around these types of issues through additional configurations. For scripting use cases, these APIs need to be much more robust (including txn re-pricing if possible)

**Comment by fubuloubu** [comment]
Following up on this, it seems like somehow I "lost" a transaction, and that's what got me stuck. Both Ape and my non-Ape wallet saw we were on nonce 92 when etherscan could only show nonce 90. So I used ape to send a transaction with nonce 91 and was able to get myself unstuck.

Not that ape should be able to detect these types of situations easily, but it should be possible to find the last "confirmed" nonce that one of my accounts made, so I can compare it to the current nonce

**Comment by unparalleled-js** [comment]
i have to retry my txns on goerli many times over. Is this just a goeli thing?
Should we be doing 1.1x the result from estimation?

Better receipt retry mechanism would also help

**Comment by fubuloubu** [comment]
Think this may be resolved by https://github.com/ApeWorX/ape/pull/1430

**Comment by antazoey** [comment]
> Also, when you try to pick up a session where this issue is encountered, it doesn't see to detect that there is a previous transaction in the mempool, or give good indication on how to solve that scenario (increasing gas usage past the previous txn) in order to get unblocked and move past the issue.

I believe this part is already tracker here: https://github.com/ApeWorX/ape/issues/352

Re the error: `ERROR: (TransactionNotFoundError) Transaction '0x1762....151f' not found.`, did https://github.com/ApeWorX/ape/pull/1458 help or resolve this?

Re gas and instability, I am wondering if this PR will help: https://github.com/ApeWorX/ape/pull/1520

Through the combination of the existing issue and the 2 other PRs, I am wondering if we can close this issue.

**Comment by antazoey** [comment]
Closing as no one responded to me, reopen if you feel differently.
