### ISSUE TITLE
with ape.reverts() not working as expected [APE-674]

### ISSUE THREAD

**Issue by franfran20** [ApeWorX/ape#1322]
### Environment information

- OS:  linux 
- Python Version: 3.10.6
- `ape` and plugin versions:

```sh
$ ape --version
# 0.6.2

$ ape plugins list
# Installed Plugins:
  vyper       0.6.1
```

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
# name: flex
```

### What went wrong?

I have some vyper code that has different loan options. Each loan option is represented by a number. Valid Loan Options are numbers 1 and 2. I could've used some other value to represent them but personal preferences.

The vyper code surrounding the logic looks soemthing like this, where the `loan_type` is a param of the function 

```vyper
if _loan_type != 0 or _loan_type != 1 :
        raise "Loan Type Does Not Exist"
```

The test look something like this: 

```python

def test_propose_loan_reverts_when_unaccepted_loan_type_is_used(accounts, acct):
    invalid_loan_type = 4
    with ape.reverts("Loan Type Does Not Exist"):
        flex_core.propose_loan(invalid_loan_type , other_loan_params, sender=acct)

```

Ape knows that a revert is supposed to occur because it throws this error
`ERROR tests/test_propose.py::test_propose_loan_reverts_when_unaccepted_loan_type_is_used - ape.exceptions.ContractLogicError: Loan Type Does Not Exist`

The tests fails which isn't expected. The test is supposed to pass because we expected the revert.
Maybe I'm doing something wrong with the vyper code or somethings wrong with my test logic or an ape based bug. Im not too sure but would love help on this. Would also give feedback if I'm able to work around it.

**Comment by fubuloubu** [comment]
@helloibis can you try and debug this?

**Comment by franfran20** [comment]
We can close the issue. The fault came from my vyper code. Wasnt checking for a possibilty of the two parameters only a single one.

**Comment by franfran20** [comment]
Sleepy eyes I guess...But yeah thanks for the fast response. Much appreciated!
