### ISSUE TITLE
Incorrect import remapping [APE-688]

### ISSUE THREAD

**Issue by 0rtis** [ApeWorX/ape#1329]
### Environment information

- OS: linux
- Python Version: 3.8010
- `ape` and plugin versions: 0.6.3

### What went wrong?
import remapping is filling the first string match instead of the actual path.

For example
```
solidity:
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/4.6.0"
    - "@openzeppelin/contracts-upgradeable=OpenZeppelinUpgradeable/4.6.0"
```

all import in solidity file will be first matched against "@openzeppelin/contracts"
for example ` import "@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol" ` wille be matched and replaced with `"OpenZeppelin/4.6.0/proxy/transparent/ProxyAdmin.sol"` for compilation

but `import "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol"` will also be matched and replaced with `"OpenZeppelin/4.6.0-upgradeable/token/ERC20/ERC20Upgradeable.sol"` which is incorrect !

### How can it be fixed?

The current mapping is done on a first string match which is incorrect. It should match the actual path (based on separator `/`) or at least take the longuest string match.

**Comment by helloibis** [comment]
We're still working on this but other users that experience this issue: a quick workaround is to ensure the longest import is first so it gets matched first. For example I had a test project that also used OpenZeppelin without issue, but my import remappings were:

```
solidity:
  import_remapping:
    - "@openzeppelin/contracts-upgradeable=OpenZeppelinUpgradeable/4.6.0"
    - "@openzeppelin/contracts=OpenZeppelin/4.6.0"
```

We'll update this ticket once we make progress on fixing the matching 👍
