### ISSUE TITLE
Bug: Avalanche won't install on new reduced size docker image because GCC doesn't exist in python-slim [APE-707]

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#1336]
issue: https://github.com/apeworx/ape/pull/1334#issuecomment-1466864443

fix: https://github.com/apeworx/ape/pull/1334#issuecomment-1467023659

**Comment by sabotagebeats** [comment]
alternatively could add avalanche to recommended-plugins and it would work then out of the box.

**Comment by sabotagebeats** [comment]
@fubuloubu @unparalleled-js let me know your thoughts and if so I will make sure this works and then make a PR to add avalanche to recommended-plugins.

**Comment by unparalleled-js** [comment]
Maybe we should make an `ape-slim` versus a bigger, more dev friendly ape

**Comment by fubuloubu** [comment]
> Maybe we should make an `ape-slim` versus a bigger, more dev friendly ape

Yeah, this was my thought too. Have `ape` and `ape-slim`. Perhaps there is a better way of creating images that support additional plugin installation though

**Comment by sabotagebeats** [comment]
@fubuloubu @unparalleled-js one issue that I'm having is that ape-avalanche is on an old version and doesn't have the right pins so I'm getting stuck in dependency hell
https://pypi.org/project/ape-avalanche/
```
ape-avalanche 0.1.0a3
pip install ape-avalanche
```

**Comment by sabotagebeats** [comment]
In the meantime @PoCk3T-SPAI please use the workaround I posted until we resolve this issue.

**Comment by sabotagebeats** [comment]
I think there are still also some dependency issues, even without ape-avalanche, one example: 

```
INFO: pip is looking at multiple versions of eth-hash to determine which version is compatible with other requirements. This could take a while.
Collecting eth-hash[pycryptodome]<1.0.0,>=0.2.0
  Using cached eth_hash-0.4.0-py3-none-any.whl (9.0 kB)
  Using cached eth_hash-0.3.3-py3-none-any.whl (8.9 kB)
```

**Comment by fubuloubu** [comment]
Yes I don't think that ape-avalanche is up to date. I haven't had time to work on it, but I do think we have access now

**Comment by sabotagebeats** [comment]
@fubuloubu we have our own version but the one in pypi is the old version: 
https://github.com/albertocevallos/ape-avalanche

**Comment by sabotagebeats** [comment]
working on release here: 
https://github.com/ApeWorX/ape-avalanche/pull/2

**Comment by sabotagebeats** [comment]
release has been made, just need pypi updated to point to our repo. I don't think I have the ability to do this because I am not a maintainer. https://pypi.org/project/ape-avalanche/

**Comment by sabotagebeats** [comment]
pypi has been updated with new release.

**Comment by PoCk3T-SPAI** [comment]
Thanks a lot @sabotagebeats , I tried to give a try to the `latest` Docker image with the updated PyPi pointing to the new Avalanche release, but I can't `ape compile` anymore as part of my build process since my smart contracts rely on accessing the Github of OpenZepellin -> it looks like "git" is not included in the latest/trimmed Docker image?

As a fallback, I tried to install it myself, but I can't seem to run `sudo apt-get install git` in my own Dockerfile as it looks like Ape Docker image is using a user without sudo access (trying without `sudo` gives me permission error)

Should users like myself try to workaround `git` missing or is it a package worth adding in Ape Dockerfile?

**Comment by sabotagebeats** [comment]
@PoCk3T-SPAI is you use the USER in your dockerfile you should be able to install it. In addition you should be able to include it when you're installing gcc:
```
FROM apeworx/ape:latest

USER root

RUN apt-get update \
    && apt-get install -y \
    --no-install-recommends -o \
    APT::Immediate-Configure=false \
    gcc g++
    
RUN ape plugins install \
    polygon \
    bsc \
    avalanche \
    arbitrum \
    optimism \
    fantom \
    starknet \
    solidity \
    alchemy \
    infura \
    etherscan \
    --upgrade

USER harambe
```
let me know if this works for you in the meantime and we will discuss how to best add those functionalities back to the docker image in the long term without bloating it.

**Comment by sabotagebeats** [comment]
@unparalleled-js @fubuloubu if we add the apt-get for git and gcc as mentioned above back to the docker image it increases size to 739MB from 446MB

**Comment by PoCk3T-SPAI** [comment]
Thank you once again @sabotagebeats for the prompt feedbacks/actions

RE your last comment https://github.com/ApeWorX/ape/issues/1336#issuecomment-1469039420 : thanks to your work on https://github.com/ApeWorX/ape-avalanche/pull/2 it looks like we do not need GCC (I'm able to use Avalanche plugin on `latest` Docker image without GCC)... so... maybe only GIT to maintain compatibility with [the doc on dependencies](https://docs.apeworx.io/ape/stable/userguides/config.html#dependencies) ?

RE your suggestion https://github.com/ApeWorX/ape/issues/1336#issuecomment-1469019048: I'm not sure how our environments differ between you and I but I had to add a `chown` in the mix to make it work, see working example below, in case it helps the next newbie like myself coming here:
```
FROM apeworx/ape:latest

USER root

RUN apt-get update \
    && apt-get install -y \
    --no-install-recommends -o \
    APT::Immediate-Configure=false \
    git

RUN chown -R harambe /home/harambe/project

USER harambe    
...
RUN ape compile
```

**Comment by sabotagebeats** [comment]
Related: #1340

**Comment by sabotagebeats** [comment]
@PoCk3T-SPAI as I mentioned in #1340 if you can give it a shot to copy the directory after you assume the harambe user, it may work without the CHOWN, since I'm not having that problem with the chown when using --volume. Let me know how that goes!

**Comment by sabotagebeats** [comment]
Since we have resolved the gcc issue by updating the avalanche plugin, I'm going to close this. If it is still an issue please let me know!
