### ISSUE TITLE
Create a Contract Object with ABI [APE-709]

### ISSUE THREAD

**Issue by arjunaskykok** [ApeWorX/ape#1338]
### Overview

With the web3.py library, I usually construct a Contract object this way:

```python
pool_instance = web3.eth.contract(address=pool_address, abi=pool_abi)
```

But with ape, I have to rely on Etherscan API to load up the similar Contract object:

```bash
$ export ETHERSCAN_API_KEY=xxx
```

```python
from ape import Contract
pool_instance = Contract(pool_address)
```

I would like to avoid API calls to external services.

### Specification

Something like this is good:

```python
from ape import Contract
pool_instance = Contract(pool_address, pool_abi)
```

Or add a way to convert web3.py's Contract object to ape's Contract object:

```python
from ape import Contract
pool_instance = web3.eth.contract(address=pool_address, abi=pool_abi)
ape_pool_instance = Contract(pool_instance)
```

**Comment by fubuloubu** [comment]
You can actually pass an arbitrary ABI to it today, but you have to wrap it as a `ethpm_types.ContractType` object first

Easiest way to do this is
```py
ct = ContractType.parse_obj({"abi": my_abi})
c = Contract(address, ct)
```

**Comment by antazoey** [comment]
Completed by https://github.com/ApeWorX/ape/pull/1635
