### ISSUE TITLE
Uniswap V3 repo version not recognized [APE-820]

### ISSUE THREAD

**Issue by MMtis** [ApeWorX/ape#1381]
### Environment information

- OS: win (but using ubuntu with wsl for this project)
- Python Version: 3.10.6
- `ape` and plugin versions:

```sh
$ ape --version
0.5.9

$ ape plugins list
Installed Plugins:
  chainstack    0.5.0a1
  solidity      0.6.2
```

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
dependencies:
  - name: Uniswap
    github: Uniswap/v3-core
    version: 1.0.0
  - name: Uniswap
    github: Uniswap/v3-periphery
    version: 1.3.0
```

### What went wrong?

- After compiling the project, the Uniswap V3 repo dependencies versions are not getting recognized. I'm fairly new to Apeworx, so maby I'm missing something.

```sh
$ ape compile
ERROR: (ProjectError) Unknown version '1.0.0' for repo 'v3-core'.
```
Since there is no release for this project, I tried different versions v1.0.0, V1.0.0 but none worked.

### How can it be fixed?

The repo does not have a release. So for it to work I had to fork it and create a release.

**Comment by unparalleled-js** [comment]
Hello @MMtis ! Do this:

```yaml
dependencies:
  - name: Uniswap
    github: Uniswap/v3-core
    branch: v1.0.0
```

Reason:
The `version:` key in the config will use the GitHub release API to try and fetch a published package version. It looks Uniswap is not publishing releases this way. The `branch:` config option will use branches or tags. In this case, the release tag is perfect!

I just tried this and it seems to work.

**Comment by MMtis** [comment]
> Hello @MMtis ! Do this:
> 
> ```yaml
> dependencies:
>   - name: Uniswap
>     github: Uniswap/v3-core
>     branch: v1.0.0
> ```
> 
> Reason: The `version:` key in the config will use the GitHub release API to try and fetch a published package version. It looks Uniswap is not publishing releases this way. The `branch:` config option will use branches or tags. In this case, the release tag is perfect!
> 
> I just tried this and it seems to work.

Hello @unparalleled-js ,

Thank you for the tip ! It's definitely better than forking the repo.
It also worked for me.

**Comment by unparalleled-js** [comment]
> > Hello @MMtis ! Do this:
> 
> > 
> 
> > ```yaml
> 
> > dependencies:
> 
> >   - name: Uniswap
> 
> >     github: Uniswap/v3-core
> 
> >     branch: v1.0.0
> 
> > ```
> 
> > 
> 
> > Reason: The `version:` key in the config will use the GitHub release API to try and fetch a published package version. It looks Uniswap is not publishing releases this way. The `branch:` config option will use branches or tags. In this case, the release tag is perfect!
> 
> > 
> 
> > I just tried this and it seems to work.
> 
> 
> 
> Hello @unparalleled-js ,
> 
> 
> 
> Thank you for the tip ! It's definitely better than forking the repo.
> 
> It also worked for me.
> 
> 

Awesome! Also, I have a PR that makes both ways work, but will warn if you're meaning to use the tag. So it'll be less confusing and still work... Thank you!
