### ISSUE TITLE
Expand `network_option` argument to be more useful [APE-881]

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1401]
### Overview

Currently, `network_option` will provide a variable `network` that just reflects the flag as passed, whether it's the default e.g. `"ethereum"` or a specific triple e.g. `"ethereum:local:test"`

However, this is not too helpful, because often I want to know the name of the ecosystem, network (and maybe the provider)

### Specification

At a basic level of consistency, this flag should expand to what the current triple is that it's using, even if a default

It would additional be nicer if I could specific `ecosystem`, `network`, and `provider` *optionally* so that I can leverage whatever I need (introspect the context) e.g.:
```py
@click.command(cls=NetworkBoundCommand)
@network_option()
def stuff(ecosystem, network, provider, ...):
# or def stuff(ecosystem, network, ...):
# or def stuff(network, ...):
# or def stuff(...):
# etc....
    ...
```

Further, it would be *most* useful if these were references to the specific objects, instead of just their names, so that I could use them. I often use this feature expecting it to be a `NetworkAPI` subclass, not realizing it's just a string and not even the string I want

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by antazoey** [comment]
What if it just returned the `provider`? Some users may not want so many params in their tests.
And you could do this:

```
provider.network
provider.network.ecosystem
```

to access the same objects.

**Comment by antazoey** [comment]
Oh I realize you mean to fill in these optionally. I see now. That is awesome actually.

**Comment by fubuloubu** [comment]
> realizing you mean optionally fill in those params. That may be do-able, that would be a nice feature

Yeah, I mean half the time I don't want _any_ of those arguments in my function, I just want it to connect for me and that's it
