### ISSUE TITLE
description of base_fee doesn't match implementation [APE-933]

### ISSUE THREAD

**Issue by wakamex** [ApeWorX/ape#1429]
[base_fee](https://github.com/ApeWorX/ape/blob/f0b5b9d44ac4a50ba6b45ab5c11635b39fafcb01/src/ape/api/providers.py#L292) is defined as:
> The minimum value required to get your transaction included on the **next** block.

Which seems consistent with its usage in [prepare_transaction](https://github.com/ApeWorX/ape/blob/f0b5b9d44ac4a50ba6b45ab5c11635b39fafcb01/src/ape/api/providers.py#L1145) where a transaction that doesn't specify gas has its max gas set to `self.base_fee + txn.max_priority_fee`. If the goal here is to prepare a transaction that will be included on the **next** block, we'd need to use the base fee of the **next **block. So far so good.

The issue is that the current implementation doesn't give us that. Instead it returns the base fee of the **latest** which you can see here: https://github.com/ApeWorX/ape/blob/f0b5b9d44ac4a50ba6b45ab5c11635b39fafcb01/src/ape/api/providers.py#L640

I think this should be fixed to either:
1. Change the docstring of the base_fee property to reflect its implementation, returning the **latest** black fee
2. Change the implementation to match the description as well as the use, by having it return the **next** block fee.

I prefer solution 2 and am submitting a barebones PR right now that will attempt this: #1430

**Comment by antazoey** [comment]
number 2 makes sense.

what we can do:
* today, we can fix it so that prepare_transaction uses the "pending" block
* in 0.7, change `base_fee` (the property) to do this too

**Comment by wakamex** [comment]
>     * today, we can fix it so that prepare_transaction uses the "pending" block
this is the big win for me, because it affects how new transactions are set up, and will hopefully cause fewer failed/hung transactions.

>     * in 0.7, change `base_fee` (the property) to do this too
I'm not sure why you'd want to delay this part, but push the prepare_transaction change earlier.

In my mind, the bigger "feature" change is the change in behavior for creating a new transaction, which the first bullet does. So I'd think, if we were to delay anything, we should delay that change? As you could argue it's a meaningful change to expected behavior, that could throw off some people's workflow (hopefully only for the better, but still 🤞).

Maybe `provider.base_fee` has some greater implications I'm not aware of. But i think of the distinction between `provider.base_fee` and `block.base_fee` being that the former doesn't point to a given block, it's just the *general hand-wavey* base fee, which would make sense is the base fee as defined in the current docstring (`The minimum value required to get your transaction included on the next block.`).

I'm happy with whichever direction, I know I'll be using some version of this locally 😊

I ran a few more tests, didn't even realize `get_latest("pending")` was a thing, even tho it's right there in the web3 method description, I just didn't click through to it (might be nice to add this to the ape `get_block` docstringhttps://github.com/wakamex/ape-stuff/blob/main/test_sanity-vanilla-alchemy.ipynb?). But it doesn't seem to be fully supported by ape right now. Would require a few more touchups, at least:
* https://github.com/wakamex/ape-stuff/blob/main/test_sanity-vanilla.ipynb pulls up the block using a geth connector pointed to a local erigon node on goerli, but the returned block has the same `block_number` and `base_fee` though what was previously in the `hash` is now in the `parent_hash`
* https://github.com/wakamex/ape-stuff/blob/main/test_sanity-vanilla-alchemy.ipynb fails parsing `totalDifficulty`

**Comment by antazoey** [comment]
`"latest"` is part of the doc str: https://docs.apeworx.io/ape/stable/methoddocs/api.html#ape.api.providers.ProviderAPI.get_block

what do you mean?

and the `totalDifficulty` bug is fixed and will be in the next release.

**Comment by antazoey** [comment]
feel free to open a PR with both of the changes and we can merge it in as a bug fix
