### ISSUE TITLE
value is not a valid integer (type=type_error.integer) [APE-960]

### ISSUE THREAD

**Issue by Aviksaikat** [ApeWorX/ape#1441]
### Environment information

- OS: Linux 
- Python Version: 3.10.9
- `ape` and plugin versions:

```sh
$ ape --version
0.6.9

$ ape plugins list
Installed Plugins:
  solidity    0.6.4
  hardhat     0.6.5
  alchemy     0.6.1
  ganache     0.6.6

```

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
name: fallback
plugins:
  - name: solidity
    version: 0.6.3 # version of the plugin
  - name: ganache
  - name: alchemy
ethereum:
  default_network: local
  sepolia_fork:
    default_provider: ganache
    gas_limit: max
    default_transaction_type: 0
ganache:
  server:
    port: auto
  fork:
    ethereum:
      sepolia:
        upstream_provider: alchemy
test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 10
```

### What went wrong?

- I was trying to invoke a fallback function from this contract
```js
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract Delegate {
    
    address public owner;
    
    constructor(address _owner) {
        owner = _owner;
    }
    
    function pwn() public {
        owner = msg.sender;
    }
}

contract Delegation {
    
    address public owner;
    Delegate delegate;
    
    constructor(address _delegateAddress) {
        delegate = Delegate(_delegateAddress);
        owner = msg.sender;
    }
    
    fallback() external {
        (bool result,) = address(delegate).delegatecall(msg.data);
        if (result) {
            this;
        }
    }
}
```

- Tried to create a transaction like this 
```py
data = web3.keccak(text="pwn()")
txn = networks.ecosystem.create_transaction(receiver=delegation, value="1 wei", data=data)
attacker.call(txn)
```

### Error
```py
pydantic.error_wrappers.ValidationError: 2 validation errors for DynamicFeeTransaction
to
  str type expected (type=type_error.str)
value
  value is not a valid integer (type=type_error.integer)
```

- I tried to set type like this but in vain
```py
txn = networks.ecosystem.create_transaction(receiver=delegation, value="1 wei", data=data, type=convert(2, int))
```

### How can it be fixed?

- I'm not sure about this. But I was going through the source code & found this line https://github.com/ApeWorX/ape/blob/4361309a0f446a83bf1aa46e81ed94b0e420eb3f/src/ape_ethereum/ecosystem.py#L565
![image](https://github.com/ApeWorX/ape/assets/31238298/34bfd627-0610-4602-a1a5-38d6add2a334)

- I think here it should be an Explicit type cast to int. as type is an int

![image](https://github.com/ApeWorX/ape/assets/31238298/026014f4-65ff-41f4-ad1d-ca867079cbb6)
- But @fubuloubu mentioned in the discord `That API was meant to be lower level, so we didnt add the extra conversion steps`. So I'm confused what is the issue here. Also the docs is not very clear about `create_transaction()` method.

**Comment by antazoey** [comment]
Good news! It is now a lot easier to invoke fallback functions in Ape (see this PR: https://github.com/ApeWorX/ape/pull/1463)

So what is left to close out this issue? I am making a list:

- [ ] Update method doc for `create_transaction()` to mention that generally should not be called by the user; that its purpose as an API method to all a hook for Ecosystems to customize how transactions are created.
- [ ] Add check on the line mentioned to only add value if the type is not an int.

**Comment by Aviksaikat** [comment]
cool
