### ISSUE TITLE
Clear, re-usable CLI Tooling for plugin writers

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#145]
### Overview

* Make it clear which tooling is suggested to use for plugin writers by creating a public `cli` module.
* Decouple `notify` from non-cli importers (probably will require the logging work to be completed)
* (optional) use a pass-click object to auto pass a helper class that contains methods like `abort()` and `warn()` to prevent users from having to import those all over, they could just use an `option` like `plugin_helper_option()` which will contain all the useful CLI methods for them to use.

### Specification

Allow `from ape.cli import verbose_option`
`from ape.cli import network_option`

(optional) :

```
from ape.cli import plugin_helper

@plugin_helper
def my_cmd(helper):
  helper.abort("oh no!")
```
NOTE: the above argument is not a CLI argument or option, it is auto-passed into the context  via:

(from `ape.cli.options.py`):
```
class PluginHelper:
    def abort(self, msg):
        raise Abort(msg)

    def warning(self, msg):
        notify("WARNING", msg)

helper_option = click.make_pass_decorator(PluginHelper, ensure=True)
```

### Dependencies
#57  - due to issues will circular imports, we have to get the `ape` modules to **not** use `notify()` unless they are `_cli.py` 
If they could use a normal logger (which I think is the plan?), then this will work really nicely.

**Comment by fubuloubu** [comment]
> use a pass-click object to auto pass a helper class that contains methods like `abort()` and `warn()` to prevent users from having to import those all over, they could just use an `option` like `plugin_helper_option()` which will contain all the useful CLI methods for them to use.

This is a clever idea!

**Comment by unparalleled-js** [comment]
Another idea that could be part of this:

`ape.cli.testing` that basically is a mini test-sdk for writing plugin integration tests in a way that is familiar and consistent.

**Comment by fubuloubu** [comment]
> Another idea that could be part of this:
> 
> `ape.cli.testing` that basically is a mini test-sdk for writing plugin integration tests in a way that is familiar and consistent.

love this!
