### ISSUE TITLE
bug: required_confirmations=0 does not appear to work [APE-978]

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#1450]
### Environment information

- OS: windows 11 wsl2 ubuntu linux
- Python Version: 3.10
- `ape` and plugin versions: 
```
$ ape --version
0.6.11.dev1+gbbd2e9ae
$ ape plugins list
Installed Plugins:
  etherscan    0.6.4
  alchemy      0.6.1
  solidity     0.6.5
  vyper        0.6.7
  infura       0.6.1
  hardhat      0.6.6
  foundry      0.6.8
  template     0.6.0
  ens          0.6.0
  tokens       0.6.0
```

- Contents of your `ape-config.yaml` :
none

### What went wrong?
scripts/txloop.py
```
import time
from ape import accounts

harambe = accounts.load("harambe")
harambe.set_autosign(True, passphrase="harambe")

while True:
    print(harambe.address, "balance:", harambe.balance)
    harambe.transfer(harambe, 10**17, gas_limit=10**7, required_confirmations=0)
 ```

 waits until transaction confirmed to go again

### How can it be fixed?

fix bug in `required_confirmations=0`

**Comment by antazoey** [comment]
talked offline, wait for tx is what was meant. `required_confirmations=0` is working as intended.

at this point in time, ape waits for and returns a receipt during `send_transaction()`
someday it will be more async but not today
