### ISSUE TITLE
Map solidity struct to python tuple [APE-979]

### ISSUE THREAD

**Issue by 0rtis** [ApeWorX/ape#1451]
### Overview

At the moment, solidity struct cannot be directly compared to python tuple.
For example:
```
struct MyStruct {uint id; uint value;}
function getMyStructs() public returns(MyStruct [] memory);
```

cannot be tested with `assert contract.getMyStructs() == [(42, 1337), (43, 1338), (44, 1339)]`

### Specification

Support a direct mapping of solidity struct to python tuple so that struct testing can be standardized/abstracted

### Dependencies

None

**Comment by fubuloubu** [comment]
As a note, should be able to add `__eq__` method here that overrides this class to allow struct comparisons

https://github.com/ApeWorX/ape/blob/main/src/ape/utils/abi.py#L249
