### ISSUE TITLE
bug: The ``ethPM`` module is no longer being maintained and will be deprecated with ``web3.py`` version 7 [APE-1049]

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#1473]
### Environment information

- OS: macOS / linux / win
- Python Version: x.x.x
- `ape` and plugin versions:

```sh
$ ape --version
0.6.10

$ ape plugins list
Installed Plugins:
  template     0.6.0
  solidity     0.6.5
  alchemy      0.6.1
  etherscan    0.6.6
  tokens       0.6.0
  hardhat      0.6.7
  infura       0.6.1
  ens          0.6.0
  foundry      0.6.8
  vyper        0.6.7
```

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml 
name: ApePay

plugins:
  - name: vyper
```

### What went wrong?

Please include information like:

- what command you ran
```
$ ape test --gas
/home/doge/.pyenv/versions/3.10.1/envs/apepay/lib/python3.10/site-packages/ethpm/__init__.py:5: UserWarning: The ``ethPM`` module is no longer being maintained and will be deprecated with ``web3.py`` version 7
  warnings.warn(
```

### How can it be fixed?

update pins for ethPM module

**Comment by fubuloubu** [comment]
Followed up with the snakecharmers the other day in discord, they are working on stopping this warning from appearing

**Comment by antazoey** [comment]
This got fixed in web3.py 6.5 and we are pinned already >= 6.7 we so are good to close this.
