### ISSUE TITLE
bug: Exception: Not a valid ABI interface JSON file

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#150]
### Environment information

* `ape` and plugin versions:

```
$ ape --version
# ...copy and paste result of above command here...

$ ape plugins list
# ...copy and paste result of above command here...
```

* Python Version: x.x.x
* OS: osx/linux/win

### What went wrong?
ape looking for json files in compile makes it crash if the json is not abi

Please include information like:

* what command you ran
`ape compile`
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
* full output of the error you received
`Exception: Not a valid ABI interface JSON file`

### How can it be fixed?
make jsons be ignored if they do not compile to abi

**Comment by fubuloubu** [comment]
Solution: when attempting to compile a JSON file that is not the correct format, skip compiling
