### ISSUE TITLE
(idea) `--save` flag for both `ape plugins install` and `ape pm install` [APE-1153]

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#1518]
### Overview

Make a similar feature that `npm` has for `--save` where you can install but also save the install to be written to your config.

### Specification

```bash
ape pm install --save gh:OpenZeppelin/openzeppelin-contracts --name openzeppelin --version "4.6.0"
ape plugins install hardhat --save
```
### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by fubuloubu** [comment]
Bit harder because we are using yaml, and writing back the yaml will strip any comments or formatting from a yaml file

**Comment by antazoey** [comment]
ah dang, maybe it is not worth it then.
however, as a lower priority we could add support for JSON config and then let it work on when using JSON config but that is kinda odd.

ill think about it for a while but potentially we could just close this as WON'T-DO.
