### ISSUE TITLE
Bug: ape account allows 'alias id' to be value of private key

### ISSUE THREAD

**Issue by sambacha** [ApeWorX/ape#1525]
### What went wrong?

ape accepts arbitrary input for alias when setting up ape account. this can lead to users setting their private key to this value. considering the nature of setting up ape account this can be insecure.

### How can it be fixed?

Alias should be limited ideally by less than 32 bytes (64chars). Using some levenshtein comparison would be (overkill/too much effort).

**Comment by antazoey** [comment]
good catch.
let me know if the linked PR suffices for you!
