### ISSUE TITLE
bug: when calling contract, TypeError: Exactly one of the passed values can be specified

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#154]
### Environment information

* `ape` and plugin versions:

```
$ ape --version
# ...copy and paste result of above command here...

$ ape plugins list
# ...copy and paste result of above command here...
```

* Python Version: x.x.x
* OS: osx/linux/win

### What went wrong?
`TypeError: Exactly one of the passed values can be specified. Instead, values were: (None,), {'hexstr': None}`
relating to https://github.com/ApeWorX/ape/blob/96ba02c1306d8fb4a262bdf39effe39e144785ec/src/ape_test/providers.py#L46

Please include information like:

* what command you ran
trying to call public variable on test deployed contract 
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
https://github.com/ApeWorX/ape/blob/96ba02c1306d8fb4a262bdf39effe39e144785ec/src/ape_test/providers.py#L46
* full output of the error you received

### How can it be fixed?
most of these can be deleted. 

```
    def send_call(self, txn: TransactionAPI) -> bytes:
        data = txn.as_dict()
        if data["gas"] == 0:
            data["gas"] = int(1e12)
        data = {key:value for key, value in data.items() if value is not None}
        return self._web3.eth.call(data)
```
this is most of the way there, but still fails with chainId since it is set to zero 
https://github.com/ApeWorX/ape/blob/96ba02c1306d8fb4a262bdf39effe39e144785ec/src/ape/api/providers.py#L18

Fill this in if you have ideas on how the bug could be fixed.
see above

**Comment by fubuloubu** [comment]
Resolution would be to make all of these fields equal to `None` by default, and then make sure they are removed before being called by the `web3` provider.

`chain_id` needs to default to the current `ProviderAPI.chain_id`

**Comment by unparalleled-js** [comment]
Outdated, no longer a bug
