### ISSUE TITLE
Allow specifying `block_id=` for RPC methods that support it [APE-1188]

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1540]
I was trying to fetch the contract code for an address at a specific block, but that feature isn't available:
https://github.com/ApeWorX/ape/blob/adb1e04dedbbfad7c4cc8dfc0f80928b723adbed/src/ape/api/providers.py#L202

Web3py supports it though: https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.get_code

**Comment by antazoey** [comment]
Note that we are supporting this parameter in many places, but you may have to look at the `Web3Provider`'s kwargs because they were added to avoid making breaking changes for plugins
