### ISSUE TITLE
3rd party account APIs show up in `accounts list` even though can't necessarily do other `accounts` commands on them

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#156]
### Environment information

* ape from the main branch
* ape-ledger (my implementation branch)

```
$ ape --version
# 0.1.0a23 (local from source)

$ ape plugins list
# ...copy and paste result of above command here...
```
  ape_solidity (0.1.0a2)
  ape_trezor (0.1.0a2.dev0+g2bb7300.d20210916)
  ape_ledger (0.1.dev2+ge8f73a3.d20210921)
* Python Version: 3.9.7
* OS: osx

### What went wrong?

First, implement the `AccountAPI` in new plugin.

Second, add an account however you do that in your plugin

Third, try to remove the account using the native ape command.

```bash
ape accounts delete <alias>
```

`ape` is able to find and load the account and then it attempts to call a method called `delete()`. However, this method is not part of the `AccountAPI` and thus will only exist by chance

Error output: 

```
  File "/Users/nifl/Projects/ape/src/ape_accounts/_cli.py", line 114, in delete
    account.delete()
AttributeError: 'LedgerAccount' object has no attribute 'delete'
```

### How can it be fixed?

We should add an abstract method `delete` to the `AccountAPI` so that developers know that they may need to implement it.

**Comment by unparalleled-js** [comment]
As it is encouraged for account plugins to create their own `delete` command, this still is an unexpected behavior.

I think it should attempt to call a Delete API, which should only fail with some sort of `NotImplementedError`()

**Comment by fubuloubu** [comment]
Note that only the KeyfileAccount implements this method https://github.com/ApeWorX/ape/blob/main/src/ape_accounts/accounts.py#L105

This is probably confusing, since the `ape accounts` only really works with keyfile accounts, but it's the default account type we use here

**Comment by unparalleled-js** [comment]
Should `ape accounts list` not include accounts from `ledger` and `trezor` (external account APIs) then? That would make users less likely to try other `ape accounts` commands on those and would resolve this issue.

**Comment by unparalleled-js** [comment]
I am not sure if it's a big deal, but the `ape accounts delete <alias>` will still work for external accounts if their custom Account class happens to have a `delete()` method.

We _could_ check the type of the account when loading it in the `delete` command and raise a custom error...

**Comment by unparalleled-js** [comment]
It seems like in general, if we want this, that we need a more comfortable way to loop through accounts by container type, re: the `__iter__` method of the `AccountsManager`.
The line where we inject the provider seems like something could easily be missed here, an unexpected side effect.

**Comment by fubuloubu** [comment]
> Should `ape accounts list` not include accounts from `ledger` and `trezor` (external account APIs) then? That would make users less likely to try other `ape accounts` commands on those and would resolve this issue.

Yeah, this seems like a good idea.
