### ISSUE TITLE
Utilize OTS namespace for nodes that support it in ape-geth [APE-1271]

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#1586]
### Overview

The OTS namespace has some really nice methods that could benefit users of the framework immensely such as `ots_getContractCreator`, which includes the block hash in the response, thus avoiding the need to do bin-search on the chain to find a contract's creation block.

### Specification

1. improve detection of API namespaces in ape-geth
2. create new API method for getting contract block
3. default to existing way, bin search
4. ape-geth check if api namespace allows for faster approach

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by banteg** [comment]
docs for otterscan api
https://github.com/otterscan/otterscan/blob/develop/docs/custom-jsonrpc.md

it should be supported by erigon and reth, but the namespace needs to be explicitly enabled
