### ISSUE TITLE
Compilation run many times on ape test if same ABIs [APE-1277]

### ISSUE THREAD

**Issue by arwer13** [ApeWorX/ape#1594]
### Environment information

- OS: macOS
- Python Version: 3.10.12
- `ape` and plugin versions:

```sh
ape --version
0.6.15

ape plugins list
Installed Plugins:
  infura       0.6.3
  etherscan    0.6.8
  solidity     0.6.7
  ganache      0.6.8
  hardhat      0.6.12
  foundry      0.6.14
```

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
name: ape-playground
plugins:
  - name: hardhat
  - name: ganache
  - name: infura
  - name: etherscan
  - name: solidity
  - name: foundry

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.4.2
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 3.4.0
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 2.0.0
  - name: AragonOS
    github: aragon/aragonOS
    version: 4.4.0
  - name: AragonId
    github: aragon/aragon-id
    version: 2.0.3
  - name: AragonApps
    github: aragon/aragon-apps
    version: master
  - name: LidoAragonApps
    github: lidofinance/aragon-apps
    version: apps-voting-v3.0.0

solidity:
  import_remapping:
    - "@openzeppelin/contracts-v4.4=OpenZeppelin/4.4.2"
    - "@openzeppelin/contracts=OpenZeppelin/3.4.0"
    - "openzeppelin-solidity/contracts=OpenZeppelin/2.0.0"
    - "@aragon/os/contracts=AragonOS/4.4.0"
    - "@aragon/id/contracts=AragonId/2.0.3"
    - "@aragon/apps-agent=AragonApps/master"
    - "@aragon/apps-lido=LidoAragonApps/apps-voting-v3.0.0"

hardhat:
  server:
    port: 8545
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura
        block_number: 17240000

ganache:
  server:
    port: 8545
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura
        block_number: 17240000

```

### What went wrong?

If there are multiple contracts / ABIs / interfaces with same name, they get compiled multiple times (7 in total), see the command and output https://app.warp.dev/block/DPNnjBjFwoJPFIGtFxbYbY

`ape compile` meantime does not trigger recompilation

### How can it be fixed?

1. Compile once
2. Do not recompile in general if there were no changes to a contract or ABI since the last compilation

**Comment by coccoinomane** [comment]
Hello!

I am experiencing a similar problem.  After I run tests, I always see the timestamp of __local__.json change, even if the contracts did not change.

This is a screenshot of the .build folder after I deleted it and ran tests the first time > https://d.pr/i/N6YDeY
You can see that all files in the folder have the same timestamp.

This is the same screen after the second test run > https://d.pr/i/h2Sfc8
I did not alter the smart contracts.  Still, tests took a lot of time to start, and __local__,json  file ended up with an updated timestamp.

My environment:
- I have recently upgraded to eth-ape 0.6.15 and web3 6.8.0
- This is my ape-config.yaml > https://d.pr/i/9awDMr, and
- I run tests with `ape test tests --network ::foundry`.

Cheers,
Cocco

**Comment by coccoinomane** [comment]
As a side note, I can trigger the same re-building of `__local__.json` in the console by just running `project.contracts`.

**Comment by antazoey** [comment]
Hmm, this is definitely not supposed to happen and have been trying to reproduce but haven't had any luck.

**Comment by antazoey** [comment]
Is there a way I can see the contents of your contracts? I am wondering if some weird whitespace character is causing the hash to get thrown off or something like (we had a bug like that once).

**Comment by coccoinomane** [comment]
Hello!

I managed to reproduce the issue with a simple ERC token contract.  Please find the source code [here](https://github.com/coccoinomane/web3client/tree/master/tests/ape/contracts/token).

1. I have only the token contract and the safe math library in my `contracts` folder > https://d.pr/i/aX4nwi
2. I ran `ape console` and then access `project.contracts` > https://d.pr/i/qdReDu
3. In the build folder, `__local__.json` has been rebuilt > https://d.pr/i/ChJSxb

Cheers,
Cocco

**Comment by antazoey** [comment]
@coccoinomane , you may to create another issue. Your description sounds different than the original issue here regarding multiple ABIs cause recompile. It seems you are only referring to the file itself being updated for some reason which is still valid but seems like a different issue

**Comment by coccoinomane** [comment]
Oh, I see, thanks for pointing that out, @antazoey.  Please disregards my comments.
Cheers,
Cocco

**Comment by antazoey** [comment]
So there is supposed to be a check that prevents multiple contract type names with the same name.
I noticed a bug though where it wouldn't check when some of the contracts were cached previously.
So like:

1. add contract named test.sol
2. compile
3. add contract named test.vy
4. noticed test.vy compiles indefinitely and is never cached.

^ I wonder if this the bug because you should get a contract type collision error.

Otherwise I really need more info on how to reproduce. But I am going to fix this bug at least and keep exploring

**Comment by antazoey** [comment]
I think the linked PR fixes this issue. However, I don' know for sure because the issue I am seeing is a little different than the what it is in the description. But, I was able to fix an infinite compiling issue nonetheless.

@arwer13 please re-open if this linked PR did not fix your issue. Also, I would appreciate any small repro. **What exactly do you mean by same ABIs?** You should get contract type collisions if your contracts have the same names.
