### ISSUE TITLE
Better error msg if tx timeout exhausted

### ISSUE THREAD

**Issue by arwer13** [ApeWorX/ape#1605]
### Overview

I'd like to see better error message if `provider.web3.eth.wait_for_transaction_receipt(...)` fails with `TimeExhausted`. At the moment I get `TransactionNotFoundError` which misleading and required me to dig into Ape sources. (full output example https://app.warp.dev/block/f8TajNJabxM0fEvpPDwY06)

The supposedly Ape part to modify is:
```python
try:
    receipt_data = self.web3.eth.wait_for_transaction_receipt(
        HexBytes(txn_hash), timeout=timeout
    )
except TimeExhausted as err:
    raise TransactionNotFoundError(txn_hash) from err
```

_Btw, I've though about https://docs.apeworx.io/ape/stable/userguides/transactions.html#transaction-acceptance-timeout but failed to put it in the right place for my network `ethereum:mainnet-fork:foundry`. None of `ethereum:mainnet`, `ethereum:mainnet-fork`, `ethereum:local`_ sections in `ape-config.yaml` worked.

### Specification
As MVP just remove catching `TimeExhaused` looks fine. In the case at the moment the error going to be
```
web3.exceptions.TimeExhausted: Transaction HexBytes('0x2b82cc7fbcfbb64b33712c4b3addc4ba03f3d857742dedb1a18c5f1677c13289') is not in the chain after 20 seconds
```
which is significantly more informative.

Ideally I'd like to see also some reference to the entry in ape-config.yaml in the error like "look up `transaction_acceptance_timeout` parameter in the Ape documentation".

**Comment by antazoey** [comment]
We rely on this error for additional functionality. Perhaps we could improve the message a different way? If you run with DEBUG log level, you should see the full trace and we should be preserving base exceptions `(from err)` and such.

**Comment by antazoey** [comment]
I am forwarding the exact error message from web3 now, it is included in the custom exception message, that way we have an agnostic way to catch these scenarios and still can give you the exact message.
