### ISSUE TITLE
Add remove option for `ape pm` [APE-1299]

### ISSUE THREAD

**Issue by dtdang** [ApeWorX/ape#1608]
### Overview

Add remove option for `ape pm` so users can remove packages from cli without having to manually delete them from `~/.ape/packages`.

### Specification

Describe the syntax and semantics of how you would like to see this feature implemented. The more detailed the better!

Remember, your feature is much more likely to be included if it does not involve any breaking changes.

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by Aviksaikat** [comment]
will take a look on this
