### ISSUE TITLE
Testing organizational changes

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#161]
### Overview

**We should consider moving integration tests that use mocks to functional tests.**

Reason: These tests are great in that they validate some expected behavior and increase the confidence of the code.
They are not like the integration tests though and do not need to run X times where X is the number of project types.
Also, it is a good thing that they use in mocks, in my opinion, because it allows them to be like unit tests and focus on the one bit of logic they aim to test.

The integration tests should stick to project-type based testing.

**Additionally, we should structure the functional tests to align wit the structure of the source code.**

Reason: Code auditing.  Unit tests are great for auditing code bases, especially for newcomers.
It makes it easier to change background-functionality for util methods, manager classes, etc. It allows us to know which cases we are testing for, which can sometime be indicative of which bugs we have encountered. It allows contributors to confidently change method implementations (upgrading python, for example).

Also, integration tests take a long time to run and are best suited for running in CI/CD. However, at this time, we don't have too many functional tests. So, part of this is to test the manager classes more thoroughly.

### Specification

Proposed structure:

```
tests/
   integration/
      cli/
         test_accounts.py (no mocks)
         ....
   functional/
       ape/
          test_utils.py (could contain what is in test_ether.py currently as well
          managers/
             test_accounts.py
       ape_accounts/
         test_cli.py (mocks! some of the tests that were in integration/cli can be moved here)
      ....
```

Notice that the functional tests follow the codebase structure for auditing purposes.
Notice that there is a `test_cli.py` in the functional tests that can still use the `CliRunner` however it mocks all of the ape stuff to be more like unit tests. We already have tests like this that can be moved there. Testing for error conditions or output formatting are good candidates here.
### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by fubuloubu** [comment]
Thinking more about this, my original hope was that `integration` could basically be only using ape through the CLI + as a plugin writer (writing fake test plugins), and that by pushing most of the logic towards the managers, api classes, etc. we could test those more directly under `functional`

I understand that perhaps there are not perfect alignment around this structure, but I want to avoid spliting CLI tests between folders. It would be good to agree on an approach and add a README.md under `tests/` describing this approach for contributors.

I also think that the fuzzer test case we have under the accounts CLI isn't really all that useful in it's current form.

**Comment by unparalleled-js** [comment]
I do agree with pushing as much logic out of the `_cli` modules as possible, and into managers or wherever.

**Comment by unparalleled-js** [comment]
Closing for now.
Lets make good tests all the way around.
