### ISSUE TITLE
Add documentation for `multicall`

### ISSUE THREAD

**Issue by Aviksaikat** [ApeWorX/ape#1611]
### Overview

There is a `multicall` handler in ape under `ape_ethereum`. But there is no documentation. 

- As soon as I figure things out I will start  the documentation

### Specification

Contributions are always welcome :)

### Dependencies

- My brain.

**Comment by fubuloubu** [comment]
This should be easy, just need to add the relevant plugin modules to the Ape auto-generated methoddocs: https://github.com/ApeWorX/ape/tree/main/docs/methoddocs

**Comment by Aviksaikat** [comment]
We can close this one
