### ISSUE TITLE
Unable to display unsupported extensions in `ape compile`

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#166]
### Environment information

* `ape` and plugin versions:

$ ape --version
0.1.0a23

$ ape plugins list
  ape_infura (0.1.0a2)
  ape_solidity (0.1.0a2)
  ape_vyper (0.1.0a6).   # NOTE: I removed this one to further reproduce the issue of not having compilers
  ape_ledger (0.1.dev2+ge8f73a3.d20210921)
  ape_hardhat (0.1.dev12+gfd19de4)

* Python Version: 3.9.7
* OS: macOS 11.6

Also, note that I am working with both `vyper` and `solidity` contracts.

### What went wrong?

There are two small bugs that occur when running `ape compile` when not having the correct compilers **or** not having an source files to compile (empty `contracts/` directory)

1. You get an error: `AttributeError: 'str' object has no attribute 'suffix'`

This is because part of the code assumes the type to be `Path` instead of a `str`.

After fixing that issue, the error message is still strange:

```
WARNING: No compilers detected for the following extensions:
```

notice that is not able to determine the actual extensions.
This is because they are previously excluded from the list that it checks from.

### How can it be fixed?

* Use Paths instead of str when calculating the extensions
* Get the unsupported extensions earlier in the process
* Handle when the contracts directory is empty separately
* Refactor where helpful

**Comment by fubuloubu** [comment]
One other thing to note is that I don't think the "package compiler" (`.json` extension) handles non-compliant json files well

In the event that it does not contain the right structure, it should be ignored instead of throwing. (and potentially raise a warning)
