### ISSUE TITLE
Pydantic v2+ compatibility + conflicts [APE-1399]

### ISSUE THREAD

**Issue by imrane** [ApeWorX/ape#1667]
### Overview

Attempting to install the Supabase client and ran into conflicts...any plans to support Pydantic 2+

### Motivation

Pydantic v2 is re-written in Rust and is between 5-50x faster than v1 depending on the use case. There are a number of breaking changes - here is the [migration guide][1] and [bump script][2]

Will still be able to retain backwards compatibility by directly referencing v1

``from pydantic.v1 import BaseModel``

### Dependencies

None

[1]: https://docs.pydantic.dev/latest/migration/
[2]: https://github.com/pydantic/bump-pydantic

**Comment by antazoey** [comment]
There is a PR in progress: https://github.com/ApeWorX/ape/pull/1651
It should be ready soon

**Comment by imrane** [comment]
Thanks @antazoey - will need to bump ``py-tokenlists`` as well

**Comment by fubuloubu** [comment]
> Thanks @antazoey - will need to bump ``py-tokenlists`` as well

We are thinking just to upgrade that one right away to v2
