### ISSUE TITLE
provide easy way to access a `Contract`'s selectors [APE-1424]

### ISSUE THREAD

**Issue by gosuto-inzasheru** [ApeWorX/ape#1682]
### Overview

brownie has a great feature that lets you list the selectors of a contract:
```
>>> contract.selectors
{
    '0x00c194db': "getCreationCode",
    '0x174481fa': "getCreationCodeContracts",
    '0x2da47c40': "getPauseConfiguration",
    '0x4555fb8d': "create",
    '0x6634b753': "isPoolFromFactory",
    '0x8d928af8': "getVault"
}
```

quick hack to get this done with ape is using `dir(contract)`, but that also includes lots of other (irrelevant) attributes, and doesnt give the hex selectors either.

source code for brownie is here: https://github.com/eth-brownie/brownie/blob/bc7b511583060fdaff1d4b5269aedcc1cb710bc6/brownie/network/contract.py#L101-L103

### Specification

1:1 copy of brownie's output would be great, so output `{ '<0xselector>': 'methodName', ...}`

### Dependencies

N/A afaik

**Comment by gosuto-inzasheru** [comment]
@fubuloubu recommended to look into `ethpm-types` for this:
> ethpm-types might be the best place for it
There's some selector logic in there

**Comment by mikeshultz** [comment]
I think this was pretty much done in https://github.com/ApeWorX/ethpm-types/pull/106/

You can do things like this now:

```python
In [1]: usdc = Contract("0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48")

In [2]: usdc.contract_type.identifier_lookup['0x70a08231']
Out[2]: MethodABI(type='function', name='balanceOf', stateMutability='view', inputs=[ABIType(name='account', type='address', components=None, internal_type='address')], outputs=[ABIType(name='', type='uint256', components=None, internal_type='uint256')])

In [3]: usdc.contract_type.identifier_lookup['0x70a08231'].selector
Out[3]: 'balanceOf(address)'
```

Works for errors and Event/topic identifiers as well.  Will add these methods directly on the contract instance as well for easier access.
