### ISSUE TITLE
Handle git submodules in foundry projects [APE-1429]

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1685]
### Environment information

- OS: linux
- Python Version: 3.11.6
- `ape` and plugin versions:

```sh
$ ape --version
0.6.21

$ ape plugins list
solidity
```

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
dependencies:
  - name: Uniswap
    github: Uniswap/v4-core
    ref: main
```

### What went wrong?

foundry recommends the use of git submodules for managing dependencies, which is annoying

### How can it be fixed?

fetch the submodules when you clone the project, also pay attention to foundry's remappings.txt file

**Comment by antazoey** [comment]
This is where the `ProjectAPI` should be given a chance...
We have similar issues with Hardhat projects regarding config processing for these things.
https://github.com/ApeWorX/ape-hardhat/issues/63

The project API is meant to process these alternative projects. **We already do this for Brownie projects!**

**Comment by fubuloubu** [comment]
> This is where the `ProjectAPI` should be given a chance... We have similar issues with Hardhat projects regarding config processing for these things. [ApeWorX/ape-hardhat#63](https://github.com/ApeWorX/ape-hardhat/issues/63)
> 
> The project API is meant to process these alternative projects. **We already do this for Brownie projects!**

yeah foundry is pretty unique in using this git submodule setup

additionally, this got me thinking how dependencies in dependent projects should be handled by recursively building manifests for each one of those, so we have those available to us to prevent dependency conflicts a bit better
