### ISSUE TITLE
`KeyfileAccount` should have a publicKey method

### ISSUE THREAD

**Issue by Aviksaikat** [ApeWorX/ape#1701]
### Overview

- It will be nice to have a `account.public_key` method to the `KeyfileAccount` or `AccountAPI` object.

### Specification

- I have something in my mind. If I can get a green signal then I will dive right in.

### Approach
- Using the `keyfile` property of the `KeyfileAccount` object I would like to implement this feature.
- Something like this 
```py
self.wallet = self.keyfile
passphrase = self._prompt_for_passphrase(default="")
# Decrypt the private key
self.private_key = Account.decrypt(self.wallet, passphrase)

# Derive the public key from the private key
self.pk = keys.PrivateKey(private_key)
self.public_key = self.pk.public_key
``` 

### Dependencies

- eth_account
- eth_keys
I believe both of them are already in use.

**Comment by fubuloubu** [comment]
Yeah, this seems fine. Implementation suggestion would be to add this property to `KeyfileAccount`:

```py
class KeyfileAccount(AccountAPI):
    ...

    @property
    def public_key(self) -> HexBytes:
        ... # logic you outlined above
```

**Comment by antazoey** [comment]
I am just perplexed that we have to decrypt an account's private key in order to obtain the public key... that just seems backwards?

**Comment by fubuloubu** [comment]
> I am just perplexed that we have to decrypt an account's private key in order to obtain the public key... that just seems backwards?

Not really, and address is a keccak hash so it is not able to be obtained like this, so you need to to run the key derivation to get the public key again

But yes, you can obtain the public key during the address derivation process

**Comment by Aviksaikat** [comment]
I have made some changes to cache the public key in the `keyfile` please review this pr https://github.com/ApeWorX/ape/pull/1702
