### ISSUE TITLE
ad-hoc compiler settings

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#1704]
### Overview

Provide a simple overview of what you wish to see added. Please include:

- What you are trying to do: change compiler version settings in an ad hoc manner like in https://github.com/ApeWorX/ape-vyper/pull/98 but at runtime because we need it to be compiling in a docker instance as an api request https://github.com/apeworx/hosted-compiler
- Why Ape's current functionality is inadequate to address your goal: because we are having a hard time doing that.

### Specification

Describe the syntax and semantics of how you would like to see this feature implemented. The more detailed the better!
able to pass compiler settings from core to plugins dynamically when running compilation so that we can add a compiler version option to our api endpoint.

Remember, your feature is much more likely to be included if it does not involve any breaking changes.

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.
https://github.com/ApeWorX/ape-vyper/pull/98

**Comment by antazoey** [comment]
Im thinking we do basically what we are doing with provider settings and merge them up with the file settings and make the config object that way
