### ISSUE TITLE
Very long compilation time for Importing complex Library.sol file 

### ISSUE THREAD

**Issue by avatar-lavventura** [ApeWorX/ape#1726]
### Environment information

- OS: macOS 
- Python Version: 3.8.10

```sh
$ ape --version
0.6.24

$ ape plugins list
Installed Plugins
  solidity    0.6.9
  template    0.6.1

```

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
name: alper
plugins:
  - name: solidity
  - name: foundry
```

### What went wrong?

Please include information like:

- what command you ran: `ape compile --verbosity DEBUG`

Compilation takes very long time looks like it compiles everything all over again. The compilation takes over 2 minutes, which was few seconds in `eth-brownie`.

Here is a dummy smart contract: `Lib.sol` is a complex solidity file

`Lib.sol`: could be downloaded from here: https://github.com/ebloc/ebloc-broker/blob/master/contract/contracts/Lib.sol

`Token.sol` file
```
// SPDX-License-Identifier: MIT

pragma solidity >=0.7.0 <0.9.0;
pragma experimental ABIEncoderV2;

import "./Lib.sol";

contract Token {
    string public symbol;
    string public name;
    uint256 public decimals;
    uint256 public totalSupply;

    mapping(address => uint256) balances;
    mapping(address => mapping(address => uint256)) allowed;

    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);
}
```

------

Scratch compilation takes few minutes. Than when I make a small change in `Token.sol` file (like change any variable name), and compile again, compilation takes over few minutes again, which was few seconds in `eth-brownie`. I believe imported `Lib.sol` is somehow compiled again instead of using its already compiled build.

```
$ time ape compile --verbosity DEBUG
INFO: Compiling 'eBlocBroker.sol'.
DEBUG: Compiling using Solidity compiler '0.8.22+commit.4fc1097e'
DEBUG: Compiling using Solidity compiler '0.8.22+commit.4fc1097e'
ape compile --verbosity DEBUG  75.29s user 0.83s system 99% cpu 1:16.43 total
```

### How can it be fixed?

This issue did not account in `eth-brownie`. Please test it with brownie as well, like when I compile the project it just takes few seconds to re-compile everything when I make a single change in the main `Token.sol` file.

**Comment by antazoey** [comment]
I am wondering if i may be related to the work done here: https://github.com/ApeWorX/ape/pull/730

**Comment by antazoey** [comment]
I am getting much better results on 0.7, like about twice as fast.
Can you try again there?

**Comment by antazoey** [comment]
OK the bad bugs were fixed and I am looking into why Brownie is so much faster, there seems to be an issue maybe in ape-solidity.

TBD

**Comment by antazoey** [comment]
attached PR is 86% performance increase!
now it feels like brownie when compiling solidity

**Comment by antazoey** [comment]
fixed in https://github.com/ApeWorX/ape-solidity/pull/130

**Comment by avatar-lavventura** [comment]
@antazoey Thank you
