### ISSUE TITLE
displays the evm trace, rather than python trace

### ISSUE THREAD

**Issue by Aviksaikat** [ApeWorX/ape#1728]
### Overview

Currently Ape is not handling the `evm trace` very well. Mostly it shows `python trace` messages.
For now, the only message we get is `ERROR: (ContractLogicError) Transaction failed.` for most of the traces.

**Comment by antazoey** [comment]
You need to use a provider with tracing capabilities, and yes Ape will do this then.

**Comment by mikeshultz** [comment]
Pending some package releases, traces will now show for the `Web3Provider`, `ape-foundry`'s provider, and `ape-hardhat`'s provider.  Let us know if this doesn't cover your needs.
