### ISSUE TITLE
Add public RPCs as default geth provider links [APE-1514]

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1729]
### Overview

Currently when using the geth plugin there are no configured networks that come out of the box. It owupd be nice if you can connect to a public RPC out of the box

### Specification

A large collection of networks are specified here:
https://github.com/pcaversaccio/hardhat-project-template-ts/blob/main/hardhat.config.ts#L141

### Dependencies

No dependencies. Would be nice to have multiple networks, which would require a change

**Comment by antazoey** [comment]
Can you elaborate? Currently, you can connect to any public RPC out of the box in ape-geth.

**Comment by fubuloubu** [comment]
> Can you elaborate? Currently, you can connect to any public RPC out of the box in ape-geth.

pre-configure the ape-geth plugin to connect to these public RPCs if it does not auto-detect one on the typical port

**Comment by antazoey** [comment]
ohhh now I get it.
Yes, that totally makes sense actually. I think there some other related issues in some of the L2 plugins for this.

**Comment by mikeshultz** [comment]
Good source of information: https://github.com/ethereum-lists/chains/tree/master/_data/chains

Thinking maybe we could either build our set from these to be included in our release packages or download on-the-fly when needed.  Mild preference for the former for performance and security reasons.
