### ISSUE TITLE
Link to example ape projects

### ISSUE THREAD

**Issue by engn33r** [ApeWorX/ape#1732]
### Overview

Ape is a new framework. Because it is new, I am unaware where I can find projects already using it as the sole framework to build their project. I suggest linking to project using ape in the README, to provide a reference for users to see how the configuration, tests, etc. are set up. This allows a new user to easily test out different ape cli features (for example, `ape test --gas`). Initially this may require bootstrapping with a sample repository with simple contracts and tests to demonstrate different ape features. The sample repository could later become a showcase for the features in the docs and could help test that the docs are updated with the latest implementation (#657).

### Specification

Add links in the README or elsewhere in the docs to provide an example of how to leverage the ape framework.

### Dependencies

None.

**Comment by Aviksaikat** [comment]
I'm trying to do something similar here https://github.com/Aviksaikat/Ape-Usage. Maybe we can add a category called `Use Case` & add more info there ?

**Comment by engn33r** [comment]
It should be easier to handle this in an external resource. Will move the discussion there.
