### ISSUE TITLE
feat: Add functionality to generate `accounts` when using as a `module`

### ISSUE THREAD

**Issue by Aviksaikat** [ApeWorX/ape#1760]
### Overview

Provide a simple overview of what you wish to see added. Please include:

I'm using `ape` as a module in some of my projects and 

- Add functionality to generate accounts like `ape accounts generate` does but when used as a module.

### Specification

- Something like this 
```py
from ape.accounts import generate

def generate(entropy: str, password: str) -> AccountAPI:
    [...]

# Feedback needed.
# I would say it's a lot better to show passwords than private keys ;)
new_account = generate("entropy", "password")



```

### Dependencies

Refactoring some existing code and `eth-accounts` which is already a dependency.

**Comment by fubuloubu** [comment]
Definitely agreed on the passwords vs. Private keys part

**Comment by antazoey** [comment]
Using `accounts.test_accounts.generate_test_account()` does not work?

**Comment by fubuloubu** [comment]
> Using `accounts.test_accounts.generate_test_account()` does not work?

think it's more programmatically creating real scripting accounts that stick around permanently

**Comment by Aviksaikat** [comment]
I was talking about a more persistent option when ape is used as a library rather than the module itself. Like say, I'm using the ape's AccountAPI to sign & send txs & what if the user doesn't want to specify the account when instantiating a custom class(related to the module I'm creating) & wants to send txs. So it'll be very complicated for a user to generate or add accounts using cli then use that account right? When their end goal is not using ape primarily.

**Comment by mikeshultz** [comment]
I think mostly we can just expose/wrap the [eth-account package's account generation features](https://eth-account.readthedocs.io/en/stable/eth_account.html#module-eth_account.account) and return an `AccountAPI` instance.  So probably same/similar APIs as `create(extra_entropy="")` and `create_with_mnemonic(passphrase = "", num_words = 12, language = "english", account_path = "m/44'/60'/0'/0/0")`

Will take a look at what exists currently (and what's used by the CLI commands now) and put together a PR tomorrow.

**Comment by mikeshultz** [comment]
Added `generate_account()` to the `eth_account` core plugin.  It will be documented in the accounts user guide after release.
