### ISSUE TITLE
Ape Segmentation Fault

### ISSUE THREAD

**Issue by ineiti** [ApeWorX/ape#1763]
### Environment information

- OS: macOS / arm64
- Python Version: 3.11.4
- `ape` and plugin versions:

```sh
$ ape --version
0.6.27

$ ape plugins list
Installed Plugins
  ens          0.6.2
  etherscan    0.6.10
  ganache      0.6.9
  hardhat      0.6.13
  solidity     0.6.0
```

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
name: sismondi_nft

contracts-folder: "contracts"

plugins:
  - name: solidity
    version: 0.6.0
  - name: hardhat
  - name: ens
  - name: etherscan
    version: ">=0.6.2,<0.7"
  - name: ape-ganache

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1
```

### What went wrong?

I installed a new environment using devbox with the following configuration:

```
$ cat devbox.json
{
  "packages": [
    "git@latest",
    "which@latest",
    "nodePackages.ganache-cli@latest",
    "cmake@latest",
    "nodejs@latest",
    "solc@latest",
    "vim@latest",
    "python311Packages.pip@latest",
    "python311@latest"
  ],
  "shell": {
    "init_hook": [
      ". $VENV_DIR/bin/activate"
    ],
  }
}
```

And I'm running it like this:

```
$ devbox shell --pure
$ pip install eth-ape
$ ape plugins install .
$ ape compile .
Segmentation fault: 11
$ python test_compile.py
Segmentation fault: 11
```

### How can it be fixed?

No workaround found.

I put the code here: https://github.com/ineiti/apetest

**Comment by antazoey** [comment]
Right now, ape has an issue where it segfauls when one of the `@property` errors in is calculation.
We have this fixed in our 0.7 work so it fails in a better way...

However - somehow it seem an error is happening in your `._plugin_configs`? or something... (based on your last issue raised).

**Comment by antazoey** [comment]
ill be able to help soon, but something to try until I have a chance - comment out bits of your ape-config file and see which one might be causing a problem?

Like can get ape to work at all?

Maybe for some reason the version in etherscan is bugging ape...

then we can set a breakpoint at that time and figure out why..

The real error is being annoyingly swallowed here!!

**Comment by ineiti** [comment]
> However - somehow it seems an error is happening in your `ConfigManager._plugin_configs`? or something... (based on your last issue raised).

The error from the `ConfigManager` came from the fact that I ran 

`ape compile` 

instead of 

`ape compile .`

**Comment by ineiti** [comment]
When I uncomment the `dependencies`, I get another error:

<code>$ python test_compile.py 
Traceback (most recent call last):
apetest/test_compile.py", line 19, in <module>
    container = compilers.compile_source(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
apetest/.devbox/virtenv/python311Packages.pip/.venv/lib/python3.11/site-packages/ape/managers/compilers.py", line 231, in compile_source
    compiler = self.get_compiler(compiler_name, settings=settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
apetest/.devbox/virtenv/python311Packages.pip/.venv/lib/python3.11/site-packages/ape/managers/compilers.py", line 77, in get_compiler
    for compiler in self.registered_compilers.values():
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
apetest/.devbox/virtenv/python311Packages.pip/.venv/lib/python3.11/site-packages/ape/managers/compilers.py", line 65, in registered_compilers
    self.config_manager.get_config(plugin_name=plugin_name)
apetest/.devbox/virtenv/python311Packages.pip/.venv/lib/python3.11/site-packages/ape/managers/config.py", line 261, in get_config
    self.load()  # Only loads if it needs to.
    ^^^^^^^^^^^
apetest/.devbox/virtenv/python311Packages.pip/.venv/lib/python3.11/site-packages/ape/managers/config.py", line 247, in load
    _ = self._plugin_configs
        ^^^^^^^^^^^^^^^^^^^^
apetest/.devbox/virtenv/python311Packages.pip/.venv/lib/python3.11/site-packages/ape/managers/config.py", line 218, in _plugin_configs
    config = config_class.from_overrides(user_override)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
apetest/.devbox/virtenv/python311Packages.pip/.venv/lib/python3.11/site-packages/ape/api/config.py", line 29, in from_overrides
    default_values = cls().dict()
                     ^^^^^
apetest/.devbox/virtenv/python311Packages.pip/.venv/lib/python3.11/site-packages/pydantic/v1/env_settings.py", line 40, in __init__
    super().__init__(
apetest/.devbox/virtenv/python311Packages.pip/.venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for CacheConfig
size
  value is not a valid integer (type=type_error.integer)
</code>

**Comment by antazoey** [comment]
Yes, dependencies is not specified correctly.

You likely want:

```yaml
dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.4.1
```

**Comment by antazoey** [comment]
When I comment it out, I get an error with vyper compiler.
For some reason, in your code, you are trying to compile a Solidiy file with Vyper? That is not going to work.
So I changed the vyper-compiler call to be solidiy, and I get further, but then it seems like you are trying to deploy a contract at the top level of the module, which runs before any provider connects, so that is not going to work either. You need to put code in a test or a fixture!

when I put everything in pytest fixtures, it works.

Please check this out to see what I did: https://github.com/ineiti/apetest/pull/1

**Comment by ineiti** [comment]
Thanks a lot. I tried to use `ape` as a drop-in replacement for `brownie`, which I couldn't get to run on my Mac. So the scripts and examples all come from a `brownie` project.
