### ISSUE TITLE
`ape test` is compiling pre-compiled contracts again

### ISSUE THREAD

**Issue by Aviksaikat** [ApeWorX/ape#1778]
### What went wrong?

`ape test` is compiling the pre-compiled contracts again. I remember someone mentioned this issue last month & I was able to reproduce it. Now I see that the person never opened an issue. 

### How can it be fixed?

Maybe check the signature of the contracts folder?

**Comment by antazoey** [comment]
Fixed in 0.7, or re-open for more information please.
