### ISSUE TITLE
Option to load accounts using private key

### ISSUE THREAD

**Issue by Aviksaikat** [ApeWorX/ape#1779]
### Overview

Something like this to load accounts from a private key. This is not encouraged but some times comes in handy. May be add a warning to force users to use `ape accounts import` instead of loading the private key.

### Specification

```py
from ape import accounts

acc = accounts.from_key("0x00dead")
```

### Dependencies

N/A

**Comment by fubuloubu** [comment]
Can move some of the logic here: https://github.com/ApeWorX/ape/blob/main/src/ape_accounts/_cli.py#L129

into classmethods `KeyfileAccount.from_mnemonic` or `KeyfileAccount.from_private_key`

**Comment by fubuloubu** [comment]
Actually, noticed that https://github.com/ApeWorX/ape/blob/main/src/ape_accounts/_cli.py#L103-L112 and https://github.com/ApeWorX/ape/blob/main/src/ape_accounts/_cli.py#L146-L154 are quite similar code

**Comment by mikeshultz** [comment]
Added `import_account_from_mnemonic()` and `import_account_from_private_key()` to the `eth_accounts` core plugin.  They'll be documented in the accounts user guide after release.
