### ISSUE TITLE
Adding interface creates "ContractType collisions"

### ISSUE THREAD

**Issue by wavey0x** [ApeWorX/ape#1780]
### Environment information

- OS: macOS
- Python Version: 3.10.9
- `ape` and plugin versions:

```sh
❯ ape --version
0.6.27
```

### What went wrong?
I've added a new solidity file to a project repo. In this file, I specified an interface inline called `ILocker`.
Upon compile, I receive the following message
`ERROR: (CompilerError) ContractType collision 'ILocker'.`
Turns out, this is likely due to another solidity file in same project that also specified `ILocker` interface inline.
To test, I renamed one of them, and compile succeeds.
Next, I attempted to externalize the interface into it's own file in `contracts/interfaces/ILocker.sol`.

Compile attempt fails, again with `ERROR: (CompilerError) ContractType collision 'ILocker'.`

I was eventually able to get it to succeed again by deleting contents of `.build/`.

### How can it be fixed?

Would be nice if the contents of `.build` can be deleted on the fly.

**Comment by fubuloubu** [comment]
hmm, yeah seems like it is writing in a failed compilation, or not searching for deleted files first to remove before compilation
