### ISSUE TITLE
Contract call execution not completing.

### ISSUE THREAD

**Issue by wavey0x** [ApeWorX/ape#1783]
### Environment information

- OS: macOS
- Python Version: x.x.x
- `ape` and plugin versions:

```sh
❯ ape --version
0.6.27
```

### What went wrong?
Fork execution is producing unexpected results. But same contract interactions work as expected in Brownie.

It has to do with contract call execution ~~when using a specific modifier~~ (edit: with additional tests, I proved it does not require a modifier).
You can notice that the token approval call [`setTokenApproval`](https://github.com/wavey0x/ape-repo/blob/823a92cba61be1c4ba46073c3bc19a18d127ffa8/contracts/FeeReceiver.sol#L19) should produce an `Approved` event from the token but never does. 

Yet we get success when calling [`setTokenApproval2`](https://github.com/wavey0x/ape-repo/blob/823a92cba61be1c4ba46073c3bc19a18d127ffa8/contracts/FeeReceiver.sol#L23).

### Reproduction Steps
1. clone this repo: https://github.com/wavey0x/ape-repo/
2. install plugins
3. run test `ape test tests/test_fee_receiver.py --network ::foundry -sI`

### How can it be fixed?
The contract call must fully complete. Right now it does not update state nor emit an expected event.

Fill this in if you have ideas on how the bug could be fixed.

**Comment by antazoey** [comment]
Some things learned so far:

1. The transaction is failing, meaning it is coming back with a failed status but didnt use all the gas. Web3.py has no decoded any contract logic error so nothing gets raises in that sense, and replaying the tx also does not yield any useful reasoning as to why it failed.
2. Ape should not have let the receipt through. Given this context, the expected behavior of Ape is to raise a transaction error. I have opened PRs in core and ape-foundry so far to resolve this.
3. When I analyze the source traceback, the failing PC is 2060. `ape-solidity` does not support source-tracing yet so it won't tell me which lines in the contract that correspond to, but i can dig to try and find out.

**Comment by antazoey** [comment]
the trace looks like this:

```
tx.origin=0x90be6DFEa8C80c184C442a36e17cB2439AAE25a7
YearnPrismaFeeReceiver.setTokenApproval(
  token=yPRISMA, 
  spender=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266, 
  amount=200000000000000000000
) [760 gas]
└── tx.origin.proxy() -> ""
```

**Comment by antazoey** [comment]
OK crazy stuff here, but I was able to get it to work but I am not sure if there is a bug in Ape or not.
So the `.proxy()` call is what is failing somehow, not how that is possible but that is what is happening.

Here is your modifier:

```solidity
 function isAuthenticated(address _caller) public view returns (bool) {
        if (
            _caller == LOCKER.proxy() ||
            _caller == LOCKER.governance() ||
            _caller == address(LOCKER)
        ) return true;

        return false;
    }
```

To fix it, what I did is change the order of the checks to this:

```solidity
    function isAuthenticated(address _caller) public view returns (bool) {
        if (
            _caller == address(LOCKER) ||
            _caller == LOCKER.proxy() ||
            _caller == LOCKER.governance()
        ) return true;

        return false;
    }
```

So now `address(LOCKER)` is checked first and in the case of the tests, `proxy()` is never called.

I am not sure why `proxy()` is failing though, that is something else to look into I suppose.

**Comment by antazoey** [comment]
or the equality check against proxy() causes a revert rather than False? Solidity-ism?

**Comment by antazoey** [comment]
Another clue: I have noticed that it actually fails intermittently!! Wow....
I am not sure how that can happen but sometimes it passes, sometimes it fails
