### ISSUE TITLE
Upon failed tests, local scope is lost

### ISSUE THREAD

**Issue by wavey0x** [ApeWorX/ape#1801]
### Environment information

- OS: macOS
- Python Version: 3.10.19
- `ape` and plugin versions: 

```sh
$ ape --version
0.7.1
```

### What went wrong?
When running tests that fail, I often like to debug using the console. But for some reason, I do not get access to any variables that should be within scope.

To reproduce:
- Clone this repo: https://github.com/wavey0x/prisma-stability-pool-strategy
- Install plugins
- Run tests with interactive mode on `ape test --network ::foundry -sI`
- Test will fail, putting me into interactive console mode
- I have now lost all access to variable that should be in scope, for example `strategy` or any other variable [here](https://github.com/wavey0x/prisma-stability-pool-strategy/blob/a6c1691b85377d9397e5c86ce452cad1acf07774/tests/test_operation.py#L24).

<img width="821" alt="image" src="https://github.com/ApeWorX/ape/assets/82397455/9da9275a-3d69-443b-aee2-20e9787cda1f">

### How can it be fixed?
Not sure.

**Comment by antazoey** [comment]
Odd, it works for me on all my tests and projects.
I am cloning the project you linked now and am going to see what is different.

**Comment by antazoey** [comment]
I tried following the repro instructions but the tests all pass, so I never get the console.

I am going to try and hack in a fail for now and see what happens.

**Comment by antazoey** [comment]
OK with my hacked in failure, it seems to work for me still:

<img width="925" alt="Screenshot 2024-01-02 at 11 22 01" src="https://github.com/ApeWorX/ape/assets/19540978/c73595da-561d-47e8-a44f-74fb7da721ed">

What am I missing?

**Comment by antazoey** [comment]
I undid the commit the fixes the problem in your example repo and `strategy` is still in my scope when I land in the console.

**Comment by antazoey** [comment]
problem found: updating `ipython` package causes this problem. I am guessing the 0.8.19 release.

**Comment by antazoey** [comment]
Question about the Python version, is it a mistake I can't find any Python 3.10.19.
The latest in the 3.10 series seems to be 3.10.13
