### ISSUE TITLE
Add Edit on Github link to Docs

### ISSUE THREAD

**Issue by miohtama** [ApeWorX/ape#1815]
### Overview

Add the standard Edit on Github link on Sphinx documentation. 

### Specification

Should be easy as turning on the setting in `conf.py` and making sure the Github link is correct.

**Comment by fubuloubu** [comment]
Found this in sphinx docs
https://docs.readthedocs.io/en/stable/guides/edit-source-links-sphinx.html

**Comment by rafael-abuawad** [comment]
What about the [View page source](#) link on top of every documentation page? What is wrong with that? Should the code be changed?

**Comment by antazoey** [comment]
> What about the [View page source](#) link on top of every documentation page? What is wrong with that? Should the code be changed?

So with linked PR, it is still much similar to "View page source" only it brings you to the blob so you can easily edit now and renames to "Edit on Github" which I think a lot of docs-user out there like because it allows fixing small typos and stuff easily and contributing is nice.
