### ISSUE TITLE
Testing documentation page incomplete

### ISSUE THREAD

**Issue by miohtama** [ApeWorX/ape#1822]
### What went wrong?

Currently [testing documentation page says](https://docs.apeworx.io/ape/stable/userguides/testing.html)

<img width="715" alt="image" src="https://github.com/ApeWorX/ape/assets/49922/84dedefd-eeb3-4ab1-81a3-6874f921fd15">

However there is no example of the fixture above, and it is unclear from the context where this example should be.

**Comment by fubuloubu** [comment]
Hmm, seems like it's referencing this line


https://docs.apeworx.io/ape/stable/userguides/testing.html#project-fixture

**Comment by rafael-abuawad** [comment]
Reordering the documentation may add extra clarity?

**Comment by fubuloubu** [comment]
Hmm, upon further review it seems like that 2nd section is really good intro material, perhaps what is needed is to skip mentioning fixtures until they are introduced in that later section, then show how you can reformat to use them

**Comment by rafael-abuawad** [comment]
Yeah, I was thinking about that, but also, fixtures are really important during testing and are something that should be thought from the start

**Comment by fubuloubu** [comment]
> Yeah, I was thinking about that, but also, fixtures are really important during testing and are something that should be thought from the start

This doc is more beginner-focused, so I think it best to be more gradual about introducing more advanced features
