### ISSUE TITLE
Add extra entropy for key generation message confusing

### ISSUE THREAD

**Issue by miohtama** [ApeWorX/ape#1833]
### Environment information

- OS: macOS

```sh
$ ape --version
```

```
0.7.3.
```

### What went wrong?

When running command `ape accounts generate` a user is given a prompt:

```
Add extra entropy for key generation.
```

As this message does not mean anything for normal user, and is very confusing and a user does not know how to proceed.
### How can it be fixed?

it probably should be changed to "Keep hitting some keys and enter to generate more randomness for your private key".

**Comment by fubuloubu** [comment]
I like this. Maybe it should instruct you to hit random keys and hit enter to proceed

**Comment by antazoey** [comment]
How about

```
Enhance the security of your key by adding additional random input.
```

?

**Comment by antazoey** [comment]
also - i dont think the entropy is used? 
because the `EthAccount.create` method accepts it but it isn't receiving it in this current flow

**Comment by fubuloubu** [comment]
> also - i dont think the entropy is used? because the `EthAccount.create` method accepts it but it isn't receiving it in this current flow

This is a deeper implementation detail, basically `eth-account` uses `os.urandom` which derives entropy from operating system input, including keystrokes. Basically, `os.urandom` is blocking on having a sufficient amount of system randomness, and may not execute for a while, so having the additonal keystrokes before it's called will make it run faster in those scenarios.
