### ISSUE TITLE
Documentation for deployment section is unclear

### ISSUE THREAD

**Issue by miohtama** [ApeWorX/ape#1836]
### Environment information

- OS: macOS 

```sh
$ ape --version

0.7.8
```

### What went wrong?

The [documentation](https://docs.apeworx.io/ape/stable/userguides/config.html#deployments) for `deployment` section for `ape-config.yml` is unclear.

<img width="802" alt="image" src="https://github.com/ApeWorX/ape/assets/49922/b0c3d002-75e8-4268-8951-632da470521e">

### How can it be fixed?

Update the documentation to cover

- Is this section updated by some tool
- Is this section updated manually
- Which commands read this section of the configuration file

**Comment by fubuloubu** [comment]
For clarity, the section is only updated manually, and it can be read when you do `project.MyContract.deployments` within ape

Agree it needs a lot of work to be useful
