### ISSUE TITLE
Documentation lacks example for a basic JSON-RPC provider

### ISSUE THREAD

**Issue by miohtama** [ApeWorX/ape#1837]
### Environment information

- OS: macOS / linux / win

```sh
$ ape --version

0.7.3
```

### What went wrong?

The [Configuration](https://docs.apeworx.io/ape/stable/userguides/config.html#deployments) section of the documentation lacks the basic example how to set up a JSON-RPC provider to be used with Ape.

Having a JSON-RPC configured is the first thing one needs to EVM scripting, so this should be the first example in the documentation.

### How can it be fixed?

- Add a link where to find Ethereum and EVM node services (ethereumnodes.com)
- Add an example for a public RPC node e.g. https://polygon-rpc.com
- Add an example for a private RPC node that uses an API key in its URL

**Comment by fubuloubu** [comment]
> Add an example for a private RPC node that uses an API key in its URL

Agree with all the rest, but typically I recommend that API key-based RPCs use their own separate plugin, because we can control better how that key gets loaded and displayed when logging, encouraging proper use of these secrets

**Comment by miohtama** [comment]
For the adoption of Ape, it is an unreasonable assumption that all of the various JSON-RPC providers get their own plugin. Choosing a plugin base approach only cements the market share of some of the largest (and worst) service providers like Infura and Alchemy.

**Comment by antazoey** [comment]
`ape-geth` is the generic node provider, but there are so many differences between all the nodes that using plugins is definitely recommended for the best support.

And as I have said several times, we are refactoring the generic node support in 0.8 to make more sense, thank you.
