### ISSUE TITLE
Rename `ape-geth` core plugin to `ape-node`

### ISSUE THREAD

**Issue by miohtama** [ApeWorX/ape#1843]
### What went wrong?

In the documentation, the custom RPC provider section is called `geth`.

This does not make sense, as today most developers  do not use, or not even have heard about GoEthereum.

It makes it hard to understand the documentation and the product and the user gets a feeling they need to install GoEthereum. The documentation then tries to explain this, making the situation even more confusing. There is always something wrong with the product when something is not obvious and then it needs to be explained in the documentation.

<img width="775" alt="image" src="https://github.com/ApeWorX/ape/assets/49922/c3d4d2ae-3d84-4485-8aba-377f744c9442">

### How can it be fixed?

- Rename `geth` section to `rpc`
- Allow old `geth` keyword to remain as alias, so any old configurations are not broken
- Further see https://github.com/ApeWorX/ape/issues/1842 for other reasons why this part of the documentation is insufficient

**Comment by antazoey** [comment]
we already have plans to rename in 0.8
