### ISSUE TITLE
Contracts user guide does not explain where to run Python code for deploying

### ISSUE THREAD

**Issue by miohtama** [ApeWorX/ape#1844]
### What went wrong?

The [Contracts](https://docs.apeworx.io/ape/stable/userguides/networks.html#custom-network-connection) chapter in the documentation does not answer the question "How can I deploy a contract".

I have created a contract, have unit tests for it, and now I want to deploy it on a testnet.

- Do I need to write a Python script for this?
- Is there a command line command, similar to [Foundry](https://book.getfoundry.sh/forge/deploying) I can simply run to deploy a contract
- If I need to write a Python script (why, I don't need it, or want it) how do I run this Python script?
- If i need to write a Python script, where do I store it, because the default `ape init` does not create any such folders
- What is `ContractContainer` and why should I care? How it is related to my Solidity files?

<img width="829" alt="image" src="https://github.com/ApeWorX/ape/assets/49922/33074568-e53e-4871-9c18-330f85a9f42c">

### How to fix

- There should be a simple command line command to deploy a contract, like in other smart contract development frameworks
- The documentation should cover the easiest best practices on this method of deploying a contract
- Ape default project should come with a default deployable contract, like [Counter](https://github.com/foundry-rs/foundry/blob/d46bcb3ddc768b35da8d1d29f85886476f974128/crates/evm/fuzz/src/lib.rs#L32) in Foundry
- Any documentation should refer to the default examples shipped with `ape init` template so it is not unclear for a user

**Comment by antazoey** [comment]
When using Python, you can use a script or some sort of TTY.

**Comment by fubuloubu** [comment]
I wanted to make some sort of higher level integration with CreateX bundled with ape-ethereum, which is @pcaversaccio's excellent project to standardize repeatable deployments on all EVM chains

Such a wrapper should allow doing normal deployments, as well as blueprints through a convienent CLI endpoint `ape deploy`

I agree that not having this for beginner to intermediate level deployments makes ape harder, and only if you go into more advanced scripting use cases for your deployment does advocating for the scripting system make more sense
