### ISSUE TITLE
Configuring networks section lacks a complete eample

### ISSUE THREAD

**Issue by miohtama** [ApeWorX/ape#1856]
### What went wrong?

Currently [Configuring networks](https://docs.apeworx.io/ape/stable/userguides/networks.html) section comes with an example:

<img width="733" alt="image" src="https://github.com/ApeWorX/ape/assets/49922/0920a624-c0de-46eb-beeb-d73a186d1fdc">

This information is sparse and for an external user, it not sufficient to tell how to configure networks

E.g. it does not answer the question

- How this is related to plugins
- What networks there are
- What does a fully configured example looks like (preferably at least two different networks)
- What are the configuration options in this section e.g. is `gas_limit: "max"` the only thing you can write here?

### How can it be fixed?

Have a more comprehensive section.

**Comment by antazoey** [comment]
Also huge improvements here: https://github.com/ApeWorX/ape/pull/1852/files
