### ISSUE TITLE
Contract deployment section still not sufficient even after the update

### ISSUE THREAD

**Issue by miohtama** [ApeWorX/ape#1857]
### What went wrong?

The contract deployment documentation was updated as:

<img width="788" alt="image" src="https://github.com/ApeWorX/ape/assets/49922/4b4a722d-7491-4334-b4d4-1a70ee368797">

It still not enough for an en external question and fails to address basic questions
- What is the exact command line command to run
- What is ""dev" and where does it come from
- How this is related to other Ape framework 

### How can it be fixed?

The documentation should be updated  to cover the basic usage of Ape framework to a level an external user can understand what the documentation is about.

**Comment by antazoey** [comment]
I am confused what you mean "the exact command to run".
It is documented several times in that guide that you use Python and the `.deploy` function on the account to deploy.
I am not sure what else you are looking for regarding "exact command".
