### ISSUE TITLE
configured foundry `base_fee` causes tx to fail when setting `max_priority_fee`

### ISSUE THREAD

**Issue by solarthesis** [ApeWorX/ape#1865]
### Environment information

- OS: linux
- Python Version: Python 3.9.18 
- `ape` and plugin versions:

```sh
$ ape --version
# ...copy and paste result of above command here...
0.7.4

$ ape plugins list
ape-alchemy==0.7.0
ape-foundry==0.7.3
ape-optimism==0.7.0
```

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
default_ecosystem: optimism

plugins:
  - name: ape-foundry
  - name: ape-optimism
  - name: ape-alchemy

optimism:
  mainnet:
    default_provider: alchemy

foundry:
  base_fee: 1000000
  priority-fee: 1
  host: auto
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy
    optimism:
      mainnet:
        upstream_provider: alchemy

```

### What went wrong?

Please include information like:

- what command you ran
I am impersonating an account and trying to run a contract call with the impersonated account
- the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
Note that the below is run providing the function with 
a)  impersonated account
b)  a ape worx contract
c)  function name
d)  args
It should make it easier to run any arbitrary impersonation on any contract.
```
    def apply_with_impersonation(self,impersonatedAddress,contract,funcName,args):
        with accounts.use_sender(impersonatedAddress):        
            func = getattr(contract,funcName)
            if args:
                return func(*args,base_fee="10 gwei",max_priority_fee=0)
            else:
                return func(base_fee="10 gwei",max_priority_fee=0)
```
- full output of the error you received
```
*** ape.exceptions.VirtualMachineError: max fee per gas less than block base fee
```

### How can it be fixed?

Fill this in if you have ideas on how the bug could be fixed.
Following the logic seems like it is arriving to `send_transaction` function under provider.py and giving the transaction 0 gasPrice
 before sending it
 ```
 tx_params
Out  [15]: {'chainId': 10, 'to': 'SOME_ACCOUNT', 'from': 'SOME_ACCOUNT', 'gas': 30000000, 'nonce': 3550, 'value': 0, 'data': 'SOME_DATA', 'gasPrice': 0}
```
Manually overriding `gasPrice` 0 makes the transaction suceed.

**Comment by antazoey** [comment]
Note: When you set gas price, you are using type 0 (static-fee transactions) instead of type 2 (dynamic-fee).
I believe type 2 requires a balance on the account for it to work. Does the account you are impersonating have a balance?

**Comment by solarthesis** [comment]
> Note: When you set gas price, you are using type 0 (static-fee transactions) instead of type 2 (dynamic-fee). I believe type 2 requires a balance on the account for it to work. Does the account you are impersonating have a balance?

Hi, the account i am using has a balance in his account. It is just sending the transaction with 0 gas price for some reason (type 1)

**Comment by solarthesis** [comment]
> I can force type-0 transactions to make things always work when you are impersonating a contract with 0 balance (see linked PR). But otherwise not sure.
> 
> You can always do `account += 100000` to get a balance as well

Yeah I am not sure how to make it send with type 2, or type 1, I thought that adding `base_fee` arg into the call would lead to an automatic type 2, but this isn't the case.

**Comment by antazoey** [comment]
> I thought that adding `base_fee` arg into the call would lead to an automatic type 2, but this isn't the case.

`max_fee` does this and the `priority_fee`

> It is just sending the transaction with 0 gas price for some reason (type 1)

`--gas-price 0` is the default CLI flag in the command

**Comment by antazoey** [comment]
> Yeah I am not sure how to make it send with type 2, or type 1

```
type=0
```

```
type=2
```

type 1 is access list tx, is that what you mean??

**Comment by antazoey** [comment]
i guess i dont understand what:

```
max fee per gas less than block base fee
```

has to do with gas price. Isnt gas price 0 ok?
It seems like this is related to the base fee

**Comment by solarthesis** [comment]
> > I thought that adding `base_fee` arg into the call would lead to an automatic type 2, but this isn't the case.
> 
> `max_fee` does this and the `priority_fee`
> 
> > It is just sending the transaction with 0 gas price for some reason (type 1)
> 
> `--gas-price 0` is the default CLI flag in the command, but your error shows a type 2 error

Hi, I just tried this
```
func(*args,max_fee="10 gwei",max_priority_fee=0)
*** ape.exceptions.VirtualMachineError: max fee per gas less than block base fee
```
changing `base_fee` to `base_fee` leads to the same behavior of sending the transaction with type pre-1559

**Comment by solarthesis** [comment]
> > Yeah I am not sure how to make it send with type 2, or type 1
> 
> ```
> type=0  # static fee
> type=1  # access list + static fee
> type=2  # dyanmic fee (also allows access lists)
> ```
> 
> type 1 is access list tx, is that what you mean??
> 
> also `gas=0`

Sorry type 1 i mean, pre-1559, type 2, post 1559

**Comment by solarthesis** [comment]
> ```
> max fee per gas less than block base fee
> ```

it is sending the transaction with gasPrice=0, while base_fee is not zero, from foundry, causing the evm revert, i hope this clarifies?

**Comment by solarthesis** [comment]
Do you have discord? tag me in the apeworx server and we can discuss there if you want, might be easier to do back and forths, username is `thesis`, wrote in the dumb-questions channel

**Comment by antazoey** [comment]
i am just having trouble reproducing. the only time i get this error is when my impersonated account does not have enough balance.

**Comment by solarthesis** [comment]
I am not using cli, maybe should mention this :thinking: 
```
        with ape.networks.optimism.mainnet_fork.use_default_provider(): 
            self.run_test_script()

```

**Comment by antazoey** [comment]
> I am not using cli, maybe should mention this 🤔

Ape uses the CLI under the hood

**Comment by solarthesis** [comment]
let me try and add type 2 to the args, 1 second

**Comment by solarthesis** [comment]
dm me in discord and i can help guide you to the problem. i have a good setup to go step by step, but i dont know what most steps do :laughing:

**Comment by antazoey** [comment]
> dm me in discord and i can help guide you to the problem. i have a good setup to go step by step, but i dont know what most steps do 😆

im trying to find you, I am antazoey everywhere, telegram too
