### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '9c04773acff4c5c42718bd0120c72761f458e43068a3961eb935577d1ed4effb'

### ISSUE THREAD

**Issue by mikeshultz** [ApeWorX/ape#1886]
Seen a flakey test failure recently.  Maybe eth-tester related rather than Ape, but adding this to track.  Truncated trace:

```
    def test_txn_hash_and_receipt(owner, eth_tester_provider, ethereum, kwargs):
        txn = ethereum.create_transaction(**kwargs)
>       txn = owner.prepare_transaction(txn)

tests/functional/test_transaction.py:211: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/ape/api/accounts.py:352: in prepare_transaction
    txn = self.provider.prepare_transaction(txn)
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/ape_ethereum/provider.py:854: in prepare_transaction
    gas = self.estimate_gas_cost(txn)
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/ape_test/provider.py:95: in estimate_gas_cost
    return estimate_gas(txn_data, block_identifier=block_id)
[...]
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/eth_tester/normalization/inbound.py:92: in _normalize_inbound_access_list
    [
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/eth_tester/normalization/inbound.py:96: in <listcomp>
    tuple([int(remove_0x_prefix(k)) for k in entry["storage_keys"]]),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x1293ba230>

>                   tuple([int(remove_0x_prefix(k)) for k in entry["storage_keys"]]),
                ]
            )
            for entry in access_list
        ]
    )
E   ValueError: invalid literal for int() with base 10: '9c04773acff4c5c42718bd0120c72761f458e43068a3961eb935577d1ed4effb'
```

You can see [the full trace and test failure in this GH Actions run](https://github.com/ApeWorX/ape/actions/runs/7658139402/job/20870427352?pr=1883).

**Comment by mikeshultz** [comment]
Failing code

https://github.com/ethereum/eth-tester/blob/3c76d34beb3ade64ec4569462b36351bdb9a0821/eth_tester/normalization/inbound.py#L91-L102

I'm a little surprised that storage keys would be converted to an int here.  Don't mappings and arrays get hashed (big int) slots?  Though not sure if access list only applies to the pointers which I think would have a lower index slot.

**Comment by antazoey** [comment]
I think `int(remove_0x_prefix(k))` will always fail if it is not 0.
`int('b')` for example fails.

I think at least they would need `int(remove_0x_prefix(k), 16)` to tell it the base.

I wonder why this only happens sometimes

**Comment by antazoey** [comment]
Might be fixed by this https://github.com/ethereum/eth-tester/pull/281 , can be closed after we pin to a greater version

**Comment by antazoey** [comment]
OK-  once we are able to upgrade to web3.py 7.0 range, we can close this issue.
And will reopen if we encounter the anomaly again

**Comment by antazoey** [comment]
We are already pinned to a version of web3.py / eth-tester containing the fix (https://github.com/ethereum/eth-tester/pull/281)

I thought we had to wait until the 7.0 range for some reason but I was wrong!
