### ISSUE TITLE
Deploying an interface (mistakenly) leads to a confusing error.

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#1904]
### Environment information

```python
# First, I hardcoded an ABI that I manually copied from the internet
abi = [ ... ]
# Then, I "deployed" it to my local node
contract = ContractContainer(ContractType(abi=abi)).deploy("SPORK", owner, sender=owner)
# This was dumb of me! Because the contract type only has an ABI and no code...
# Yet, it worked because you can deploy empty contracts.
SUCCESS: Contract 'Spork' deployed to: 0x5FbDB2315678afecb367f032d93F642f64180aa3
# Then I try to call one of the methods from the ABI:
contract.balanceOf(account)

# this is the failure I get:

ERROR: (ContractNotFoundError) Failed to get contract type for address '0x5FbDB2315678afecb367f032d93F642f64180aa3'. Current provider 'test' has no associated explorer plugin. Try installing an explorer plugin using ape plugins install etherscan, or using a network with explorer support.
```

**I know why it is failing obviously, it was a dumb mistake**. But still, I feel like the error message from this flow makes very little sense, like why it is talking about explorer plugins, especially was the explorer plugin would give me a similar contract anyway (the normal flow is to use Contract(addr) and the code is already deployed)... but in this case, the error message is just weird, that is he issue.

### How can it be fixed?

1. Add a warning if deploying an empty contract? Especially if there is an ABI!

2. If trying to call a method from the ABI but there is no code, raise a different error

```
ContractError("Contract has no code")
```

**Comment by fubuloubu** [comment]
if the deployment bytecode is empty, you can probably raise without any issues because that means it isn't doing anything worthy of a deployment

**Comment by antazoey** [comment]
> if the deployment bytecode is empty, you can probably raise without any issues because that means it isn't doing anything worthy of a deployment

That works for me!

**Comment by antazoey** [comment]
> probably

How certain are we?

**Comment by fubuloubu** [comment]
> > probably
> 
> How certain are we?

Nothing I can think of

> Only thing i can think of is someone testing a deployment pipeline or something

 How so?

**Comment by antazoey** [comment]
> How so?

I am imagining a hypothetical situation someone builds a deployment tool using Ape and in their tests, they deploy an empty contract to verify their deployment tool works.

**Comment by fubuloubu** [comment]
> > How so?
> 
> I am imagining a hypothetical situation someone builds a deployment tool using Ape and in their tests, they deploy an empty contract to verify their deployment tool works.

I think as long as it raises a good error it should be obvious that they should do the same thing with a dummy contract that contains some logic, at least on deployment (runtime can still be empty, we would only raise if *both* runtime and initcode are empty, because that is pointless)
