### ISSUE TITLE
[Bug]: Using ape in streamlit gives ValueError

### ISSUE THREAD

**Issue by dhruvmalik007** [ApeWorX/ape#1944]
### Environment information

- OS:  ubuntu 22.04
- Python Version: 3.8.10
- `ape` and plugin versions:

```sh
$ ape --version
eth-ape                0.6.27
$ ape plugins list
No plugins installed.
```

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):
NA

### What went wrong?

Please include information like:

- I just imported the ape package in the streamlit file 

```python 

from ape import contracts, project .....

import streamlit as st

def demo_wallet():
      from ape import accounts, Contract
      wallet = accounts[0]
     st.write("minting the tokens w/ wallet " + str(wallet))
     token = Contract(address=token_contract)



``` 

- the code that caused the failure : Mentioned above (I can share you precise script in case if the context is not fully mentioned) 
- full output of the error you received

### How can it be fixed?

The issue is of the concurrency and threading . during the streaming running the thread for the main application, invoking ape contract is trying to pre-empt it.

**Comment by fubuloubu** [comment]
Could be fixed by #1941

**Comment by antazoey** [comment]
> Could be fixed by #1941

was it?

**Comment by fubuloubu** [comment]
> > Could be fixed by #1941
> 
> was it?

I believe that @Gonmeso was attempting to solve this problem in that PR

**Comment by Gonmeso** [comment]
From what I see the fix is added in release [0.7.11](https://github.com/ApeWorX/ape/releases/tag/v0.7.11) and for me it's working as expected in prefect, @dhruvmalik007 could you try to update it to `0.7.11`?

**Comment by dhruvmalik007** [comment]
hi all and apologies for late response. it seems to create another error log as follows : 

```bash

RuntimeError: no validator found for <class 'pydantic.main.BaseModel'>, see `arbitrary_types_allowed` in Config


```

**Comment by antazoey** [comment]
> hi all and apologies for late response. it seems to create another error log as follows :
> 
> ```shell
> File "/home/ubuntu/app/version-2-geospatial-pipelines/geospatial-pipelines/.venv/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
>     exec(code, module.__dict__)
> File "/home/ubuntu/app/version-2-geospatial-pipelines/geospatial-pipelines/packages/viz/vizualization_py/app.py", line 16, in <module>
>     from ape import accounts, Contract
> File "/home/ubuntu/app/version-2-geospatial-pipelines/geospatial-pipelines/.venv/lib/python3.8/site-packages/ape/__init__.py", line 10, in <module>
>     from ape.managers.project import ProjectManager as Project
> .....
> ```

Is there more to log? I am not really seeing anything.

**Comment by antazoey** [comment]
I have verified streamlit works with Ape now, I am guessing as a result of https://github.com/ApeWorX/ape/pull/1941 as everyone else has stated.

also the script in the description of this issue has messed up indentation which will trigger such errors, but at least they now show up correctly! That is the real fix  I suppose. OK - am closing now.

<img width="871" alt="Screenshot 2024-06-24 at 13 49 06" src="https://github.com/ApeWorX/ape/assets/19540978/0924d998-e40a-46d9-98f0-b11f4c46c946">
