### ISSUE TITLE
Transaction confirmation is logged twice

### ISSUE THREAD

**Issue by BlinkyStitt** [ApeWorX/ape#1956]
### Environment information

- OS: macOS
- Python Version: 3.10.13
- `ape` and plugin versions:

```sh
$ ape --version
0.7.11.dev9+ga8d1487d

$ ape plugins list
Installed Plugins
  alchemy         0.7.1
  ens             0.7.0
  etherscan       0.7.1
  foundry         0.7.4.dev6+ga535421
  ganache         0.7.0
  hardhat         0.7.0
  infura          0.7.1
  polygon         0.7.1
  solidity        0.7.1
  template        0.7.0
  tokens          0.7.1
  vyper           0.7.0

Third-party Plugins
  flashprofits    0.0.1
  roll            0.0.3
```

### What went wrong?

The contract deploy is working, but there are two identical log messages:

```
INFO: Confirmed 0x79df564bc93a4c93d60bd5b0a8b9d30057c77eaea1aecebbf14c4ecce0910216 (total fees paid = 430287000000000)
INFO: Confirmed 0x79df564bc93a4c93d60bd5b0a8b9d30057c77eaea1aecebbf14c4ecce0910216 (total fees paid = 430287000000000)
SUCCESS: Contract 'FlashWalletV3' deployed to: 0x24EcC5E6EaA700368B8FAC259d3fBD045f695A08
INFO: Confirmed 0xff639154e0febfa0b8c6471465689dfe5727eaeefc24a2dba85a1c4206387ef3 (total fees paid = 1266760000000000)
INFO: Confirmed 0xff639154e0febfa0b8c6471465689dfe5727eaeefc24a2dba85a1c4206387ef3 (total fees paid = 1266760000000000)
SUCCESS: Contract 'PrismaArbitrageV1' deployed to: 0x876939152C56362e17D508B9DEA77a3fDF9e4083
```

**Comment by fubuloubu** [comment]
Just confirm @BlinkyStitt, the transaction isn't getting posted twice right?

**Comment by antazoey** [comment]
i am guessing this is related to this decorator thing: https://github.com/ApeWorX/ape/blob/main/src/ape_ethereum/provider.py#L119-L123

**Comment by antazoey** [comment]
I have not been able to reproduce and would like some more information please.
Which provider are you using to deploy? What network are you on? Are you running a script or using the `ape console` or running tests or something else?
Thank you

**Comment by banteg** [comment]
happens to me a lot too, both in scripts and tests
<img width="964" alt="image" src="https://github.com/ApeWorX/ape/assets/4562643/fad5be9a-1496-4847-a829-dda262c55c36">

**Comment by antazoey** [comment]
It happens to me when using Foundry but no other provider.
