### ISSUE TITLE
Expose automining via `TestProviderAPI`

### ISSUE THREAD

**Issue by derekpierre** [ApeWorX/ape#1968]
### Overview

It would be great to utilize  [EthereumTester.disable_auto_mine_transactions](https://github.com/ethereum/eth-tester?tab=readme-ov-file#ethereumtesterdisable_auto_mine_transactions) through ape without needing to do something a tad ugly like

```python
w3 = networks.provider.web3
w3.provider.ethereum_tester.disable_auto_mine_transactions()
```

Ideally, disabling auto mining would be enabled/disabled via ape's `TestProviderAPI`.

**Comment by fubuloubu** [comment]
Actually think re-opening this makes sense to eventually add it as a feature to `TestProviderAPI` like originally suggested

**Comment by antazoey** [comment]
You mean `ProviderAPI`.
None of the dev-related methods are in `TestProviderAPI`, as a couple years we had a lengthy discussion saying resulting in us not doing that.
