### ISSUE TITLE
Explicitly calling `chain.mine(1)` does not work after disabling auto mining.

### ISSUE THREAD

**Issue by derekpierre** [ApeWorX/ape#1969]
### Environment information

- OS: macOS
- Python Version: 3.12
- `ape`: 0.6.27 

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):
https://github.com/nucypher/ATxM/blob/main/tests/ape-config.yaml

### What went wrong?

Related to #1968 .

After disabling auto-mining (see #1968), it seems that the subsequent use of `chain.mine(1)` (using the `chain` fixture) does not work, and instead I have to specifically call `w3.provider.ethereum_tester.mine_block()`  for the mine to actually occur.

Ideally using the `chain` fixture should be sufficient to force the mining of blocks.

**Comment by antazoey** [comment]
are you using the eth-tester provider that comes with Ape?
I haven't been able to reproduce this one, even after implementing the auto mine functionality.

**Comment by derekpierre** [comment]
> are you using the eth-tester provider that comes with Ape?

Pretty sure we are. We don't have an explicit dependency on `eth-tester`.

**Comment by derekpierre** [comment]
That being said we use an older version of eth-ape - `eth-ape==0.6.27`. Is that issue possibly fixed in a newer version.

We haven't updated to a newer version of `eth-ape` because of #1933

**Comment by antazoey** [comment]
> We haven't updated to a newer version of `eth-ape` because of #1933

workaround for #1933 https://github.com/ApeWorX/ape/issues/1933#issuecomment-2025623526
btw, this isn't a bug on 0.8 (which isn't released yet but is in the works)

**Comment by antazoey** [comment]
still unable to reproduce this.

**Comment by antazoey** [comment]
please re-open , i dont think this is a problem!
