### ISSUE TITLE
Optional block_id parameter only read properly when in fork mode

### ISSUE THREAD

**Issue by wavey0x** [ApeWorX/ape#1970]
### Environment information

```sh
$ ape --version
# 0.7.13
```

### What went wrong?

Ape allows a shortened `block_id` optional parameter designed to achieve the identical behavior as `block_identifier` for calls targeting historical blocks.

However, it was noticed (h/t @0xkorin) that when connecting to rpc via `ethereum:mainnet`, we get different results than when connecting via fork. Specifically, when connecting this way, the parameter is ignored and the call targets chain head.

Intended behavior only happens when in fork mode.

Here is an example of output when on fork. (can use the [script here](https://gist.github.com/wavey0x/f605a53deacdee50e089e14649cfbff9https://gist.github.com/wavey0x/f605a53deacdee50e089e14649cfbff9) to reproduce)

```
In [5]: ycrv.balanceOf(POOL, block_id=SNAPSHOT_HEIGHT-500_000)
Out[5]: 6653067659730073687412989
 
In [6]: ycrv.balanceOf(POOL, block_id=SNAPSHOT_HEIGHT)
Out[6]: 6653067659730073687412989
 
In [7]: ycrv.balanceOf(POOL)
Out[7]: 6653067659730073687412989
 
In [8]: ycrv.balanceOf(POOL, block_identifier=SNAPSHOT_HEIGHT)
Out[8]: 6672806608781332562172057
```

**Comment by antazoey** [comment]
What provider are you using for mainnet when you are not forking?

**Comment by wavey0x** [comment]
> What provider are you using for mainnet when you are not forking?

i run with `--network ethereum:mainnet:https://...`

**Comment by antazoey** [comment]
the attached PR should address the issue, but let me know if it does not.
