### ISSUE TITLE
return value structs are unpicklable

### ISSUE THREAD

**Issue by banteg** [ApeWorX/ape#1976]
### What went wrong?

pickling works for events, but not for struct return values of function calls. this prevents some caching libraries from working.

```python
$ ape console --network ethereum:mainnet:geth
import pickle
pool = Contract('0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640')
logs = list(pool.Swap.range(chain.blocks.height - 10, chain.blocks.height))
call = pool.slot0()
pickle.loads(pickle.dumps(logs)) # works fine
pickle.loads(pickle.dumps(call)) # fails
# PicklingError: Can't pickle : attribute lookup slot0_return on types failed
```

**Comment by antazoey** [comment]
A way to fix this: We can stop dynamically creating models for structs and instead, use a dict-like model (kinda how we do it for events). So all structs will be the same but their data will be different, but since the main model is defined at a module level, we'd be able to pickle them.

**Comment by fubuloubu** [comment]
@banteg found the pickle method `__reduce__`

If we implement that we should be good to go
