### ISSUE TITLE
Replace `pkg_resources` with `importlib.resources`/`importlib.metadata`

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1995]
`pkg_resources` apparently doesn't ship with Python 3.12 anymore, we use it in one place:

https://github.com/ApeWorX/ape/blob/f5b6c7a91defeee74cc329479a8f76db24e35eab/src/ape/plugins/_utils.py#L131

It should be possible to replace this with some functionality from `importlib` (or maybe `packaging`)

Either way, looks like some better methods we can use vs. `pkg_resources` (which is slow)

**Comment by antazoey** [comment]
I wonder if we need to make an entry point specifically for ape plugins.

**Comment by fubuloubu** [comment]
> I wonder if we need to make an entry point specifically for ape plugins.

I think entrypoints are just for cli extensions (which we do use)

Plugins themselves need dynamic imports, or something to trigger registration from `<plugin-package>/__init__.py`
