### ISSUE TITLE
Embeded structures can't be encoded

### ISSUE THREAD

**Issue by pandadefi** [ApeWorX/ape#2007]
### Environment information

- OS: macOS
- Python Version: 3.10.12
- `ape` and plugin versions: 0.7.13

### What went wrong?

Here is a simple contract that contains a structure within a structure the inside structure contains arrays.

```solidity
contract SwapWrapper {
    enum Version {
        V1,
        V2,
        V2_1
    }

    struct Path {
        uint256[] pairBinSteps;
        Version[] versions;
        address[] tokenPath;
    }
    struct SwapData {
        address tokenIn;
        uint256 amountIn;
        uint256 minAmountOut;
        Path path;
    }

    function check(SwapData memory data) external view returns (bool) {
        return true;
    }
}
```

When running this relatively simple script:

```python
from ape import Contract, accounts, chain, project

def test_swap():
    user = accounts["0x1100000000000000000000000000000000000011"]
    swaper = user.deploy(project.SwapWrapper)
    wavax = "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7"
    usdc = "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E"
    path = {
        "pairBinSteps": [0],
        "versions": [0],
        "tokenPath": [wavax, usdc]
    }
    swap_data = {
        "tokenIn": wavax,
        "amountIn": 10**18,
        "minAmountOut": 10**7,
        "path": path
    }
    swaper.check(swap_data)
```

The python execution will stop with the following error:

```
ERROR: (ConversionError) Value '{'pairBinSteps': [0], 'versions': [0], 'tokenPath': ['0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7', '0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E']}' must be a list or tuple when given multiple types.
``` 
### How can it be fixed?

Encoding should not crash the execution.

**Comment by antazoey** [comment]
Notes so far:

* It seems like the network is `polygon-fork`, based on the contents of the test.
* `swaper = user.deploy(project.SwapWrapper)` is failing for me out-the-gate with a `ContractNotFoundError` which is extremely weird.

**Comment by pandadefi** [comment]
The network is avalanche mainnet fork.

**Comment by antazoey** [comment]
Another issue:

* User exceeds balance.

This can be explained by using `ape.accounts` module level construct rather than the `accounts` fixture. In ape, the accounts fixture are the test accounts and module level `ape.accounts` are actual, live accounts, purposely separated this way.

Fixed by doing:

```
# Use accounts fixture!
def test_swap(accounts):
    user = accounts[0]
```

Also:

> The network is avalanche mainnet fork.

I really appreciate all the info!

**Comment by pandadefi** [comment]
I have used an hardcoded address to test that out, used the first address I saw on the blockchain explorer.

**Comment by antazoey** [comment]
I am able to reproduce now, hopefully will have it fixed soon! Thank youuuu
