### ISSUE TITLE
Mention or prompt user to install corresponding compiler plugins when missing

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#203]
### Overview

Right now if we detect someone trying to compile files with extensions that are missing compiler plugins, we warn and do nothing.

### Specification

Perhaps it'd be better to detect if there exists a second-class plugin that can install this type of file and either

1. prompt the user at this point to install the corresponding plugin
2. tell the user the command needed to install the plugin

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by unparalleled-js** [comment]
This probably is not doing without hardcoding them or tagging repos with what extensions they can compile
