### ISSUE TITLE
ConnectedProviderCommand does not work with `@network_option` when `use_cls_types=False`

### ISSUE THREAD

**Issue by milkyklim** [ApeWorX/ape#2055]
### Environment information

- OS: macOS 
- Python Version: Python 3.11.4

```sh
$ ape --version
0.7.20.dev6+g4a039c29

$ ape plugins list
Installed Plugins
  ens          0.7.1
  etherscan    0.7.2
  foundry      0.7.4
  solidity     0.7.3
  tokens       0.7.1
  vyper        0.7.1
```

```sh
$ cat ape-config.yaml
name: project

plugins:
  - name: foundry
  - name: solidity
  - name: vyper
  - name: ens
```

### What went wrong?

Please include information like:

Can't connect to sepolia when use 
`ape run deploy_token deploy --network https://endpoints.omniatech.io/v1/eth/sepolia/public`
or 
`ape run deploy_token deploy --network :sepolia:https://endpoints.omniatech.io/v1/eth/sepolia/public`

In both cases, connected to `ethereum:mainnet-fork:foundry`. Looks like `network` parameter is never picked up in the script.

_____

Edit from @antazoey !!!

CLI-based scripts using deprecated `cls=NetworkBoundCommand` **DO NOT** work now with `@network_option` (bug).. however, you get the `@network_option` for free so simply deleting `@network_option()` seems to fix the problem on the scripts side, as well as switching to `cls=ConnectedProviderCommand`.

This is because `NetworkBoundCommand`  sets `use_cls_types=False` to use raw values of the network and that seems to throw something off.

**Comment by antazoey** [comment]
What does your script look like?

**Comment by antazoey** [comment]
> In both cases, connected to ethereum:mainnet-fork:foundry. Looks like network parameter is never picked up in the script.

Do  you mean sepolia fork? I am a little confused by this part.

**Comment by fubuloubu** [comment]
> > In both cases, connected to ethereum:mainnet-fork:foundry. Looks like network parameter is never picked up in the script.
> 
> Do you mean sepolia fork? I am a little confused by this part.

I believe the issue is that he is using `@network_option` but it doesn't seem to recognize his choice provided via `--network`

**Comment by milkyklim** [comment]
> Do you mean sepolia fork? I am a little confused by this part.

What fubuloubu mentioned above `@network_option` doesn't seem to work.

**Comment by antazoey** [comment]
> I believe the issue is that he is using `@network_option` but it doesn't seem to recognize his choice provided via `--network`

It is a main-style script or a CLI based script?
What do you mean by "not recognized"?
Using `@network_option` _does not_ connect to the network, it only allows you to select a network from the valid choices.
Commands that automatically connect to the network use he `@command(cls=ConnectedProviderCommand)`

**Comment by antazoey** [comment]
> What fubuloubu mentioned above `@network_option` doesn't seem to work.

What do you mean by "doesn't work"? What is happening?

**Comment by antazoey** [comment]
I received more info on Telegram. The problem is with the legacy and deprecated and soon to be deleted `cls=NetworkBoundCommand`.

Migrating the script to the newer approach likely fixes it but I can try to fix the legacy bug too, but note it is deleted in 0.8.

**Comment by antazoey** [comment]
note for devs (me): It is odd that it only happens with `NetworkBoundCommand` and not `ConnectedProviderCommand`, as all `NetworkBoundCommand` does is override `ConnectedProviderCommand` and warn for deprecation.

**Comment by fubuloubu** [comment]
> I received more info on Telegram. The problem is with the legacy and deprecated and soon to be deleted `cls=NetworkBoundCommand`.
> 
> Migrating the script to the newer approach likely fixes it but I can try to fix the legacy bug too, but note it is deleted in 0.8.

Should make sure to alert people to this in the 0.8 release thread, so they don't get bit by it

The class is completely gone in 0.8? That makes it better, because you will be forced to update

**Comment by antazoey** [comment]
> Should make sure to alert people to this in the 0.8 release thread, so they don't get bit by it

We will!

> The class is completely gone in 0.8? That makes it better, because you will be forced to update

It has been deprecated all of 0.7 with a warning the whole time too.
