### ISSUE TITLE
(ape-safe) tests - Safe contracts are not cached

### ISSUE THREAD

**Issue by banteg** [ApeWorX/ape#2133]
### What went wrong?

every time i run `ape test` i see
```
Downloading safe-global/safe-smart-account@v1.3.0: : 2.93MiB [00:02, 1.35MiB/s]
```
this line makes me think github deps are not cached.

you can try this yourself in [apeworx/ape-safe](https://github.com/ApeWorX/ape-safe/blob/main/ape-config.yaml#L17-L18) repo.

### How can it be fixed?

cache the deps

**Comment by antazoey** [comment]
dependencies are cached, this is probably related to the tests in ape-safe. can we move this issue there?

**Comment by antazoey** [comment]
https://github.com/ApeWorX/ape-safe/blob/main/tests/conftest.py#L22-L25

**Comment by fubuloubu** [comment]
> https://github.com/ApeWorX/ape-safe/blob/main/tests/conftest.py#L22-L25

good catch!

we can probably give it like a standard name under cache? or I guess there's really not a problem in just using the default. I think I did this when I was having problems getting safe-contracts to install properly

**Comment by antazoey** [comment]
> we can probably give it like a standard name under cache? or I guess there's really not a problem in just using the default. I think I did this when I was having problems getting safe-contracts to install properly

This isn't the perfect solution but this is how I handled it in `ape-solidity`: https://github.com/ApeWorX/ape-solidity/blob/main/tests/conftest.py#L79-L95

**Comment by fubuloubu** [comment]
I actually think it would be fine to cache these dependencies here, both for local testing and CI

**Comment by banteg** [comment]
> this is how I handled it in `ape-solidity`

this looks like something that can be handled in ape itself. maybe we can have some utility function for testing that can either fork the data folder, making all packages available, or make a clean one.

but i think this also doesn't address an issue when you don't have the package installed and it gets installed when running tests. this needs to be cached too!

**Comment by antazoey** [comment]
> but i think this also doesn't address an issue when you don't have the package installed and it gets installed when running tests. this needs to be cached too!

Dependencies during tests do get cached, just they get cached to a temporary data folder.

**Comment by antazoey** [comment]
> this looks like something that can be handled in ape itself.

maybe this'll help: https://github.com/ApeWorX/ape/pull/2139
