### ISSUE TITLE
General: Replace PyGithub w/ GHapi

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#22]
PyGithub is LGPL licensed, switch to Apache license here:

https://github.com/fastai/ghapi

**Comment by unparalleled-js** [comment]
Is `GPLv2` license okay?

**Comment by unparalleled-js** [comment]
`pygit2` is `GPLv2` and is a more generic `git` client

**Comment by fubuloubu** [comment]
> `pygit2` is `GPLv2` and is a more generic `git` client

I believe GPLv2 is copy left, meaning you have to have a license with equal or greater rights or your in violation. Hmm... Afraid to audit this lol
