### ISSUE TITLE
RPC method `debug_setHead` being called during pytest execution, not working on Gnosis (chainId=100)

### ISSUE THREAD

**Issue by gabrielfior** [ApeWorX/ape#2215]
### Environment information

- OS: macOS
- Python Version: 3.11.9
- `ape` and plugin versions:
ape 0.8.11
ape-foundry 0.8.3

- Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml

name: prediction-market-agent-tooling

plugins:
  - name: foundry

default_ecosystem: ethereum

node:
  gnosis:
    mainnet:
      uri: MY-RPC


networks:
  custom:
     - name: mainnet                   # Required
       chain_id: 100                   # Required
       ecosystem: gnosis
       base_ecosystem_plugin: ethereum
       default_provider: node


foundry:
  host: http://localhost:8545/
  fork:
    gnosis:
      mainnet:
        upstream_provider: node

```

### What went wrong?

I'm trying to run pytest with a forked Gnosis chain as environment (using ape-foundry), so that `ape` handles `anvil` in a seamless way.
I wrote a pytest fixture like below:
```
@pytest.fixture(scope="class")
def local_web3(chain: ChainManager) -> t.Generator[ProviderAPI, None, None]:
    with chain.network_manager.fork(provider_name="foundry") as provider:
        w3 = Web3(Web3.HTTPProvider(provider.http_uri))
        yield w3

    # clean-up
    # chain.network_manager.active_provider.disconnect()
```
If I use the fixture above as is, it throws an error, see below

```
E               ape.exceptions.APINotImplementedError: RPC method 'debug_setHead' is not implemented by this node instance.

../../..//lib/python3.11/site-packages/ape_ethereum/provider.py:1121: APINotImplementedError
```

I tried adding the commented out line (`disconnect`) which solves the error - however, this makes the fixture become `per-function` based, since every time I call the fixture, it gets disconnected during clean-up. I wanted it to only disconnect in the very end.
Note that I'm aware (from the docs) that I should not call `disconnect` directly.

Please include information like:

### How can it be fixed?

I also tried overwriting the method `chain.restore = lambda x: do_nothing()`, but it's also a hacky solution.

Thank you for your guidance.

**Comment by antazoey** [comment]
To fix, we need try / except the line in `ape-node` that is

```
self.make_request("debug_setHead", [block_number_hex_str])
```

(currently line [408](https://github.com/ApeWorX/ape/blob/main/src/ape_node/provider.py#L408))

then, as a performance enhancement, maybe cache a class level flag `self._supports_debug_set_head = False` (have to define at top of class and at the beginning of the restore method, check if that flag is False and bail out early)

**Comment by antazoey** [comment]
weird, we are already handling this error in pytest: :https://github.com/ApeWorX/ape/blob/main/src/ape/pytest/fixtures.py#L122

**Comment by antazoey** [comment]
BTW! A couple things that may be a lot easier (just letting you know in case you didn't):

1. Use the forked network from the start:

```
ape test --network gnosis:mainnet-fork:foundry
```

^ I tried this and was having some success!

2. Access `web3` from the connected provider:

```
@pytest.fixture(scope="class")
def local_web3(chain: ChainManager) -> t.Generator[ProviderAPI, None, None]:
    return chain.provider.web3
```

Note: you don't have to call `.disconnect()` manually usually.

**Comment by gabrielfior** [comment]
thanks @antazoey , very helpful.
I will implement the suggested changes - in the end, what solved the problem was adding `disable-isolation` - see [commit](https://github.com/gnosis/prediction-market-agent-tooling/commit/77b55dd21a87b2b217db9ddba70a82a0860657b5#diff-41137e30b74e4512f180015cad4c581da4943aad32db06e40df0c4885c1583c1R48)

**Comment by antazoey** [comment]
> thanks @antazoey , very helpful.
> 
> in the end, what solved the problem was adding `disable-isolation` 

Yes i recommend doing this anyway in our case! But we did fix the bug so in the next release it won't error anyway.
