### ISSUE TITLE
HexInt not converted

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#2216]
Debugging a user's error in discord I noticed that this result was returning raw from RPC, which in some nodes may be a hex-encoded integer string and not an integer value (like the type hint says)

https://github.com/ApeWorX/ape/blob/bce0c181c2dad60f42bb2b341ef5c1d2afdde2f2/src/ape_ethereum/provider.py#L285

**Comment by antazoey** [comment]
Note to fixer: One can use the `ape.utils.to_int()` method which should handle all types from RPCs
