### ISSUE TITLE
General: Run functional tests before integration in CI

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#223]
### Elevator pitch:

Run functional tests on a CI job _before_ integration tests.

### Value:

Since functional tests run really fast, if they fail, the CI job will fail faster.

### Dependencies:

Perhaps a new `pytest.mark`

### Design approach:

Something like `pytest -m "not integration"` and `pytest -m "integration`

### Task list:

* [ ] CI split up in two, run functional before integration

### Estimated completion date:

N/a

### Design review:
Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
we could just run them separately like 
```py
$ pytest -m "not fuzzing" tests/functional/
$ pytest -m "not fuzzing" tests/integration/
```

**Comment by unparalleled-js** [comment]
> we could just run them separately like
> 
> ```python
> $ pytest -m "not fuzzing" tests/functional/
> $ pytest -m "not fuzzing" tests/integration/
> ```

Yeah that sounds easier
