### ISSUE TITLE
Variables with `_root` in name break `ape compile`

### ISSUE THREAD

**Issue by LHerskind** [ApeWorX/ape#2304]
### Have you ensured that all of these are up to date?

- [X] Ape
- [X] Ape plugins

### What version of Ape are you on?

0.8.15

### What command(s) is the bug in?

ape compile

### Operating System

macOS (Apple Silicon)

### Description

When running `ape compile` for a vyper contract that includes a variable with a name ending in `_root` will cause a failure which seems to be because of the validate dict implementation in `ethpm_types`. 

Compiling directly with vyper works just fine.

### Reproduction code

Minimal example 
```python
#pragma version ~=0.4.1
@external
def whoopsie():
    merkle_root: uint256 = 1
```

Running `ape compile` should cause a failure along the lines of:

```bash
.venv/lib/python3.12/site-packages/ethpm_types/source.py", line 124, in validate_dict
    data = value["root"] if "_root" in value else value
```

**Comment by LHerskind** [comment]
As I read it, a fix should be fairly simple by adding a case where `isinstance(value, str)` in `source.py` of `ethpm_types`:

```python
if isinstance(value, Path):
    data = value.read_text()
if isinstance(value, str):
    data = value
else:
    data = value["root"] if "_root" in value else value```

**Comment by antazoey** [comment]
Thanks for reporting! I am surprised this hasn't come up already 😅 .
It's fixed in the attached PR.
