### ISSUE TITLE
Sepolia Receipt Bug (blobGasPrice Input should be valid integer)

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#2329]
### Have you ensured that all of these are up to date?

- [X] Ape
- [X] Ape plugins

### What version of Ape are you on?

0.8.15

### What command(s) is the bug in?

ape run

### Operating System

Linux

### Description

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for SharedBlobReceipt
blobGasPrice
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/int_type
```

**Comment by antazoey** [comment]
More info is needed.

Does this happen after making a transaction or during getting a receipt?

When I do:

```python
tx = provider.get_receipt("0x45c7eaeb61f5b6ddad12090f94453ee074f71422e68bf9ffabf35748363e17d2")
```

it does not reproduce the problem.

**Comment by antazoey** [comment]
I also tried making a transaction on sepolia and that also worked.

**Comment by fubuloubu** [comment]
> More info is needed.
> 
> Does this happen after making a transaction or during getting a receipt?
> 
> When I do:
> 
> ```python
> tx = provider.get_receipt("0x45c7eaeb61f5b6ddad12090f94453ee074f71422e68bf9ffabf35748363e17d2")
> ```
> 
> it does not reproduce the problem.

after making a transaction, it seemed weird and intermittent

**Comment by antazoey** [comment]
Which provider are you using?

**Comment by antazoey** [comment]
Another question: Do you know if this TX is failing or not?

**Comment by antazoey** [comment]
Are you actually sending a blob tx?

> SharedBlobTransaction

Filing in this would be extremely helpful, haven't been able to reproduce; I don't know what the _real_ problem is.

**Comment by fubuloubu** [comment]
> Which provider are you using?

Node

**Comment by fubuloubu** [comment]
> Another question: Do you know if this TX is failing or not?

It was not
