### ISSUE TITLE
Fast Forward Only Merge Strategies

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#233]
### Elevator pitch:

There is a GitHub feature that only allows merges to main if the branch is caught up with main (fast-forward only strategy)... I wonder if we should enforce that because then it will prevent multiple branches merging at once and causing issues with docs deploying (or other deploying).

### Value:

Safer merging to the code base, safer deploys.

### Dependencies:
GitHub admin settings

### Design approach:
Change setting in GitHub
Add note to CONTRIBUTING guide

### Task list:

* [ ] Change setting in GitHub
* [ ] Add note to contributing guide

### Estimated completion date:

n/a

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
Updated this setting
