### ISSUE TITLE
Relative pathing for contract compilation

### ISSUE THREAD

**Issue by bitwise-constructs** [ApeWorX/ape#2397]
### Describe

Have `ape compile` try to find the contract at relative path before searching for contracts folder.

**Comment by antazoey** [comment]
I think honestly relative paths work and the bug may be more related to projects with contracts in the root path not working on compile when specifying them, for some reason.

I also think there is something to think about regarding compiling in a project when you are in a nested dir... The `--project` flag helps but also may not be understood to new users of the framework. It is something to think about, not sure I like any proposed solution to that yet.

But the first paragraph is worth investigating. It the user's scenario, I would have expected it to compile and for it to have created a `.build/` folder in the cwd with the contracts folder detected as being the same as the bath path (recognized in the `contract_type.source_id`s as well).

**Comment by antazoey** [comment]
actually wasnt able to reproduce: 

```
(ape09) ➜  sources git:(fix/base-p-compile) ✗ ape compile ./ContractA.sol
INFO:     Compiling using Solidity compiler '0.8.27+commit.40a35a09'.
Input:
        ContractA.sol
        ContractB.sol
        ContractC.sol
SUCCESS:  'local project' compiled.
```
