### ISSUE TITLE
Improve error when accidentally mixed up arguments on `account.transfer()`

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#2435]
### Describe

When accidentally putting the account where the value is and the value where the account is, the error is kind of confusing

```
ape.exceptions.AccountsError: Transfer value meets or exceeds account balance for account '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266' on chain '1337' using provider 'test'.
```

### Specification

Make the error more obvious what I am actually doing wrong

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the transfer method to provide a more informative error message when users accidentally swap the account and value parameters. The new error message explicitly states the possibility of parameter confusion.

You can review changes in this commit: https://github.com/wwqwq2313/ApeWorX-ape-2435/commit/723c58aee4b6237461de268a559012b4699307a7.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
