### ISSUE TITLE
Change `SnapshotID` type to support `tuple[bytes, int]`

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#2437]
### Describe

Titanoboa's py-evm method `snapshot()` returns this type.
It seems to work in Ape but is not defined to do so.

### Specification

Maybe just add `tuple["SnapshotID", ...` to the type or something
Or `tuple[bytes, int`

**Comment by fubuloubu** [comment]
I think `SnapshotID` is just defined as `Any`
