### ISSUE TITLE
Allow loading accounts via address/address conversion

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#244]
### Overview
Support loading account by address (example pulled from readme)

### Specification
```py
a = accounts["0x...."]  # Load by raw address
# OR
a = accounts["example.eth"]  # Load by ENS (via conversion plugin)
```

**Comment by unparalleled-js** [comment]
We are able to load by address now:

```python
In [5]: address = "0x1e59ce931B4CFea3fe4B875411e280e173cB7A9C"

In [6]: accounts[address]
Out[6]: <KeyringAccount 0x1e59ce931B4CFea3fe4B875411e280e173cB7A9C>
```

^ Note: that is only an account on a local chain so not doxxing myself or anyone here

**Comment by unparalleled-js** [comment]
I just verified! I am totally able to load account by my ENS name when connected to the right network and all that! This is so wicked.

```python
a = accounts["juliya.eth"]
```
