### ISSUE TITLE
Create chain ID Enum

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#254]
### Overview

Create a chain ID enum that can be used across providers, to make the code more readable without having to translate integers in our head.

### Specification

Use https://chainlist.org/ as a reference

Include common ones (like from `ape_ethereum.NETWORKS`).

```python
class ChainId(Enum):
    ETHEREUM = 1  # Ethereum Mainnet
    EXPANSE = 2  # Expanse Mainnet
    ...
```

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by unparalleled-js** [comment]
https://github.com/ApeWorX/ape-infura/pull/10#discussion_r753700701

**Comment by fubuloubu** [comment]
Also thought about making this a package, maybe built via code gen from the chainlist api and released to pypi as a pure python module

**Comment by mikeshultz** [comment]
Created the [evmchains](https://github.com/ApeWorX/evmchains/) package that packages all the metadata available from [ethereum-lists/chains](https://github.com/ethereum-lists/chains) that I might at least partially cover this issue.  It's not an Enum, but maybe we can derive one from the data if we want it.

Brought the package into the Ape framework in PR #1880.  

Can probably leverage this a bit more than just for public RPCs.  Feedback and requests welcome in the PR or the other repo.

**Comment by antazoey** [comment]
Ya, i dont think it has to be enum, this structure makes sense because of all the data we need per chain besides just chain id so let't close
