### ISSUE TITLE
General: Import account via Mnemonic

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#259]
### Overview

Right now you an import a private key, but you should have the option to import both by mnemonic and private key (and also display both when generating)

This applies to the `ape-account` plugin.

### Specification
Brownie does this currently. Also see [here](https://eth-account.readthedocs.io/en/stable/eth_account.html#eth_account.account.Account.from_mnemonic)

### Dependencies
No dependencies

**Comment by Ninjagod1251** [comment]
@Ninjagod1251 mentioning me to the ticket so I can see it

**Comment by unparalleled-js** [comment]
One thing to note: It seems the `eth-account` feature that this feature relies on is labeled as "unaudited" with a note that it may change in the future. (Note that other features in Ape also currently use the `from_mnemonic()` classmethod). I would like to understand the risks and potential changes before investing into more features requiring this! 

More info here:
https://github.com/ethereum/eth-account/commit/94257b53b6be4d6dbdec03924c057ed0a8c8511b

**Comment by fubuloubu** [comment]
So, this was put on a blanket disclosure. I actually don't think it's that big of a deal.

Here's why:
- the mnemonic to master seed algorithm implements a checksum, and the UX is very safe
- the master seed hierarchical derivation algorithm could have a bug in it, but if it did it would generate the wrong private key which would not have the address the user would seek
- once it's in a private key format, the rest of the `eth-account` implementation is audited that deals with signing. mnemonic is not a signing method
- the implementation has been fuzzed against ethers.js

Honestly, could probably petition to remove the disclosure in `eth-account`, at the time I implemented it this was done as a cautionary measure, it's been over 2 years without any issues, and people have used that implementation in Brownie since I did, so I think that combination of factors at least makes it safe to use in ape

**Comment by unparalleled-js** [comment]
So will it be that the single prompt accepts either private key or mnemonic?

**Comment by fubuloubu** [comment]
> So will it be that the single prompt accepts either private key or mnemonic? 

Yeah, probably a mutually exclusive option to import via private key (flag only, does not accept input this way only through secret input) or input via combo of mnemonic (also secret input only) and hdpath (which can be parameter, with sensible default), all to produce a singular account
