### ISSUE TITLE
Function Scoped Fixtures do not work with `ape-test`

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#260]
### Environment information

Latest Ape

### What went wrong?

Tried to use session scoped fixtures but ran into issues. Need more information and need to look into this.

### How can it be fixed?

Fill this in if you have ideas on how the bug could be fixed.

**Comment by fubuloubu** [comment]
Function scope is by default, and that works

https://betterprogramming.pub/understand-5-scopes-of-pytest-fixtures-1b607b5c19ed

**Comment by unparalleled-js** [comment]
Do you remember which scopes do not work? I made this ticket from my notes from the last demo.

**Comment by fubuloubu** [comment]
> Do you remember which scopes do not work? I made this ticket from my notes from the last demo.

Function and Module scopes work in Brownie. Session does not. I don't typically use class scope

**Comment by unparalleled-js** [comment]
I am not sure which scope is failing here, so I am going to close this one for now
