### ISSUE TITLE
Use ExplorerAPI to display txn URLs

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#266]
### Overview

This is to show Etherscan URLs  in the terminal after deploying. (if explorer plugin is installed)

### Dependencies

`ape-etherscan` is the only explorer we have so far

**Comment by fubuloubu** [comment]
NOTE: Need to reevaulate the decision of only 0 or 1 explorer plugins being installed (if multiple is installed, it only uses the "first")

How to represent this option to users? Via config?

**Comment by unparalleled-js** [comment]
If there are multiple explorers for the network, I would expect to say all of them! I imagine most people will just install one of them most of the time.

**Comment by unparalleled-js** [comment]
Maybe we can create a new issue for handling multiple explorers. Else, let's cross that bridge at another point.

This issue was resolved in https://github.com/ApeWorX/ape/pull/405
