### ISSUE TITLE
Bug: `ape plugins install` does not bump the versions

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#269]
### Environment information

Latest ape

### What went wrong?

When you increment the version in a `ape-config.yaml` for plugins to use to install from, it does not install the update version.

**Comment by fubuloubu** [comment]
Also was thinking about version pinning, this could be the right behavior (if the `version` key is the config)

**Comment by unparalleled-js** [comment]
Maybe we should do it setup.py style? Allow `>=1.0.0,2.0.0` for example

**Comment by fubuloubu** [comment]
> Maybe we should do it setup.py style? Allow `>=1.0.0,<2.0.0` for example

yeah, I like this
