### ISSUE TITLE
Default to first dev provider that can be used on the device

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#273]
### Overview

Right now, if you don't have geth installed, ape errors when using the default provider.
I propose that we change ape to fallback to `eth-tester` somehow if it notices `geth` is not installed. Or, more generically, ape could pick the first provider it finds that it can use.

### Specification

Maybe add API property method `can_use()` --  a hook to check if binaries are present on the device, such as geth. `eth-tester` will always return `True` for `can_use()`. Pick the first development provider that you can actually use as the default provider.

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by fubuloubu** [comment]
I like this idea, as some of the providers do have installation requirements that aren't guaranteed to be installed without the user performing them. Remote RPC providers might not have the right API key set, as another example of how this might work

Could also see for remote RPC providers that they might have a huge network outage, and this "failover" cue would be very handy in gracefully handling those scenarios

**Comment by unparalleled-js** [comment]
Now that `eth-tester` is the default, it should always be on the device.
If the user says to use `geth` as the defaut and `geth` is not installed, it is a good thing that it errors.
