### ISSUE TITLE
Wait for transaction confirmations

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#274]
### Overview

Currently experiencing something unusual while developing the alchemy plugin where I get a txn hash after I send the raw transaction but it never shows up in the block explorer and also waiting for the txn receipt lasts indefinitely, making non-stop HTTP calls to Alchemy.

**Make a way for transactions to get retried after some time until there is feedback that it made it to the mempool**

### Specification

There might be a way to make web3.py do this
Otherwise, manually implement a timeout plan.

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by fubuloubu** [comment]
We have seen this with Infura as well, the remote RPC nodes might lose track of a transaction and require resubmitting it

A short term fix is to just keep the signed transaction locally, and push it a few times (with time in the middle) until there is some feedback that the transaction is in the mempool

---

As an aside, this might also be a nice use case for the transaction resubmission ideas we've had

**Comment by unparalleled-js** [comment]
Okay, I am going to adjust the description a little to reflect that instead. Turns out, there is a timeout from web3 after 120 seconds.

**Comment by unparalleled-js** [comment]
Now I am wondering if this is deployment confirmations thing?

Like, am I transacting too fast on the contract after I deploy it without waiting for enough block confirmations?

**Comment by unparalleled-js** [comment]
Ah! I just found proof of something that may be related to this problem...

My nonce does not increase fast enough before making the next transaction, so it thinks it is a "Replacement transaction".
