### ISSUE TITLE
feat: implement etherscan get_contract_type

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#280]
### Overview

need to integrate this with ape core

https://github.com/ApeWorX/ape-etherscan/pull/2

* What you are trying to do
* Why Ape's current functionality is inadequate to address your goal

### Specification

Describe the syntax and semantics of how you would like to see this feature implemented. The more detailed the better!

Remember, your feature is much more likely to be included if it does not involve any breaking changes.

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by unparalleled-js** [comment]
Done in https://github.com/ApeWorX/ape/pull/318
