### ISSUE TITLE
General: Figure out a way to test the installation of plugins

### ISSUE THREAD

**Issue by Ninjagod1251** [ApeWorX/ape#285]
### Environment information

* `ape` and plugin versions: 0.1.0a26.dev34+gb1765d1

```
$ ape --version
# ...copy and paste result of above command here...

$ ape plugins list
"""
Installed Core Plugins:
  pm
  ethereum
  networks
  test
  run
  accounts
  plugins
  console
  compile
  geth

Installed Plugins:
  vyper     0.1.0a7
"""
```

* Python Version: 3.8.10
* OS: Linux: Ubuntu 20.04

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

### What went wrong?

When I try and create a pytest to properly test the install and uninstall of the 2nd class plugins. I am unable to verify that it done correctly due to the result.output not showing the correct output to assert against.

Here is the code:
```
result = runner.invoke(ape_cli, ["plugins", "add", "solidity", "-y"])
    assert result.exit_code == 0, result.output  # no errors when it runs
    assert "Installing ape_solidity...\n" in result.output


    result = runner.invoke(ape_cli, ["plugins", "list", "-a"])
    assert result.exit_code == 0

    # TODO It is should find the solidity plugin and show assert that it is in the output
    assert "Installed Plugins:\n" in result.output
    assert "solidity" in result.output
```
### ISSUE:
* The issue is under the TODO: When I list the plugins after installing solidity. The result.output should show that solidity is under the Installed Plugins header. But it is not.

* Another issue is that this test runs more than once without me specifying it. Another TODO is to create a:
``` @skip_all_projects so I can make this header for all test not related to integration

### How can it be fixed?

* The second issue needs to a feature add to our testing suite.

**Comment by unparalleled-js** [comment]
I think this is also related to the `click.testing.CLIRunner` isolated environments.

**Comment by unparalleled-js** [comment]
Removing bug label since this only applies to the `ape` tests and is not a bug that affect users.
