### ISSUE TITLE
Feat: Pytest Figure out how to set and unset Github Access Token

### ISSUE THREAD

**Issue by Ninjagod1251** [ApeWorX/ape#286]
### Environment information

* `ape` and plugin versions: 0.1.0a26.dev34+gb1765d1

```
Plugins:
Installed Plugins:
  vyper     0.1.0a7
```

* Python Version: 3.8.10
* OS: Linux: 
* Distributor ID: Ubuntu

Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
### What went wrong?

Please include information like:
* Working with @unparalleled-js and @fubuloubu  we need to figure out a way to set the GITHUB_ACCESS_TOKEN so i can test as user with or without a token
* https://docs.pytest.org/en/6.2.x/monkeypatch.html
* https://click.palletsprojects.com/en/8.0.x/testing/
Click Runner Isolation or Monkey Patch did not work properly. Stepping into the breakpoints. I can verify the github access token is set to 'TEST'. However the output is not expected

```
def test_github_access_token(ape_cli, runner, monkeypatch):
    # from ape_plugins import utils
    # monkeypatch.setattr(utils, "SECOND_CLASS_PLUGINS", set())

    result = runner.invoke(ape_cli, ["plugins", "list"])
    breakpoint()
    assert result.exit_code == 0, "Exit was not successful"
    assert "$GITHUB_ACCESS_TOKEN not set, skipping 2nd class plugins\n" in result.output

    # github token invoke with enviorment in click documenation test cli apps
    # isolate installed enviorment during testing
```
We suspect that click runner and/or monkey patch runs in a separate isolated env. I need to figure out a way to set the env_var in the isolated env. The documentation is lack luster on how to implement that properly. 

### How can it be fixed?

I should ask the community and figure out the right way to do this. I am sure I not understanding a key concept.
here is the stackoverflow link: 
https://stackoverflow.com/questions/70175033/pytest-how-do-i-change-bashrc-token-durning-runtime

**Comment by unparalleled-js** [comment]
I suspect this is a `click` related to the isolated environments that `click.testing.CLIRunner` uses

**Comment by unparalleled-js** [comment]
I don't think this is really needed anymore, since the github token is no longer required to view the available plugins
