### ISSUE TITLE
feat: incorporate Pydantic environment variable support in `ape-config.yaml` file

### ISSUE THREAD

**Issue by NotPeopling2day** [ApeWorX/ape#292]
### Overview

Figure out how to load config from environment variables, probably using pydantic settings.
This may be a breaking change, not sure.

### Specification

https://docs.pydantic.dev/latest/usage/settings/

**Comment by unparalleled-js** [comment]
We have also talked about a `SecretStorageAPI` type thing

**Comment by gosuto-inzasheru** [comment]
i think dotenv makes sense since pydantic includes native support for it: https://pydantic-docs.helpmanual.io/usage/settings/#dotenv-env-support

**Comment by fubuloubu** [comment]
btw, this is great for loading already set environment variables, but for those looking to manage environment variables it is recommended to use something specific to your development environment like https://direnv.net/

(leaving this here for others to reference)
