### ISSUE TITLE
Testing: Equality handling between ENS address and AddressAPI

### ISSUE THREAD

**Issue by NotPeopling2day** [ApeWorX/ape#323]
### Overview

When making assertions in ape test, it would be nice to be able to assert an account is an ENS address. This will make writing tests easier and read more intuitively.

Originally a part of ticket #261 

### Specification

```python
# NOTE: `contract.owner()` returns an address like "0xAbCd...1234"
assert contract.owner() == "my-name.eth"
```

**Comment by unparalleled-js** [comment]
Probably blocked by https://github.com/ApeWorX/ape/issues/1089

**Comment by Ninjagod1251** [comment]
No longer blocked by #1089

**Comment by Ninjagod1251** [comment]
This is not longer an issue

```
In [11]: dev2 = convert("vitalik.eth", AddressType)

In [12]: assert contract.owner() != dev2
```

**Comment by unparalleled-js** [comment]
> This is not longer an issue
> 
> 
> 
> ```
> 
> In [11]: dev2 = convert("vitalik.eth", AddressType)
> 
> 
> 
> In [12]: assert contract.owner() != dev2
> 
> ```

You are calling convert here though. The issue wants the convert to happen under-the-hood.

**Comment by fubuloubu** [comment]
We can probably close this one, don't think it's super necessary to be able to convert ENS names like this and do equality checks

Probably would be more useful for things like value checking e.g.
```py
assert acct.balance == "100 ether"
assert token.balanceOf(acct) == "10 TOK"  # using `ape-tokens`
```

but again, not sure how you'd implement without hacking into the `int` type

**Comment by unparalleled-js** [comment]
I am good with closing because I also don't know how this would get done.

**Comment by Ninjagod1251** [comment]
Sorry for the confusion, but the task failed to completion!
