### ISSUE TITLE
Testing: Equality handling between currency units and int

### ISSUE THREAD

**Issue by NotPeopling2day** [ApeWorX/ape#324]
### Overview

Conversion of `"1 gwei"` to `int` would be valuable for things like specifying gas prices, as well as comparisons to account balances:
```python 
assert contract.balance == "1 ether"
```

Related to ticket #261 and #323

**Comment by fubuloubu** [comment]
temporary workaround:
```py
assert contract.balance == convert("1 ether", int)
```
