### ISSUE TITLE
Python3.10 missing Ape Compatability

### ISSUE THREAD

**Issue by johnson2427** [ApeWorX/ape#328]
ape 0.1.0-beta.1

$ python3 setup.py install

...........
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
listing git files failed - pretending there aren't any
c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
   15 | #include <ffi.h>
      |          ^~~~~~~
compilation terminated.
error: Setup script exited with error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

This requires us to download libffi-dev

$ sudo apt-get install libffi-dev

Then run: 
$ape test -k test_only_one_thing

Result:
Traceback (most recent call last):
  File "/home/blake/.local/share/virtualenvs/ape310/bin/ape", line 33, in <module>
    sys.exit(load_entry_point('eth-ape==0.1.0b2.dev1+gfd9583b6', 'console_scripts', 'ape')())
  File "/home/blake/.local/share/virtualenvs/ape310/bin/ape", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/blake/.local/share/virtualenvs/ape310/lib/python3.10/site-packages/eth_ape-0.1.0b2.dev1+gfd9583b6-py3.10.egg/ape/__init__.py", line 9, in <module>
    from .contracts import _Contract
  File "/home/blake/.local/share/virtualenvs/ape310/lib/python3.10/site-packages/eth_ape-0.1.0b2.dev1+gfd9583b6-py3.10.egg/ape/contracts/__init__.py", line 1, in <module>
    from .base import ContractContainer, ContractInstance, ContractLog, _Contract
  File "/home/blake/.local/share/virtualenvs/ape310/lib/python3.10/site-packages/eth_ape-0.1.0b2.dev1+gfd9583b6-py3.10.egg/ape/contracts/base.py", line 3, in <module>
    from eth_utils import to_bytes
  File "/home/blake/.local/share/virtualenvs/ape310/lib/python3.10/site-packages/eth_utils-1.10.0-py3.10.egg/eth_utils/__init__.py", line 4, in <module>
    import pkg_resources
  File "/home/blake/.local/share/virtualenvs/ape310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/home/blake/.local/share/virtualenvs/ape310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/home/blake/.local/share/virtualenvs/ape310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/blake/.local/share/virtualenvs/ape310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/home/blake/.local/share/virtualenvs/ape310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/blake/.local/share/virtualenvs/ape310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'packaging' distribution was not found and is required by pytest

Which just required:

$ pip install eth-ape

This is required because the setup.py fails

Then run:
$ ape test -k test_only_one_thing
Result:
====================================== test session starts ===============================================
platform linux -- Python 3.10.1, pytest-6.2.5, py-1.11.0, pluggy-0.13.1
rootdir: /home/blake/ApeWorx/ape, configfile: pyproject.toml, testpaths: tests
plugins: eth-ape-0.1.0b2.dev1+gfd9583b6, web3-5.25.0
collected 274 items / 2 errors / 274 deselected                                                                                                                                                                               

=============================================== ERRORS ============================================
____________________ ERROR collecting tests/functional/conversion/test_ether.py _______________
ImportError while importing test module '/home/blake/ApeWorx/ape/tests/functional/conversion/test_ether.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/functional/conversion/test_ether.py:3: in <module>
    from hypothesis import given
E   ModuleNotFoundError: No module named 'hypothesis'
______________________________ ERROR collecting tests/functional/manifests/test_manifest.py __________________________
ImportError while importing test module '/home/blake/ApeWorx/ape/tests/functional/manifests/test_manifest.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/functional/manifests/test_manifest.py:3: in <module>
    from hypothesis import HealthCheck, given, settings
E   ModuleNotFoundError: No module named 'hypothesis'
=============================== warnings summary ======================================
../../.local/share/virtualenvs/ape310/lib/python3.10/site-packages/pytest-6.2.5-py3.10.egg/_pytest/config/__init__.py:1114
  /home/blake/.local/share/virtualenvs/ape310/lib/python3.10/site-packages/pytest-6.2.5-py3.10.egg/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: ens
    self._mark_plugins_for_rewrite(hook)

../../.local/share/virtualenvs/ape310/lib/python3.10/site-packages/pytest-6.2.5-py3.10.egg/_pytest/config/__init__.py:1114
  /home/blake/.local/share/virtualenvs/ape310/lib/python3.10/site-packages/pytest-6.2.5-py3.10.egg/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: web3
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
====================================== short test summary info ============================================
ERROR tests/functional/conversion/test_ether.py
ERROR tests/functional/manifests/test_manifest.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

This requires us to download 2 packages:
This error occurs if you only download hypothesis
$ pip install hypothesis

When you run again, you get an error that there is no module named 'hypothesis_jsonschema'

Then run:

$ pip install jsonchema==3.2.0

This returns an error.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hypothesis-jsonschema 0.22.0 requires jsonschema>=4.0.0, but you have jsonschema 3.2.0 which is incompatible.

Once again run:

$ ape test -k test_only_one_thing

Result:
============================================== test session starts =======================================
platform linux -- Python 3.10.1, pytest-6.2.5, py-1.11.0, pluggy-0.13.1
rootdir: /home/blake/ApeWorx/ape, configfile: pyproject.toml, testpaths: tests
plugins: eth-ape-0.1.0b2.dev1+gfd9583b6, hypothesis-6.31.6, web3-5.25.0
collected 286 items / 286 deselected                                                                                                                                                                                          

================================== warnings summary ==================================
../../.local/share/virtualenvs/ape310/lib/python3.10/site-packages/pytest-6.2.5-py3.10.egg/_pytest/config/__init__.py:1114
  /home/blake/.local/share/virtualenvs/ape310/lib/python3.10/site-packages/pytest-6.2.5-py3.10.egg/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: ens
    self._mark_plugins_for_rewrite(hook)

../../.local/share/virtualenvs/ape310/lib/python3.10/site-packages/pytest-6.2.5-py3.10.egg/_pytest/config/__init__.py:1114
  /home/blake/.local/share/virtualenvs/ape310/lib/python3.10/site-packages/pytest-6.2.5-py3.10.egg/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: web3
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== 286 deselected, 2 warnings in 1.18s =====================================

* Python Version: 3.10.1
* OS: Ubuntu 20.04

There are dependency issues that are not resolved when running setup.py

We have to figure out the issue with the dependency of hypothesis and jsonschema

We also have to force libffi-dev

**Comment by fubuloubu** [comment]
Dup of #235
