### ISSUE TITLE
bug: ape tokens plugins bug

### ISSUE THREAD

**Issue by Ninjagod1251** [ApeWorX/ape#329]
### Environment information

* `ape` and plugin versions: 0.1.0b1

* Python Version: 3.8.10
* OS: linux

### What went wrong?

There is a bug when you install tokens:
```
WARNING: Error loading plugin package 'ape_tokens'.
        ImportError: cannot import name 'SIGNED_INTEGERS' from 'ape.managers.converters' (/home/user/ape/src/ape/managers/converters.py)
        (Use `--verbosity DEBUG` to see full stack-trace)
```

Please include information like:

* what command you ran
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
* full output of the error you received

### How can it be fixed?

Fill this in if you have ideas on how the bug could be fixed.

**Comment by Ninjagod1251** [comment]
This issue might also be related:
https://github.com/ApeWorX/ape/issues/328

**Comment by fubuloubu** [comment]
What's the plugin version for this?

**Comment by unparalleled-js** [comment]
We should track this issue in the `ape-tokens` repo:

https://github.com/ApeWorX/ape-tokens/issues/1

**Comment by unparalleled-js** [comment]
https://github.com/ApeWorX/ape-tokens/pull/2
