### ISSUE TITLE
Testing: Mining control via Chain Manager

### ISSUE THREAD

**Issue by evanblank3** [ApeWorX/ape#344]
### Overview

Use RPC methods https://infura.io/docs/ethereum/json-rpc/eth-mining

### Specification

Be able to control mining

```python
def mine(self, num_blocks: int=1, timestamp: Optional[int] = None) -> str:
    ...
```

Overview of chain manager

```python
class ChainManager:
    ...
    # Mining management
    def mine(self, num_blocks: int=1): ...
    def enable_automining(self): ...
    def disable_automining(self): ...
    ...
```

### Dependencies

#129

**Comment by fubuloubu** [comment]
Inside `ChainManager.mine`:
```py
if timestamp:
    self.pending_timestamp = timestamp

self.provider.mine(num_blocks)
```

**Comment by fubuloubu** [comment]
Updates to:
- https://github.com/ApeWorX/ape/blob/main/src/ape_test/providers.py#L12
- https://github.com/ApeWorX/ape-hardhat/blob/main/ape_hardhat/providers.py#L49
