### ISSUE TITLE
Testing: Interactive mode

### ISSUE THREAD

**Issue by evanblank3** [ApeWorX/ape#346]
### Overview

Open an interactive console each time a test fails when doing `ape test --pdb`
(new "interactive" flag)

### Specification

the interactive flag opens an `ape console` at the point of test failure and allows the user to debug.

_____

RESEARCH DONE:

* We are able to add custom debugger classes via configuration options: https://docs.pytest.org/en/6.2.x/usage.html#dropping-to-pdb-python-debugger-on-failures
* We need to figure out how to programmatically set the debugger class pytest uses when the user passes in the `--pdb` flag. It might mean modifying the options from config via the `pytest_configure` hook: https://docs.pytest.org/en/6.2.x/reference.html#pytest.hookspec.pytest_configure. Note that ape already has a `pytest_cofigure` hook defined here: https://github.com/ApeWorX/ape/blob/main/src/ape_test/plugin.py#L25 so might need to modify that.

**Comment by fubuloubu** [comment]
Note: Yearn devs need this!

**Comment by unparalleled-js** [comment]
```yaml
--pdbcls=IPython.core.debugger:Pdb
```

**Comment by unparalleled-js** [comment]
Sudo code for how I think this might work:

```python

    from IPython.core.debugger import Pdb

    from ape_console._cli import console
    console()
    config.option.pdbcls = Pdb

```

**Comment by Ninjagod1251** [comment]
# TODO
            # if "tx" not in namespace and len(chain.account_history):
            #     # make it easier to look at the most recent transaction
            #     namespace["tx"] = self.chain.account_history[-1]
            # To many changes to make it work

**Comment by Ninjagod1251** [comment]
The solution is being worked on with this PR #455
