### ISSUE TITLE
Testing: Transaction tracing

### ISSUE THREAD

**Issue by NotPeopling2day** [ApeWorX/ape#347]
### Overview

Provide an exported iterator of trace frames, possibly using sql alchemy with supporting database (sqlite, postgres, ect.)

### Specification

Method to `ProviderAPI`

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

### Links
https://pypi.org/project/EthTx/
https://geth.ethereum.org/docs/dapp/tracing
https://twitter.com/gnidan/status/1453902500315254784?s=20
https://etherscan.io/tx/0x0fe2542079644e107cbf13690eb9c2c65963ccb79089ff96bfaf8dced2331c92
https://ethtx.info/mainnet/0x0fe2542079644e107cbf13690eb9c2c65963ccb79089ff96bfaf8dced2331c92/
https://medium.com/@AndyPavia/swissblock-post-mortem-cream-finance-hack-7c1caff4335c

**Comment by fubuloubu** [comment]
more resources: https://eth-brownie.readthedocs.io/en/stable/core-transactions.html

**Comment by fubuloubu** [comment]
Superceded by: #700 #349 #350
