### ISSUE TITLE
Testing: Test coverage w/ code-cov support

### ISSUE THREAD

**Issue by NotPeopling2day** [ApeWorX/ape#349]
### Overview

Add test coverage with code-cov support
https://medium.com/coinmonks/brownie-evaluating-solidity-code-coverage-via-opcode-tracing-a7cf5a92d28c

### Specification

```python
    def get_coverage(self):
        """
        """

        calltree = self._calltree(show_internal=True)
        # TODO: test coverage logic
        # {Source: {Line: NumberOfHits}}
        return calltree
```

https://github.com/eth-brownie/brownie/blob/master/brownie/test/coverage.py

**Comment by fubuloubu** [comment]
https://coverage.readthedocs.io/en/latest/api_plugin.html#file-tracers
