### ISSUE TITLE
Testing: Gas reporting in tests

### ISSUE THREAD

**Issue by NotPeopling2day** [ApeWorX/ape#350]
### Overview

Create a gas report when running tests

### Specification

```python
def get_gas_usage(self):
        """
        """

        calltree = self._calltree(show_internal=True)
        # TODO: gas report logic
        # {Address: {Calldata: [GasUsed, ...]}}
        return calltree
```

https://github.com/eth-brownie/brownie/blob/master/brownie/test/output.py#L62

### Dependencies

#345
#347

**Comment by fubuloubu** [comment]
depends on #700

**Comment by fubuloubu** [comment]
ipfs://bafybeihapxqz43vadpqicxulwihrj6pqnvrxavf7hruk6xk45es57ds3hi/forge/gas-reports.html

**Comment by unparalleled-js** [comment]
I am guessing we want this on the receipt?

```python
receipt.show_gas_report()
```

This ticket could use some more acceptance criteria

**Comment by unparalleled-js** [comment]
> ipfs://bafybeihapxqz43vadpqicxulwihrj6pqnvrxavf7hruk6xk45es57ds3hi/forge/gas-reports.html

Ah interesting. Do we want something similar here?

```yaml
test:
    gas_reports: [MyContract]
```

```bash
ape test --gas-reports
```

**Comment by unparalleled-js** [comment]
> ipfs://bafybeihapxqz43vadpqicxulwihrj6pqnvrxavf7hruk6xk45es57ds3hi/forge/gas-reports.html

Does this actually require tracing? This table looks like it tracks the calls and `gas_used` from the receipts and calculates some stats on them.

**Comment by fubuloubu** [comment]
> > ipfs://bafybeihapxqz43vadpqicxulwihrj6pqnvrxavf7hruk6xk45es57ds3hi/forge/gas-reports.html
> 
> Does this actually require tracing? This table looks like it tracks the calls and `gas_used` from the receipts and calculates some stats on them.

What you want is all internal and external calls that were made, and their relative gas usage

**Comment by unparalleled-js** [comment]
Make progress here but haven't gotten to the hard part yet I don't think.
