### ISSUE TITLE
Testing: Set-Code

### ISSUE THREAD

**Issue by NotPeopling2day** [ApeWorX/ape#358]
### Overview

Support development RPC method for `set-code`
This is useful for setting the code of a smart contract for testing purposes.

### Specification

In `ProviderAPI`, add method:

```python
@raises_not_implemented
def set_code(address, AddressType, code: bytes):
    """
    Change the code of a smart contract, for development purposes.
    Test providers implement this method when they support it.
    """
```

Then, in `ape-hardhat`, we can support it be calling the RPC https://hardhat.org/hardhat-network/docs/reference#hardhat_setcode

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by fubuloubu** [comment]
@antazoey don't we have this?

**Comment by antazoey** [comment]
we have this
