### ISSUE TITLE
General: User scripts to work w/o `main` or `cli` methods

### ISSUE THREAD

**Issue by NotPeopling2day** [ApeWorX/ape#369]
### Overview

Update to make user scripts work whether or not they include `main` or `cli` methods in their scripts

### Specification

https://github.com/ApeWorX/ape/blob/29c8840d6dc02d7c37545e29b28269bf744842c9/src/ape_run/_cli.py#L15

**Comment by fubuloubu** [comment]
Check line 46. The script is actually fully running, but it shows an error for not having the right method
