### ISSUE TITLE
APE doesn't handle lists

### ISSUE THREAD

**Issue by SwapOperator** [ApeWorX/ape#376]
### Environment information

* `ape` and plugin versions: 0.1.0b1

```
$ ape --version

0.1.0b1

$ ape plugins list

Installed Plugins:
  etherscan     0.1.0a2
  hardhat     0.1.0a3
  alchemy     0.1.0a1
  vyper     0.1.0a8
  infura     0.1.0a4

```

* Python Version: Python 3.8.6
* OS: macOS

### What went wrong?

I have tested my contract func that works with lists and got error.
**Func Example:**
```
def foo(_tokens: address[25]) -> bool:
```
**Token list and testing func:**
```
tokens = [token1, token2, token3, token4, ZERO_ADDRESS, ZERO_ADDRESS,ZERO_ADDRESS...] 
assert deployer.foo(tokens, sender=owner)
```

**Error:**
```
eth_abi.exceptions.EncodingTypeError: Value `<Token 0x6418E...`  of type <class 'ape.contracts.base.ContractInstance'> cannot be encoded by AddressEncoder
```

Please include information like:

* what command you ran: **ape run deploy_test  --network ethereum:rinkeby:infura**
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
* full output of the error you received

### How can it be fixed?

Fill this in if you have ideas on how the bug could be fixed.

**Comment by fubuloubu** [comment]
@SwapOperator sorry it took so long, we fixed a host of other conversion issues now too!

**Comment by SwapOperator** [comment]
> @SwapOperator sorry it took so long, we fixed a host of other conversion issues now too!

Super cool! I should update my version :)

**Comment by fubuloubu** [comment]
> > @SwapOperator sorry it took so long, we fixed a host of other conversion issues now too!
> 
> Super cool! I should update my version :)

Newest version not released yet! You can try installing from `main` if you like though
```bash
$ pip install git+https://github.com/ApeWorX/ape.git@main
```
