### ISSUE TITLE
General: Global ape-config.yaml file

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#379]
### Overview

Allow user to edit and store a global `ape-config.yaml` file.  Project `ape-config.yaml` files obviously still take precedence.
This story must include documentation about said config file because otherwise users may not know about the existence of the `.ape` folder. 

### Specification

Configurations get applied in this order:

```
config defaults > global config > local config
```

### Dependencies

Maybe dependent the start of a `ape-config.yaml` guide.

**Comment by unparalleled-js** [comment]
The `ConfigManager` has a property called `_plugin_config`. This is where things get loaded in from the project config.

This is the point we can interject also loading the root project yaml.
