### ISSUE TITLE
Plugins: allow plugins add to add multiple plugins at the same time example: `ape plugins add etherscan infura`

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#383]
### Overview

Provide a simple overview of what you wish to see added. Please include:

* What you are trying to do
add multiple plugins at the same time
* Why Ape's current functionality is inadequate to address your goal
each plugin has to be added one at a time

### Specification

Describe the syntax and semantics of how you would like to see this feature implemented. The more detailed the better!
Would like to see it to be able to add multiple plugins at the same time for example:
`ape plugins add etherscan infura`

Remember, your feature is much more likely to be included if it does not involve any breaking changes.

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by fubuloubu** [comment]
I was just thinking about this today!

**Comment by fubuloubu** [comment]
cc @Ninjagod1251
