### ISSUE TITLE
Make Errors More Readable

### ISSUE THREAD

**Issue by SwapOperator** [ApeWorX/ape#384]
### Overview

Provide a simple overview of what you wish to see added. Please include:

* What you are trying to do: I tested a list of instructions(910 LOC). Then got an error : ```ERROR: (ArgumentsLengthError) The number of the given arguments do not match what is defined in the ABI.``` 
* Why Ape's current functionality is inadequate to address your goal: Testing redeployment(specially when you edit 2-3 functions and add new variables) contract can be a little difficult with long list of instructions.

### Specification

I suggest making the error messages more readable, for instance: tell user on which line the error occurred.   ```ERROR: (ArgumentsLengthError) The number of the given arguments do not match what is defined in the ABI. Line: 350, Function: contract.price(int(1e18), tokenF)...```

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by unparalleled-js** [comment]
Thanks for reporting, we will look into improving this!

If you do '--verbosity debug',
do you get any helpful info?

**Comment by SwapOperator** [comment]
> Thanks for reporting, we will look into improving this!
> 
> If you do '--verbosity debug', do you get any helpful info?

I have already fixed the assert errors in my code, so I did not run it this way, but I will know that with this command you can get more useful information, thanks you!

**Comment by SwapOperator** [comment]
> Thanks for reporting, we will look into improving this!
> 
> If you do '--verbosity debug', do you get any helpful info?

check this one too:

```
ERROR: (VyperInstallError) Unable to install Vyper version: 0.3.1.
```

this error is happening when some function in contract.vy for instance return hasn't enough data:
```
@external
@view
def foo() -> (uint256, uint256):
    a: uint256 = 1
    b: uint256 = 2
    return a
```

**Comment by fubuloubu** [comment]
@SwapOperator what version are you using of `ape-vyper` plugin? (Use `ape plugins list` to find out)

We resolved a bug in https://github.com/ApeWorX/ape-vyper/issues/26 that would display this type of error instead of the proper compiler error, but it should be fixed as of `0.1.0b1`

**Comment by SwapOperator** [comment]
> ape plugins list

Glad to hear you already know about this issue!
my version: vyper     0.1.0a8

**Comment by fubuloubu** [comment]
> > ape plugins list
> 
> Glad to hear you already know about this issue! my version: vyper 0.1.0a8

Oh yes! definitely upodate via `pip install -U ape-vyper` (we are working on a native way to update via `ape plugins`)

**Comment by unparalleled-js** [comment]
`ape plugins add vyper -U` should now work

**Comment by antazoey** [comment]
this got done, in several respecs.
1. line numbers are shown now, all py sources and vyper sources anyway
2. arguments error includes accepable number of args and the method signature
