### ISSUE TITLE
Plugin: StarkNet ecosystem and compiler support

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#401]
### Elevator pitch:
Add support for StarkWare's StarkNet L2 networks and Cairo compiler/transpiler

### Design approach:
https://github.com/Shard-Labs/starknet-devnet
https://github.com/OpenZeppelin/nile
https://github.com/starkware-libs/cairo-lang
https://github.com/software-mansion/starknet.py

### Task list:

* [ ] Tasks go here

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by Pet3ris** [comment]
I'm currently using `ape` in conjunction with `nile` so this would be great.

**Comment by fubuloubu** [comment]
> I'm currently using `ape` in conjunction with `nile` so this would be great.

:eyes: connect w/ me on telegram?
