### ISSUE TITLE
enhancement: allow configuring contracts/ directory 

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#409]
### Overview

Right now, a project directory can be configured. The `contracts/` directory is assumed to be `<project-dir>/contracts`.

We should allow configuring the contracts directory but defaulting to `<project-dir>/contracts`.

### Specification

* Add `contracts_folder` property to `ConfigManager`
* Replace all usages of a path ending in `contracts/` off the project, (`ProjectManager`, `CompilerManager`, etc.)

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by unparalleled-js** [comment]
Wondering if we should allow a list:

```yaml
contracts:
- src/contracts
- src/other-contracts-dir
- ~/global-contracts
```

**Comment by fubuloubu** [comment]
> Wondering if we should allow a list:
> 
> ```yaml
> contracts:
> - src/contracts
> - src/other-contracts-dir
> - ~/global-contracts
> ```

That's interesting. I haven't seen a project with more than one contracts directory though, although I suppose foundry repos typically use git submodules to link to ds-test and other dependencies
