### ISSUE TITLE
General: add functionality to convert datetime object to timestamp

### ISSUE THREAD

**Issue by johnson2427** [ApeWorX/ape#436]
### Overview

we currently can convert a string in "MM-DD-YYYY HH:MM:SS" format. Want to add functionality of taking a datetime object and converting to a timestamp

### Specification

```python
date_time = datetime.datetime.fromisoformat("2020-10-15 12:00:00")
new_date_time_obj = date_time.replace(tzinfo=timezone.utc)
return int(new_date_time_obj.timestamp())
```

### Dependencies

None

**Comment by fubuloubu** [comment]
You can add this to current timestamp converter via `Union[str, datetime]`

**Comment by fubuloubu** [comment]
Also make sure that the chain manager method accepts this

**Comment by fubuloubu** [comment]
timedelta might also be nice to add. I had thought about correcting the time for it, but that seems like it would lead to a lot of contextual errors. I think more directly just converting timedeltas (in string or `datetime.timedelta` object formats) to their integer equivalent in seconds:
```py
int(timedelta.total_seconds())
```

also parse `"1 weeks"` via:
```py
# "1 weeks"
# "1 weeks, 1 days"
# "1 weeks, 1 days, 1 seconds"
# Convert comma-separated string of `"{int} {kwarg}, ..."` to dict of `{"{kwarg}": "{int}", ...}`
int(timedelta(**timedelta_dict).total_seconds())
```

This might be tougher though.

**Comment by johnson2427** [comment]
Oh, I can delete DatetimeConverter then

**Comment by johnson2427** [comment]
I can add timedelta to TimestampConverter. I will make a new issue
