### ISSUE TITLE
Refactor: _Contract and ContractContainer

### ISSUE THREAD

**Issue by NotPeopling2day** [ApeWorX/ape#443]
### Overview

Provide a simple overview of what you wish to see added. Please include:

- Remove partial _Contract creation and simplify creation logic

### Specification

- Remove `partial()` in the `ape.__init__.py` around _Contract creation
- Rework `_Contract` and  get logic into `ContractContainer` class

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by unparalleled-js** [comment]
Outdated and Done
