### ISSUE TITLE
Testing: Make 'ape test' work nicely in GitHub action

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#452]
### Overview

See @fubuloubu for more info!

He was trying to copy this:
https://github.com/actions/hello-world-docker-action

Looks like we have an existing repo started here: https://github.com/ApeWorX/github-action

**Comment by fubuloubu** [comment]
Was trying to add this in github.com/ApeWorX/github-action

**Comment by sabotagebeats** [comment]
@fubuloubu I think this has been resolved?

**Comment by unparalleled-js** [comment]
> @fubuloubu I think this has been resolved?

Go ahead and close! You probably know best what is left on this.
