### ISSUE TITLE
Bug: Unable to use AddressType for 'sender'

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#462]
### Environment information

Latest 'ape'

### What went wrong?

Using an `AddressType` for the `sender=` kwarg when making a transaction causes an error:

```
...
  File "****/ape/contracts/base.py", line 177, in __call__
    return sender.call(txn)
AttributeError: 'str' object has no attribute 'call'
```

### How can it be fixed?

Handle both types in the contract base when encoding sender

**Comment by fubuloubu** [comment]
So this is because `sender` must also go and sign/execute the transaction as well (currently)

Perhaps should be rethought

**Comment by unparalleled-js** [comment]
Ah okay. Maybe we can attempt to load account if we recognize it?
