### ISSUE TITLE
bug: Allow raising Abort without providing a message

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#465]
### Environment information

0.1.0b4
macOS
python 3.9.7

### What went wrong?

Right now, if you do:

```python
raise Abort()
```

you get error:

```
TypeError: __init__() missing 1 required positional argument: 'message'
```

It would be nice if it defaulted to something generic so I can use in scripts without having to care. Like:

```
ERROR: Operation aborted.
```

### How can it be fixed?

Default argument

**Comment by fubuloubu** [comment]
I think it would be nice that it contains some sort of info of what triggers the aborts, like file and line no

**Comment by unparalleled-js** [comment]
> I think it would be nice that it contains some sort of info of what triggers the aborts, like file and line no

Since the exception is not on the stack at this point, the only way I know how to do that is to inspect the call frames
