### ISSUE TITLE
Cache `chain_id` requests

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#483]
It should be possible for the `ProviderAPI.chain_id` method to just be a `cached_property`, because this value should *never* change for a specific provider once you query 1 time.

**Comment by unparalleled-js** [comment]
I think we are over-using the `BUG` label.
BUGS means things are not working.
It would be an optimization / enhacement to cache this rather than a bug.
I will address it either way, but just something to think about.

**Comment by unparalleled-js** [comment]
To do this correctly in `web3`, we need to use their caching middleware...

Reason: The request happens behind-the-scenes sometimes. I notice the logs still appear with using `cached_property`. We are caching it on our side but it's not completely cached in the right spot.

**Comment by unparalleled-js** [comment]
Even when using the middlware, the request logs for Chain ID still appear more than once.
I am doing all the caching I can do and confident that it is being cached, yet cannot get the multiple logs to go away. Maybe not a big deal but difficult to tell why.

**Comment by unparalleled-js** [comment]
The log is from the `web3` library logger, no the `ape` logger

**Comment by unparalleled-js** [comment]
One weird thing from using `@cached_property`:

```python
In [1]: provider
Out[1]: <test chain_id=61>

In [2]: provider.disconnect()

In [3]: provider.chain_id
Out[3]: 61
```

The provider is not connected to a chain ID, so it is misleading that it still has a chain ID.

I am looking into managing the cached chain ID ourselves and getting rid of it on `disconnect()`.

**Comment by unparalleled-js** [comment]
Also, one of the requests is currently unavoidable and I am trying to figure out why that is. I have a lead here: https://github.com/ethereum/web3.py/pull/2450/files but the solution may not be correct.
