### ISSUE TITLE
Testing: Impersonate Account API

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#488]
### Overview

* Currently, mainnet-fork capabilities are limited by not having a way to unlock accounts. We should add a method to the `TestProviderAPI` for unlocking accounts.

I am trying to make my tests have accounts that start off with ERC20s.

### Specification

```python
class TestProviderAPI:
    def impersonate_account(self, address):
        raise NotImplementedError(...)  # Override if this feature is supported
```

### Dependencies

[Include links to any open issues that must be resolved before this feature can be implemented.](https://hardhat.org/hardhat-network/reference/#hardhat-impersonateaccount)

Will also require updating Hardhat plugin

**Comment by fubuloubu** [comment]
What do you think of this?
```py
def impersonate_account(address: Union[str, AddressType]) -> AddressAPI:
    """
    Returns an `AddressAPI` subclass (only for testing purposes) that the `TestProviderAPI`
    will allow to make arbitrary transactions
    """
```

I'm not sure if `stop_impersonating_account` is even needed, the variable should just go out of scope

Also curious if this should be under the `ChainManager` for the user-facing portion of it (since `chain` ends up in our fixtures, but `provider` does not)

**Comment by unparalleled-js** [comment]
Yes, I think that all makes sense and works out nicely.

So would this be a usage example?

```python
@pytest.fixture
def my_account(accounts, chain):
    dev_account = accounts[0]
    impersonated_account = chain.impersonate_account("0xwhatever")
    impersonated_account.transfer(dev_account, "100 DAI")
```

**Comment by unparalleled-js** [comment]
How do all the cool kids fund their test accounts with DAI?
Is there a way to do this by impersonating the contract itself (I can't really think of how)?
Or is there some known "faucet" accounts that are reliable to use in tests?

**Comment by fubuloubu** [comment]
> How do all the cool kids fund their test accounts with DAI?

When I did it, I liked to impersonate an account I always knew would have lots of it. Or, even better, one with minting authority.

> Is there a way to do this by impersonating the contract itself (I can't really think of how)?

You should be able to impersonate any contract the same as an account.

However, you can't make arbitrary self-calls like that, you'd need the ability to modify storage directly (which is also something I want to add the ability to do e.g. `token.storage["balanceOf"][acct] += int(1e20)`)

**Comment by unparalleled-js** [comment]
Is it possible to make this return `Union[ContractInstance, ImpersonatedAccount`] where `ImpersonatedAccount` is an `AccountAPI` that does not care about signing. Reasons:

1. Right now, I am not sure how to get the `ContractType` from an impersonated contract (unless I use etherscan or something).

2. I can't use the `transfer()` method unless it is the `AccountAPI` (not `AddressAPI`). I believe impersonated accounts just simply don't requiring signing? So we can send raw transactions without needing sign or can put whatever there?

I am really not sure if what I am trying to do is possible! I just want some DAIIIIIII. I was going to impersonate vitalik and fund my test accounts that way.

**Comment by fubuloubu** [comment]
> Is it possible to make this return `Union[ContractInstance, ImpersonatedAccount`] where `ImpersonatedAccount` is an `AccountAPI` that does not care about signing.

I don't think we'd need that to return `ContractInstance` at all, you would just create a contract variable at that address instead.

> 1. Right now, I am not sure how to get the `ContractType` from an impersonated contract (unless I use etherscan or something).

This wouldn't be the use case for it, you should load a contract type at that address instead. `ImpersonatedAccount` is just there to let you send assets from that account, or make other types of calls for testing purposes.

> 2. I can't use the `transfer()` method unless it is the `AccountAPI` (not `AddressAPI`). I believe impersonated accounts just simply don't requiring signing? So we can send raw transactions without needing sign or can put whatever there?

Yep! That's how it would work!

> I am really not sure if what I am trying to do is possible! I just want some DAIIIIIII. I was going to impersonate vitalik and fund my test accounts that way.

Honestly, the easiest way is probably to mint yourself some Dai by finding a caller that is `auth`'d:
![image](https://user-images.githubusercontent.com/3859395/153538986-b220051b-a068-49a6-9e11-d29ec38e8eb7.png)

I think the `Vat` contract is one such auth'd contract: 0x35D1b3F3D7966A1DFe207aa4514C12a259A0492B. So, you would impersonate `Vat` and mint yourself however much Dai you wanted.

Note: I found this by looking for ERC20 Transfer events coming from 0x0 account, and then got a transaction trace of the vent to see what address triggered the transaction, something eventually our Query system can handle?

**Comment by unparalleled-js** [comment]
### Overview

* Currently, mainnet-fork capabilities are limited by not having a way to unlock accounts. We should add a method to the `TestProviderAPI` for unlocking accounts.

I am trying to make my tests have accounts that start off with ERC20s.

### Specification

```python
def impersonate_account(address):
    ....
```

Also have config-driven impersonated accounts, something like :

```yaml
test:
    unlocked_accounts:
      - name: DaiHolder
         address: 0x12..45
```

Also, change the `accounts` test fixture to include key-accessible unlocked accounts:

```python
def test_accounts(accounts):
    acct = accounts[0]
    dai_acct = accounts["DaiHolder"] 
```

### Dependencies

[Include links to any open issues that must be resolved before this feature can be implemented.](https://hardhat.org/hardhat-network/reference/#hardhat-impersonateaccount)

Will also require updating Hardhat plugin

**Comment by fubuloubu** [comment]
> Also have config-driven impersonated accounts, something like :
> 
> ```yaml
> test:
>     unlocked_accounts:
>       - name: DaiHolder
>          address: 0x12..45
> ```
> 
> Also, change the `accounts` test fixture to include key-accessible unlocked accounts:
> 
> ```python
> def test_accounts(accounts):
>     acct = accounts[0]
>     dai_acct = accounts["DaiHolder"] 
> ```

I think this type of feature fits better with #306
