### ISSUE TITLE
Ape hijacks pytest, not allowing pytest to be used independently or pytest-xdit to be used

### ISSUE THREAD

**Issue by Pet3ris** [ApeWorX/ape#498]
### Environment information

Ape version was beta 0.1.3 and this issue surfaced before plug-in installation.

* Python Version: 3.8
* OS: macOS

I'm using poetry with ape as a dev dependency.

### What went wrong?

When I run poetry run pytest ape reports "no provider name test"
After that I switched to running `poetry run ape test`, which worked fine as a replacement.
However, recently started using `pytest-xdist` for test parallelization and when running `poetry run ape test -n auto`, the same error occurs. Had to uninstall ape to be able to test directly with pytest.

### How can it be fixed?

Fill this in if you have ideas on how the bug could be fixed.

**Comment by unparalleled-js** [comment]
Most pytest plugins are installed along side pytest. Ape, however, does hijack it. The work around is that you have to disable the ape-test plugin when running pytest in other projects (or use separate environments).

To disable the `ape-test` plugin in `pytest`, include the following command line option:  `-p no:ape_test`.
You can also use this in your `pyproject.toml` file. This is actually how we run the normal `ape` tests: https://github.com/ApeWorX/ape/blob/main/pyproject.toml#L21

- [ ] I think, for now anyway, we should more explicitly document this somewhere


We can also brainstorm alternatives.

**Comment by fubuloubu** [comment]
> We can also brainstorm alternatives.

Wonder if we can dynamically inject the plugin only when `ape test` is called? Although I do like it being an alias for `pytest`

**Comment by unparalleled-js** [comment]
> > We can also brainstorm alternatives.
> 
> Wonder if we can dynamically inject the plugin only when `ape test` is called? Although I do like it being an alias for `pytest`

I also want to look more into why it fails.. Maybe if we can detect that it is not an ApeProject, we can avoid doing any plugin stuff.

**Comment by fubuloubu** [comment]
> > > We can also brainstorm alternatives.
> > 
> > 
> > Wonder if we can dynamically inject the plugin only when `ape test` is called? Although I do like it being an alias for `pytest`
> 
> I also want to look more into why it fails.. Maybe if we can detect that it is not an ApeProject, we can avoid doing any plugin stuff.

Hmm, maybe have `-p no:ape_test` by default w/ pytest registration, and then remove it in `ape_test/_cli.py`

**Comment by Pet3ris** [comment]
Curious - why couldn't ape exist as a library/pytest plug-in as far as testing is concerned?

**Comment by Pet3ris** [comment]
Maybe to add more color on the consequences of using global package state from a python module: I used a conda environment to create a poetry env for ape development. After uninstalling ape to be able to use pytest parallelization (the issue above), I created another poetry env based on this conda environment. However, this env still has `ape_test` and `ape` and I cannot uninstall them. Moreover it seems to have modified some internal `pytest` registry so I'm not able to test. I had to delete the conda env altogether :(.

**Comment by unparalleled-js** [comment]
> Curious - why couldn't ape exist as a library/pytest plug-in as far as testing is concerned?

Yes that is exactly what `ape_test` is!

The issue is related to `ape_test` trying to load `ape` plugins when you invoke `pytest` alone in a non-ape project, and some race conditions happen causing the thing to not work.

**Comment by unparalleled-js** [comment]
To further clarify, the bug is that when you do `ape test`, things load up in the right order but when you just do `pytest`, things do not

**Comment by unparalleled-js** [comment]
> Maybe to add more color on the consequences of using global package state from a python module: I used a conda environment to create a poetry env for ape development. After uninstalling ape to be able to use pytest parallelization (the issue above), I created another poetry env based on this conda environment. However, this env still has `ape_test` and `ape` and I cannot uninstall them. Moreover it seems to have modified some internal `pytest` registry so I'm not able to test. I had to delete the conda env altogether :(.

I am not exactly sure about some of this! What do you mean by "jt 

> Maybe to add more color on the consequences of using global package state from a python module: I used a conda environment to create a poetry env for ape development. After uninstalling ape to be able to use pytest parallelization (the issue above), I created another poetry env based on this conda environment. However, this env still has `ape_test` and `ape` and I cannot uninstall them. Moreover it seems to have modified some internal `pytest` registry so I'm not able to test. I had to delete the conda env altogether :(.

I don't understand why ape is still installed in a new environment; that must be related to conda or something. For now, to turn of f the ape-test pytest plugin, you either have to use ape in separate environment or use the `-p no:ap_test` option when invoking pytest.

**Comment by unparalleled-js** [comment]
@Pet3ris I am curious of the PR above works for you! It seems to do the following for me:

1. I can do run `pytest` and `ape test` interchangeably for ape projects
2. When I run `pytest` in a non-ape project, things still "work".  (the plugin still gets registered but it does not really matter)

**Comment by Pet3ris** [comment]
Thanks @unparalleled-js  - I did this on a non-ape repo:

```python
poetry add --dev git+https://github.com/unparalleled-js/ape.git#fix/test-race-cond
poetry run pytest
```

Can confirm it works now, which didn't work on main.
