### ISSUE TITLE
Plugin Registration for providers uses plugin name

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#500]
### What went wrong?
So when registering a provider for a given network, the plugin name is used:
https://github.com/ApeWorX/ape/blob/26ff5a411be1611bd2c698deb5e9010cd42f7f25/src/ape/api/networks.py#L455-L468

Typically this is desirable (e.g. `ape-alchemy`, etc.) However, when you are re-using another provider in a different plugin (e.g. `geth` provider in `ape-fantom`) this comes back to bite us (e.g. `fantom:testnet:fantom`)

This needs to be re-thought

**Comment by unparalleled-js** [comment]
Maybe we can just allow the one and to have the config get set dynamically on use at later date, since this is just a partial at this point anyway?

**Comment by fubuloubu** [comment]
idea: use the module name that the object defined in as the plugin name, instead of where it ends up being registered

**Comment by fubuloubu** [comment]
A few options:
1. Get `plugin_name` from module that `provider_class` was defined in
2. Move registration statements to ape core, conditional on `fantom` being installed
3. Allow provider to set it's own name

**Comment by unparalleled-js** [comment]
Could we do something like this?

```python
from ape_geth import register_geth_provider

register_geth_provider("fantom", NETWORKS)
```
