### ISSUE TITLE
Ape Test Scope Management for Fixtures

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#502]
### Elevator pitch:
Allow the use of normal Pytest fixture scoping such as "session", "module", and "function".

### Value:
In order to speed up testing, it is often very useful to "cache" heavier fixture setups like deployments by setting a scope for them, so that pytest does less setup between tests.

### Dependencies:
Ape providers have snapshot features, but they need to be used more heavily inside of a test. This also must function well with xdist, or other paralell test processors (which should be smoother since we made the decision to have independent providers per test runner)

### Design approach:
Make provider snapshots at particular scopes e.g. collect all "session" scopes and snapshot, then all "module" scopes and snapshot (and revert when module complete), and finally snapshot prior to each test (and revert afterwards).

It might also help to explore more about how we might enable certain tests to use the final state from other tests, maybe via a decorator e.g.

```py
def test_do_a():
    ...

@ape.use_snapshot("test_do_a")
def test_do_b():
    ...  # Depends on state from previous test
```

### Task list:

* [ ] Tasks go here

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by unparalleled-js** [comment]
I think this ticket either needs to be closed or re-written, as of https://github.com/ApeWorX/ape/pull/654/files

**Comment by unparalleled-js** [comment]
was completed here https://github.com/ApeWorX/ape/pull/654
