### ISSUE TITLE
Bug: Sphinx-warnings for re-importables

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#521]
### Overview

One of the on-going warnings / issues we have with sphinx docs is the cases when we import stuff from other python modules to be re-importable from or module, such as stuff in the `ape.types` namespace and some things in the `ape.utils` namespace

I have been poking around a Starknet python client library and noticed this gem: https://github.com/software-mansion/starknet.py/blob/development/starknet_py/utils/docs.py#L10

^ Looks like they also have had this same issues and have created a method that fixes it.

We should try to borrow this fix!

### Specification

```python
def as_our_module(cls: T) -> T:
    """
    We create alias for some function from starkware, but sphinx show original module path. This makes docs harder to
    follow.

    :param cls: class
    :return: Same class, just with changed module if docs are being created.
    """
    if not generating_docs:
        return cls

    frm = inspect.stack()[1]
    mod = inspect.getmodule(frm[0])
    cls.__module__ = mod.__name__
    return cls

```
(copied from `starknet.py` library, link is above)

And using it would be like this:

```python
try:
    from functools import cached_property as _cp  # type: ignore
except ImportError:
    from backports.cached_property import cached_property as _cp  # type: ignore

cached_property = as_our_module(_cp)
```

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by fubuloubu** [comment]
Lol that's pretty wild
