### ISSUE TITLE
Managing Deployments

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#530]
### Overview
Allow specifying final deployments to networks, as well as referencing them.

Currently, we have limited deployment management features from the config file of a project, as well as the project manifests, but for the currently active project we need a way to track and reference deployments to create structured deployment processes (e.g. B depends on A)

This is a test of Linear app integration

### Specification
```py
from ape import project  # NOTE: Our local project


# Do deployment of `my_contract = account.deploy(project.MyContract)`
project.track_deployment(my_contract)  # NOTE: Appends to list of deployments for type
# Adds tracking for deployment of `MyContract` type on `networks.active_network`
# NOTE: This only works for our local project (deployments are immutable otherwise)

...

# Reference previous deployment
# NOTE: This works for any project, not just our local one
my_contract = project.deployments(project.MyContract)[-1]
```

Also add a way to "untrack" a deployment:
```py
project.drop_deployment(my_contract)
# NOTE: This only works for our local project (deployments are immutable otherwise)
```

### Dependencies
EthPM `dependencies` field

**Comment by unparalleled-js** [comment]
Yes!!!

**Comment by unparalleled-js** [comment]
@NotPeopling2day said I can take this one

**Comment by unparalleled-js** [comment]
Status update!

First, was confused about some things in ethpm-types so I spent time researching and updating the documentation there: 
https://github.com/ApeWorX/ethpm-types/pull/40

After I understood more about the schema for deployments, I realized I would like to local deployments cache to be more work-able with me, so I had to do this work today: https://github.com/ApeWorX/ape/pull/940

So we are making good practice but this was a little more complex than I originally thought! But I assume it still won't take too much more effort.

**Comment by fubuloubu** [comment]
@unparalleled-js as a side note: always keep in mind we can make changes to EIP-2678, we've made a few already even (mostly additions). If any substantive changes need to happen that depart from EIP-2678, we can look at publishing it as a new EIP.
