### ISSUE TITLE
Address loader misconfigured

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#541]
### Environment information

* `ape` and plugin versions:

```
$ ape --version
0.1.0b6+...

$ ape plugins list
# Not important
```

* Python Version: 3.9.9
* OS: linux

### What went wrong?
```py
In [5]: acct = Contract("0x...")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [5], in <module>
----> 1 acct = Contract("0x...")

File ape/contracts/base.py:491, in _Contract(address, networks, conversion_manager, contract_type)
    488 else:
    489     # We don't have a contract type from any source, provide raw address instead
    490     logger.warning(f"No contract type found for {address}")
--> 491     return Address(  # type: ignore
    492         _address=converted_address,
    493         _provider=provider,
    494     )

TypeError: Address() takes no arguments
```

### How can it be fixed?
Seems like something changed in the pydantic refactor

**Comment by unparalleled-js** [comment]
Looks like the reason for this is that `Address` / `BaseAddress` not pydantic models but we are using them as so via this init and the lack of `__init__` method

**Comment by unparalleled-js** [comment]
Also seems like the contract type is not fetchable from the network cache

**Comment by fubuloubu** [comment]
> Also seems like the contract type is not fetchable from the network cache
> 
> Edit: I guess that is not implemented fully yet ?

Yes, that is an outstanding TODO, to add a locally-kept DB that tracks `ContractTypes` by some combination of `.codehash` and `address` (and introspecting their assembly to see if they match some sort of proxy type and/or re-init `CREATE2` scenario)
