### ISSUE TITLE
Add `ape_assert` utility method

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#554]
### Overview

Inspired from this method: https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starkware_utils/error_handling.py#L160-L166

This is better than the normal `assert` statement because it is more prod-friendly.
IDK this is just something I liked and wanted to track! It would be a fun one to implement use, and share.

### Specification

```
def ape_assert(expr: bool, fail_message: str):
    """
    Verifies that the given expression is ``True``.
    Inspired from https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starkware_utils/error_handling.py#L16

    Raises:
        :class:`~ape.exceptions.ApeAssertionError`: When the expression evaluates to ``False``.
    """
    if not expr:
        raise ApeAssertionError(fail_message)
```

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by fubuloubu** [comment]
This for testing purposes, or for use inside core/plugins?

**Comment by unparalleled-js** [comment]
It is for use anywhere. It is just an idea for making code cleaner, like anywhere where we are raising `AssertionError` right now

**Comment by antazoey** [comment]
closing as nevermind
