### ISSUE TITLE
Plugins: Use `click-plugins`

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#56]
https://pypi.org/project/click-plugins/

Note the ability to pass-through the network and account options!

**Comment by unparalleled-js** [comment]
Another v1 SPIKE I think

**Comment by antazoey** [comment]
The package is no longer maintained (so it seems!) and it doesn't work on Python 3.12.
Also, we likely will go a different direction with something like typer where this won't be needed.
Closing as WON'T DO.

https://github.com/click-contrib/click-plugins/issues/37
