### ISSUE TITLE
Error initializing Contract

### ISSUE THREAD

**Issue by mikeshultz** [ApeWorX/ape#564]
Pretty sure I'm both using this wrong and it's a bug.  From an Ape console:

    In [6]: weth = Contract(address='0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2')
    WARNING: No contract type found for 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    Input In [6], in <cell line: 1>()
    ----> 1 weth = Contract(address='0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2')

    File ~/dev/ape/src/ape/contracts/base.py:491, in _Contract(address, networks, conversion_manager, contract_type)
        488 else:
        489     # We don't have a contract type from any source, provide raw address instead
        490     logger.warning(f"No contract type found for {address}")
    --> 491     return Address(  # type: ignore
        492         _address=converted_address,
        493         _provider=provider,
        494     )

    TypeError: Address() takes no arguments

Running Ape from the `main` branch.

**Comment by fubuloubu** [comment]
`Contract` is a partial, so you're passing the kwarg to that caller, where the name is `_address` instead

However, that code looks old, see if you can update to v0.1.0?

**Comment by mikeshultz** [comment]
Thanks, yeah, my fork was out of date.  Closing
