### ISSUE TITLE
Plugins: Add Chainstack provider

### ISSUE THREAD

**Issue by NotPeopling2day** [ApeWorX/ape#567]
### Overview

Make a chainstack plugin

### Specification

Uses the structure @unparalleled-js created during EthDenver and functions similarly to ape-infura/ape-fantom

https://docs.chainstack.com/blockchains/ethereum
https://github.com/ApeWorX/ape-infura
https://github.com/ApeWorX/ape-fantom
https://github.com/unparalleled-js/ape-ethdenver

https://docs.google.com/document/d/13g3jXfswtjgVYs8wL4b9NxuEZv9fVED0ioRqaLlcyM4/edit

**Comment by antazoey** [comment]
this got done
