### ISSUE TITLE
Create a logger object and add `click-logging`

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#57]
https://pypi.org/project/click-logging/

**Comment by lost-theory** [comment]
+1 on a logging setup in general. I could use it with the `ape-hardhat` work (logging network calls, subprocess calls, retries, etc.).

**Comment by lost-theory** [comment]
Also for dumping captured stdout/stderr from the hardhat process, like error messages.

**Comment by fubuloubu** [comment]
@lost-theory let's talk about this tomorrow

**Comment by lost-theory** [comment]
I started on this last week.
