### ISSUE TITLE
Support getting events form ReceiptAPI + getting all events from a ContractInstance

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#571]
### Overview
In general, it's nice to see the set of events emitted by a transaction

### Specification
Something maybe like

```py
tx = my_contract.doSomething(...)
assert len(tx.events) > 0  # tx.events is list-like
assert tx.events.MyEvent[0].caller == ...  # be able to fetch items from the event log
# OR
assert tx.MyEvent[0].caller == ...  # Not sure if `__getattr__` here would be dangerous
```

### Dependencies
Might require some changes to event decoding logic

**Comment by fubuloubu** [comment]
```py
my_contract.MyEvent.from_receipt(tx)[0].caller  # All `MyEvent` events emitted during `tx`
my_contract.MyEvent[-1].caller                  # All `MyEvent` events emitted by `my_contract`
```

**Comment by unparalleled-js** [comment]
What exactly is the return type? It would be a new class, like `ContractEventInstance` ?  The type of `MyEvent` is `ContractEvent` but it kind of seems more like `ContractEventType` ?

**Comment by unparalleled-js** [comment]
I am also wondering if we want to provider a way that iterates over all of them? I know that may be a lot of events, but maybe an `__iter__` that does that? Otherwise, you can do that via `filter()` without kwargs I think, but that seems odd

**Comment by fubuloubu** [comment]
> Edit: Ok, I have found the `ContractLog` class and the `decode_event` method on the `EcosystemAPI`. Seems like this is it.

Yes this is correct

**Comment by fubuloubu** [comment]
> I am also wondering if we want to provide a way that iterates over all of them? I know that may be a lot of events, but maybe an `__iter__` that does that? Otherwise, you can do that via `filter()` without kwargs I think, but that seems odd

Yeah, I mean this fits with `__getitem__` method we were talking about, `__iter__` would be the same. Might require something intermediate to get to work like this correctly

More concretely:

```py
class ContractEvent:
    ...

    def __iter__(self) -> Iterator[ContractLog]:
        ...

    def __getitem__(self, index) -> ContractLog:
        ...

    def from_receipt(self, receipt) -> List[ContractLog]:
        ...

    def filter(self, **filter_args) -> Iterator[ContractLog]:
        ...

    def query(self, *fields, **filter_args) -> pd.Dataframe:
        ...
```

p.s. you can refactor the module structure under `src/ape/contracts/*` if you'd like

**Comment by fubuloubu** [comment]
question: do we want the ability to poll new events?
