### ISSUE TITLE
Interactive mode disconnects from provider when running scripts

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#581]
### Environment information

ape v0.1.0
python 3.7.12
macOS

### What went wrong?

When using `-i` with `ape run`, it disconnects from the network before opening the console. Note: this does not happen in EthTester but it happens in all the other networks.

(As an aside, the `-i` is stuck on the left side of the script name. That maybe fixed at the same time as this, depending on what the solution entails)

### How can it be fixed?

I think we need to add a more clever way to manage the network in scripts.
I don't know yet!

**Comment by unparalleled-js** [comment]
Another scripts bug:  ApeExceptions seem to not show up. The script ends without any output

**Comment by unparalleled-js** [comment]
Seems like in some cases, as reported in #645, the interactive shell does not open at all

**Comment by fubuloubu** [comment]
@NotPeopling2day follow up if this one is solved

**Comment by sabotagebeats** [comment]
@fubuloubu I was unable to replicate this, however I also wasn't able to get `-I` to drop into interactive mode, but I think that might be a separate bug.

**Comment by unparalleled-js** [comment]
I am not able to reproduce this anymore as of 0.6., but one thing to be aware of: if your `ape_console_extras.py` errors, it may crash `-I` and your provider and you may still get this error, that was happening to me.

**Comment by antazoey** [comment]
OK so this is still a problem.
What happens - it is only a problem if you don't have a reference to the provider in your script.
This was also reported by users!

**Comment by z80dev** [comment]
![image](https://github.com/ApeWorX/ape/assets/83730246/b2dcc67a-dfe3-40e1-8513-b05839698794)
