### ISSUE TITLE
chain.ChainManager.pending_timestamp returns a datetime object, but expects and int

### ISSUE THREAD

**Issue by johnson2427** [ApeWorX/ape#586]
### Environment information
```
$ ape --version
0.1.1.dev4+g0b984659a
```
* Python Version: 3.8.10
* OS: Linux

### What went wrong?

Please include information like:

Ran the pre-commit in the cli, mypy failed and I received this error:
```
src/ape/managers/chain.py:428: error: Incompatible return value type (got "datetime", expected "int")
Found 1 error in 1 file (checked 123 source files)
```

### How can it be fixed?
We can return int(self.prov....)

**Comment by unparalleled-js** [comment]
@johnson2427 Which provider are you using? This does not seem to be the case in `EthTester`.

**Comment by unparalleled-js** [comment]
I just tried Hardhat and mainnet-fork on Hardhat and they both return `int` as well.

**Comment by unparalleled-js** [comment]
Talked to @johnson2427 , this got resolved
