### ISSUE TITLE
Leverage query manager to complete historical block range queries

### ISSUE THREAD

**Issue by johnson2427** [ApeWorX/ape#595]
### Elevator pitch:
The query provider system will intelligently find the fastest way to provide data for historical queries, often much faster than querying a provider directly. 

### Value:
Allows for querying of block data and fetching it much faster when alternative data sources are connected vs. calling the provider directly. 

### Dependencies:
None

### Design approach:
Pull the logic from the `ChainManager.blocks.range` function and replace with calls to `QueryManager` instead. Move the previous logic to `DefaultQueryProvider` so that by default it will query the provider if no faster method of providing this data is found. 

### Task list:

* [ ] Remove range functionality from chain_manager
* [ ] Put that functionality into query_manager (confirm this)

### Estimated completion date:
March 22nd, 2022

### Design review:

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
Approved! (with edits)
