### ISSUE TITLE
Ad-hoc network support

### ISSUE THREAD

**Issue by mikeshultz** [ApeWorX/ape#598]
### Overview

I often have a need to connect to random JSON-RPC nodes.  Either for testing (trying out a new provider like BSN with a test key), or to connect to ad-hoc private networks.  For instance, for a project I work with, we stand up individual hardhat nodes for every PR to act as a private network.  The URLs are derived by the branch name so change every time. 

#### What you are trying to do

I would love to simply get a console on a random endpoint like this:

    ape console http://hardhat.sub.domain.dev

And instantly be able to poke and prod at the network as needed.

#### Why Ape's current functionality is inadequate to address your goal

Right now, I would need to alter a project level config (shout out to global config #379) to add the network, then `ape console --network ethereum:mainnet:test123`, which takes time and clutters my config with useless configuration.

### Specification

I'm not really sure and that's why I'm here.  I'd be happy to work on it but since I'm still familiarizing myself with ape, I'd like to have a conversation on this part before I dig too far into it.

I'm a little concerned that this request spans responsibilities of multiple plugins (e.g. `ape_console` and `ape_geth`) and internal config maybe so I'm not sure how to make all that play nicely.

### Dependencies

None that I know of.

**Comment by fubuloubu** [comment]
I the past, I've thought about having a way to specify provider settings via command line, so here you would do something like:

```py
ape console --network ::geth --provider-url http://hardhat.sub.domain.dev
```

However, a more general question, why do you need to load the Hardhat node separately? Could you leverage the automatic launch that `ape-hardhat` does?

**Comment by mikeshultz** [comment]
> I the past, I've thought about having a way to specify provider settings via command line, so here you would do something like:
> 
> ```python
> ape console --network ::geth --provider-url http://hardhat.sub.domain.dev
> ```

Something like that would work for me.  I could add a bash alias to simplify it pretty easily.

> However, a more general question, why do you need to load the Hardhat node separately? Could you leverage the automatic launch that `ape-hardhat` does?

The stack in question is a complete infrastructure for a hybrid dapp, including a backend API, private network, and other relevant services that more or less mirrors production infra.  There's some  local dev env tooling as well, though that's currently using "plain" hardhat because it's a JS shop.  I just prefer a Python console to interact with the remote running node when I need to because Python > JS.  

Brownie and hardhat also have the same hurdles.  9 times out of 10 I end up using a plain Python REPL in a venv that has web3.py (and the rest of the Python ecosystem) installed and just init my own Web3 instance which is repetitive and annoying.

For my other examples, Ape wouldn't be used as a contract project app, but as a toolkit to interact with other nodes, networks, etc.

**Comment by fubuloubu** [comment]
> For my other examples, Ape wouldn't be used as a contract project app, but as a toolkit to interact with other nodes, networks, etc.

Sounds like it might be solved by specifying a port in the config, which disables the Hardhat auto-selection algorithm, or using geth plugin config via full URI

**Comment by mikeshultz** [comment]
> > For my other examples, Ape wouldn't be used as a contract project app, but as a toolkit to interact with other nodes, networks, etc.
> 
> Sounds like it might be solved by specifying a port in the config, which disables the Hardhat auto-selection algorithm, or using geth plugin config via full URI

Not sure I'm following.  How does specifying a hardhat listening port help with connections to remote machines?  But sure, I can use the configuration file for the geth plugin but that's kind of what I was trying to avoid, because they were temporary connections that I wouldn't be using again.  That's essentially the summary of this whole use case: "connecting a console to remote ephemeral JSON-RPC endpoints."

**Comment by mikeshultz** [comment]
Mostly notes for myself as I have a terrible memory, but feedback/clarifications welcome.  I was digging around trying to understand how things work currently and it looks like at one point direct URIs were supported!

`NetworkManager` appears to have supported network options like `ecosystem:network:uri` like `ethereum:mainnet:https://eth-mainnet.alchemyapi...`.

https://github.com/ApeWorX/ape/blob/731b556b88f3830c5a94511bc3ab32c86bd972a8/src/ape/managers/networks.py#L306-L308

This would pass on a `provider_name` that's actually a URI, to `NetworkAPI.get_provider()` which parses the URI and sets it on `provider_settings`:

https://github.com/ApeWorX/ape/blob/731b556b88f3830c5a94511bc3ab32c86bd972a8/src/ape/api/networks.py#L504-L507

Seems like the (first) blocker might be click, since it's using `click.Choice` as a type on the option, it may be preventing this as a valid CLI option:

    $ ape console --network ethereum:mainnet:https://eth-mainnet.alchemyapi...
    Error: Invalid value for '--network': 'ethereum:mainnet:https://eth-mainnet.alchemyapi...

I don't know yet if the relevant provider plugins consume `provider_settings["uri"]`, but seems like it might require moving mountains to support this use case.

**Comment by NotPeopling2day** [comment]
Example of calling ad-hoc network w/ cli

```
$ ape console --network --provider-settings '{"foo": "bar", "uri": "http://xyz.com", ... }'
```

`ProviderAPI.provider_settings`

- [ ] Network guide in docs - Plugins to connect to networks as main workflow, use ad-hoc as a workaround for "not-yet" supported networks
