### ISSUE TITLE
Calling with `sender=ContractInstance` doesn't work

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#606]
### Environment information

* `ape` and plugin versions:

```
$ ape --version
0.1.3

$ ape plugins list
Installed Plugins:
  ens          
  hardhat      
  infura       
  vyper        
  etherscan    
  solidity     
  tokens  
```

* Python Version: 3.9.9
* OS: linux

### What went wrong?

When using a network provider that supports transactions without signatures (such as forked mode networks or local test networks), ape doesn't support calling via a `ContractInstance` object as `sender` e.g.:

```py
one_contract.mutableCall(..., sender=another_contract)
```

### How can it be fixed?

The signature check in certain providers checks to see if `sender` is not of type `AddressType` before switching to using the signature check, which is missing `ContractInstance` (this is done because of a circular dependency). Just add the extra support for `ContractInstace` as well. Could even have it always convert the `sender` argument to `AddressType`, if signing is not required on that network.

**Comment by fubuloubu** [comment]
Debugging this further, seems like there is another issue where `src/ape/contract/base.py:ContractTransaction.serialize_transaction` will convert `AddressType` variables to `HexBytes` (presumably via `HexEncoder`), which fails to serialize properly for the Provider downstream

Thinking that conversion step needs more context into whatever variable types should be for the conversion, at least for `kwargs`

**Comment by fubuloubu** [comment]
quick fix to `ContractTransaction`:

```py
    def _get_type(self, kwarg_name: str) -> Any:
        return TransactionAPI.__fields__[kwarg_name].type_

    def serialize_transaction(self, *args, **kwargs) -> TransactionAPI:
        kwargs = {
            k: self.conversion_manager.convert(
                v,
                # TODO: Upstream, `TransactionAPI.sender` should be `AddressType` (not `str`)
                AddressType if k == "sender" else self._get_type(k),
            )
```

**Comment by fubuloubu** [comment]
Even with above fix, the workaround is to do:

```py
one_contract.mutableCall(..., sender=accounts[another_contract.address])
```

This will load the contract as an `ImpersonatedAccount`

**Comment by sabotagebeats** [comment]
@fubuloubu can you give #619 a shot and see if it resolves the issue?

**Comment by sabotagebeats** [comment]
in v 0.1.5.dev7+g1832fe10

```
File ~/ape/ape/src/ape/api/providers.py:681, in Web3Provider.send_transaction(self, txn)
    680 def send_transaction(self, txn: TransactionAPI) -> ReceiptAPI:
--> 681     txn_hash = self._web3.eth.send_raw_transaction(txn.serialize_transaction())
    682     req_confs = (
    683         txn.required_confirmations
    684         if txn.required_confirmations is not None
    685         else self.network.required_confirmations
    686     )
    688     receipt = self.get_transaction(txn_hash.hex(), required_confirmations=req_confs)

File ~/ape/ape/src/ape_ethereum/ecosystem.py:66, in BaseTransaction.serialize_transaction(self)
     63 def serialize_transaction(self) -> bytes:
     65     if not self.signature:
---> 66         raise SignatureError("The transaction is not signed.")
     68     txn_data = self.dict(exclude={"sender"})
     70     unsigned_txn = serializable_unsigned_transaction_from_dict(txn_data)

SignatureError: The transaction is not signed.
```

**Comment by sabotagebeats** [comment]
https://github.com/ApeWorX/ape-hardhat/issues/38
