### ISSUE TITLE
Not handling `NotImplementedError` leads to difficult to understand issues

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#611]
https://github.com/ApeWorX/ape/blob/30c90195190d7915decc97f17bf4ef427337d24c/src/ape/managers/accounts.py#L56

When this issue is raised, it looks like it can't find the address, when the real issue is that the provider does not allow impersonation. The error message should reflect that, or we can see about just not handling this `NotImplementedError` and letting it propagate upwards.

**Comment by unparalleled-js** [comment]
Let's say I think I have a keyfile with address "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045" so I go to grab it:

If we are to raise `NotImplemented`, it would error with that when I do this:
```python
my_account = accounts["0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"]
```

which seems like a funny error for trying to access an account I thought was mine.

**Comment by unparalleled-js** [comment]
I think adjusting the error message to indicate it could be from either situations is the best way for now

**Comment by fubuloubu** [comment]
> I personally think it is odd to secretly unlock the account from using address-index access and would rather have the user explicitly call `unlock_account()`

I am okay with this, yes
