### ISSUE TITLE
Track if plugins that did not load correctly and don't include them in the `available plugins`

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#614]
### Environment information

Latest ape
Any OS

### What went wrong?

When a plugin fails to load (e.g. from a breaking change), it shows as an available plugin you can install

### How can it be fixed?

Fill this in if you have ideas on how the bug could be fixed.

**Comment by fubuloubu** [comment]
can probably get the set of installed plugins from looking into the site packages

**Comment by Ninjagod1251** [comment]
This is not an issue an anymore

**Comment by Ninjagod1251** [comment]
I didnt mean to close this. How can I break a plugin to fail it? How can we test the plugin to load properly if we do not install it?

**Comment by fubuloubu** [comment]
> I didnt mean to close this. How can I break a plugin to fail it? How can we test the plugin to load properly if we do not install it?

I think one of the easiest ways is to break an `EcosystemAPI` class, since that loads on startup

**Comment by unparalleled-js** [comment]
There are two ways to try:

1. Change the signature of the one of the API methods. This will cause an error saying the plugin is not fully implemented. I am curious if in this case, does it show up in the plugins list output as an available plugin?
2. Similarly, if the plugin has an error during startup. I think to do this, you can add random text to the top of the one source files. This will cause a python syntax error.

**Comment by antazoey** [comment]
the hard part is it would be nice to know that `ape-vyper` is actually a compiler plugin, i wish that data was accessible even when it fails to load correctly

**Comment by antazoey** [comment]
This is no longer happening! Ever since we changed how plugin lookup, using a better source instead of plugin registration, we never show a failed-plugin as an available plugin.
