### ISSUE TITLE
ContractLog repr method should show arguments

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#622]
### Overview
When printing a log that contains arguments, the printout should show those arguments

```py
In [1]: log
Out[1]: <DurationUpdated>

In [2]: print(log)
<DurationUpdated>

In [3]: log.event_arguments
Out[3]: {'duration': 1209600, 'rewardRate': 82671820978905}
```
### Specification

Something that looks more like this:

```py
In [1]: log
Out[1]: <DurationUpdated duration=1209600 rewardRate=82671820978905>

In [2]: print(log)
DurationUpdated(duration=1209600, rewardRate=82671820978905)
```

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by antazoey** [comment]
this got done
