### ISSUE TITLE
git unauthenticated error when pulling dependencies using a github branch in ape config

### ISSUE THREAD

**Issue by storming0x** [ApeWorX/ape#635]
### Environment information

* `ape` and plugin versions: 

```
$ ape --version
ape 0.1.4
$ ape plugins list
Installed Plugins:
  solidity    0.1.0
  hardhat     0.1.4
  vyper       0.1.0
```

* Python Version: 3.9.7
macOS m1: Darwin mac.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64

### What went wrong?

Trying to add to ape-config.yaml dependencies using branch option results in the errors below when running `ape compile`

```yaml
 - name: ds-test
    github: dapphub/ds-test
    branch: master
```

Error output:
```sh
INFO: Cloning branch 'master' from 'ds-test'.

...error log

  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

### How can it be fixed?

Fill this in if you have ideas on how the bug could be fixed.

**Comment by unparalleled-js** [comment]
I think I got something working that uses https instead! Would this be okay for now? See the attached PR.

Note that you have to also set the value `contracts_folder` in your dependency config because it is `src` and not the default `contracts/`.

**Comment by storming0x** [comment]
> I think I got something working that uses https instead! Would this be okay for now? See the attached PR.
> 
> Note that you have to also set the value `contracts_folder` in your dependency config because it is `src` and not the default `contracts/`.

yes, i think https would solve my issue.
