### ISSUE TITLE
File extensions should glob the entire extension

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#636]
### Environment information

* `ape` and plugin versions:

```
$ ape --version
0.1.4

$ ape plugins list
None
```

* Python Version: x.x.x
* OS: linux

### What went wrong?

Certain dependencies like dapptools and foundry us `*.t.sol` as their file extensions to denote testing files. However, we can't compile them currently for other reasons, nor do we need to since they're just testing files.

### How can it be fixed?

Currently, we will see these as just `*.sol` files, but if the file extension glob instead worked with the largest extension in can find on a file, we can differentiate between these types of files and avoid compiling them, which is the job of other tools.

**Comment by unparalleled-js** [comment]
Extensions are weird! Here is more information on what this change means:

* The first `.` found in a contract source file name will note the start of the chain of extensions.
* You cannot have a `.` in the file that is not part of the chain of extensions.
* By including multiple `.` **anywhere** in your source file name, it will cause it not to compiled by `ape` **today**.

I think this is all okay, but we may want to include a way for users to register file-extension (chains) to their `solidity` or `vyper` configs. This way, we can support projects that do want to compile these files.

**Comment by antazoey** [comment]
This is causing issues with users trying to publish contracts with names like `Contract.1.2.3.sol`
