### ISSUE TITLE
Autosign transactions option once the account has been unlocked

### ISSUE THREAD

**Issue by pandadefi** [ApeWorX/ape#637]
### Overview

Now when a user has to review every transaction and approve it.
I see two use cases for the transaction to be auto signed:

- When running a long script with a lot of transactions. That could be a big deployment or some routine scripts you have to run.
- Using ape with a bot that has no cli.

**Comment by fubuloubu** [comment]
Add `set_autosign(enabled: bool)` to `ape_accounts.KeyfileAccount` that bypass the UX around displaying and accepting a transaction before signing it.
