### ISSUE TITLE
ReceiptAPI missing `data` field

### ISSUE THREAD

**Issue by NotPeopling2day** [ApeWorX/ape#638]
### What went wrong?

ReceiptAPI is missing the `data` field containing transaction calldata.

Adding `data` field will be a breaking change.

**Comment by unparalleled-js** [comment]
I don't think adding normal properties is breaking change, only if we use the `@abstractmethod` thing. But if we just do the pydantic class members, I don't think it is, right?

**Comment by fubuloubu** [comment]
> I don't think adding normal properties is breaking change, only if we use the `@abstractmethod` thing. But if we just do the pydantic class members, I don't think it is, right?

Adding new fields to a pydantic model is breaking if it doesn't have a default value.

**Comment by unparalleled-js** [comment]
Could we make it default to `{}` ?

**Comment by fubuloubu** [comment]
> Could we make it default to `{}` ?

The data is bytes, so the only thing that makes it make sense is empty bytes, which is strictly not true

An alternative is to have it be `None` by default, and have it fetch the data on-demand. We can actually backfill the data if we know the original signed transaction, but for transactions we get directly from `ProviderAPI.get_transaction` we'd have to go out and fetch this data using `eth_getRawTransaction` which not every provider supports.

I don't really know why the data field isn't in the transaction receipt object that's returned on `eth_getTransaction`, it seems like a miss to me.

**Comment by unparalleled-js** [comment]
Data seems to be added now!
