### ISSUE TITLE
Learn 2 Ape

### ISSUE THREAD

**Issue by NotPeopling2day** [ApeWorX/ape#651]
### Overview

github.com/ApeAcademy 

### Specification
- [x] How to setup Python env (pipx)
- [ ] How to contribute (pyenv) (not sure)
- [x] How to install ape tutorial
- [x] ERC 20 tutorial
- [x] Ape init template
- [x] NFT tutorial
- [x] Convert contracts to cookiecutter (dependent on which smart contract or project we want to convert) 
- [ ] Make cookies out of brownies (BACKBURNER) waiting on Patrick Video

### Other Tutorials

- [ ] Deploy a contract
- [ ] Test ERC20
- [ ] Test ERC721
- [ ]  Ape Accounts
- [ ]  Interacting with Ape
- [ ] Understanding the Tech Doc

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by ahoymrag** [comment]
We're checked for ERC 20 Tutorial -

**Comment by sabotagebeats** [comment]
@ahoymrag ✅

**Comment by Ninjagod1251** [comment]
@fubuloubu since we added the ape-template. Should we make a 2 min video on how to use it? to satisfy the Ape init ?

**Comment by fubuloubu** [comment]
> @fubuloubu since we added the ape-template. Should we make a 2 min video on how to use it? to satisfy the Ape init ?

Yes, I would say needs a video

**Comment by NotPeopling2day** [comment]
@Ninjagod1251 Whenever you get a moment, let's break this ticket down into whatever is remaining and close this one out.

**Comment by Ninjagod1251** [comment]
Updated ready for launch!

**Comment by Ninjagod1251** [comment]
https://github.com/ApeWorX/ape/pull/768
This is to help with deployment tutorial

**Comment by Ninjagod1251** [comment]
- [ ]  Ape Accounts
- [ ]  Interacting with Ape
- [ ] Understanding the Tech Doc


3 more scripts have been added to guide a user to best use Ape

**Comment by Ninjagod1251** [comment]
Closing the ticket and moving it to a place to keep better track
https://github.com/ApeWorX/academy/issues
