### ISSUE TITLE
Discord bot not running

### ISSUE THREAD

**Issue by NotPeopling2day** [ApeWorX/ape#652]
- [ ] Automate restarting bot on boot-up of cloud server
- [ ] Email upon fail or otherwise notify
- [ ] Move discord bot to docker

**Comment by sabotagebeats** [comment]
- [ ] logging

**Comment by sabotagebeats** [comment]
@Ninjagod1251 should we create a notification via discord message in the except statement?

**Comment by sabotagebeats** [comment]
> * [ ]  Automate restarting bot on boot-up of cloud server
cloud server is not rebooting, this is an issue with python script failing.

**Comment by sabotagebeats** [comment]
issue was with python script not running after logout. restarted process in a screen terminal multiplexer instance.

**Comment by johnson2427** [comment]
I think this issue is closed. The failure doesn't occur because of the script itself, it failed when we closed the remote terminal. If this script begins to fail due to our actual script, we can open this back up.

**Comment by sabotagebeats** [comment]
closing as per @johnson2427
