### ISSUE TITLE
Can't compile a dependency without a `contract/` folder

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#659]
### Environment information

* OS: linux
* Python Version: 3.9.9
* `ape` and plugin versions:

```sh
$ ape --version
# ...copy and paste result of above command here...

$ ape plugins list
# ...copy and paste result of above command here...
```

* Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
dependencies:
    - name: some-dep
      ...
```

### What went wrong?

```sh
$ ape compile
WARNING: No source files found in '~/path/to/project/contracts'.
```

### How can it be fixed?

Fill this in if you have ideas on how the bug could be fixed.

**Comment by unparalleled-js** [comment]
I am not able to reproduce.

My demo project does not specify `contracts_folder` and still compiles.

Is there something else going on?

**Comment by fubuloubu** [comment]
> I am not able to reproduce. I require more information.
> 
> My demo project does not specify `contracts_folder` and still compiles.
> 
> Is there something else going on?
> 
> (my config: https://github.com/unparalleled-js/ape-demo-project/blob/main/ape-config.yaml#L26)

This but actually delete the `contracts/` folder and then do `ape compile`

**Comment by unparalleled-js** [comment]
> This but actually delete the `contracts/` folder and then do `ape compile`

Ahh, I understand - the project has no contracts but still uses dependencies.

On it!
