### ISSUE TITLE
Sign:  [y/N]: shows every tx

### ISSUE THREAD

**Issue by SwapOperator** [ApeWorX/ape#668]
### Environment information

* OS: macOS 
* Python Version: 3.8
* `ape` and plugin versions: 2.0, 2.1, plugins: 0.2.0 vyper, infura, etherscan, hardhat(was deleted)

```sh
$ ape --version
# ...copy and paste result of above command here...

$ ape plugins list
# ...copy and paste result of above command here...
```

* Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
# contracts_folder: contracts

```

### What went wrong?

I decided to test my smart contracts with APE. For that I needed to install hardhat plugin. I did it through pycharm Python Interpreter. However, I needed to do a few more tests on Rinkeby before I ran "ape test". At this moment I found out a bug that ask me to sign tx on each transaction.  I deleted hardhat plugin late, but it didn't help.

my first tx:
```
Sign:  [y/N]: y
Enter passphrase to unlock 'trader03' []: 
Leave 'trader03' unlocked? [y/N]: y

```
The message below after first tx:
```
Sign:  [y/N]:
```
reacts only positive only on Enter, y, n, N. But if I type n or N, the tx will continue to process.

If I type some random symbols:
```
Sign:  [y/N]: sfgsf
Error: invalid input
```

I don't remember the exact version of APE i has before. But I'm sure it was older 2.0.

I tested on a new created env, but I still get with message again and again.

Please include information like:

* what command you ran
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
* full output of the error you received

### How can it be fixed?

Fill this in if you have ideas on how the bug could be fixed.

**Comment by unparalleled-js** [comment]
Hello!  In general, we use test accounts that do not require `y/N` for signing transactions, but you said you are running tests on the Rinkeby network so that is why you are probably using key-file accounts.

Thankfully, there is a solution for this! We have a method for enabling `auto_sign()`... 

```python
account.set_autosign(True)
```
It will prompt you for a passphrase, but you can also pass it on to bypass that:

```python
accounts.set_autosign(True, passphrase="123")
```

Please let me know if this resolves your issue! And thank you for using ape and reporting :)

**Comment by SwapOperator** [comment]
I think something happens with "global path"... but I'm not sure

**Comment by SwapOperator** [comment]
Thanks @fubuloubu and @unparalleled-js . 
The problem was solved

```
    owner = accounts.load("trader03")
    owner.set_autosign(True)
```
