### ISSUE TITLE
Sign: [y/N]: after first signed tx, this message doesn't react on N

### ISSUE THREAD

**Issue by SwapOperator** [ApeWorX/ape#671]
### Environment information

* OS: macOS
* Python Version: x.x.x
* `ape` and plugin versions: 0.2.1

```sh
$ ape --version
0.2.1

$ ape plugins list
ape-infura 0.2.0
ape-vyper 0.2.0
ape-etherscan 0.2.0
```

* Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
contracts_folder: contracts
```

### What went wrong?

Well, I use APE on testnet to generate a bunch of data for my web interface. With old version (I'm not sure what exactly version I have, maybe 1.5 or maybe 1.6) I ran with command ```ape run deploy_testing --network ethereum:rinkeby:infura``` I signed the first tx:
```
Sign:  [y/N]: y
Enter passphrase to unlock 'trader03' []: 
Leave 'trader03' unlocked? [y/N]: y
```
After that I just leave unlocked account and wait when script will done.

Well, I decided to rewrite some test from Brownie to APE and check how it will going. I installed ape-hardhat through PyCharm Python Interpreter. As I understood APE updated too automatically. 

If the script has:

```
    owner = accounts.load("trader03")
    owner.set_autosign(True)
``` 

I hasn't any problems. But if delete these strings and continue to Sign Tx with hands when the next message appear:
```
Sign: [y/N]: 
```
it will react only positive, so if I type y,Y,n,N, or tap on ENTER, the result will be always Yes.

How to reproduce:

token: https://github.com/vyperlang/vyper/blob/master/examples/tokens/ERC20.vy

deploy_testing.py:

```
from ape import project
from ape import accounts

class InitToken(object):

    def load_accs(self, type):
        acc = accounts.load("trader03")

        if type > 0:
          acc.set_autosign(True)

        return acc1

    def create_token(self, name, symbol, decimals, supply,  owner):
        token = owner.deploy(project.Token, name, symbol, decimals, supply)
        return token

    def token_approve(self, token, receiver, amount, sender):
        return token.approve(receiver, int(amount), sender=sender)

random_addr = 0xDf032Bc4B9dC2782Bb09352007D4C57B75160B15
### works fine with set_autosign
deploy = InitToken()

main_account = deploy.load_accs(1)
main_token = start_deploy.create_token("NAME", "SMBL", main_account)
deploy.token_approve(main_token, random_addr, 1e18, main_account)


### check Sing Tx without set_autosign and type N
deploy = InitToken()
main_account = deploy.load_accs(0)
main_token = start_deploy.create_token("NAME", "SMBL", main_account)
deploy.token_approve(main_token, random_addr, 1e18, main_account)
deploy.token_approve(main_token, random_addr, 1e18, main_account)
deploy.token_approve(main_token, random_addr, 1e18, main_account)

```

NOTE: First tx I signed and leave account open.

```
Sign:  [y/N]: y
Enter passphrase to unlock 'trader03' []: 
Leave 'trader03' unlocked? [y/N]: y
```

if account is locked, then everything works fine. 

Please include information like:

* what command you ran
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
* full output of the error you received

### How can it be fixed?

Fill this in if you have ideas on how the bug could be fixed.

**Comment by unparalleled-js** [comment]
> it will react only positive, so if I type y,Y,n,N, or tap on ENTER, the result will be always Yes.

I could use some information on the issue, as I was not able to reproduce this!

I modified your example some to get it to run and then things behaved as expected. e.g. when I select `N`, it does not leave the account unlocked.

Here is a simpler attempt at reproducing, but things seem to work (the account remains locked when selecting `No`):

```python
(kong) ➜  ape-demo-project git:(main) ✗ ape console --network ethereum:mainnet-fork
INFO: Starting 'Hardhat node' process.

In [1]: account = accounts.load("test0")

In [2]: project.FundMe.deploy(sender=account)
DynamicFeeTransaction:
  chainId: 31337
  from: 0x1e59ce931B4CFea3fe4B875411e280e173cB7A9C
  gas: 411810
  nonce: 0
  value: 0
  data: 0x608060...0d0033
  type: 0x02
  maxFeePerGas: 35792896749
  maxPriorityFeePerGas: 0

Sign:  [y/N]: y
Enter passphrase to unlock 'test0' []: 
Leave 'test0' unlocked? [y/N]: N
INFO: Confirmed 0x87061ff1113ac465da2396d0b03bfa3c430b43928897c2fbd1f5c436638acd3f (gas_used=411810)
SUCCESS: Contract 'FundMe' deployed to: 0x274b028b03A250cA03644E6c578D81f019eE1323
Out[2]: <FundMe 0x274b028b03A250cA03644E6c578D81f019eE1323>

In [3]: project.FundMe.deploy(sender=account)
DynamicFeeTransaction:
  chainId: 31337
  from: 0x1e59ce931B4CFea3fe4B875411e280e173cB7A9C
  gas: 411810
  nonce: 1
  value: 0
  data: 0x608060...0d0033
  type: 0x02
  maxFeePerGas: 0
  maxPriorityFeePerGas: 0

Sign:  [y/N]: y
Enter passphrase to unlock 'test0' []: 
Leave 'test0' unlocked? [y/N]: N
INFO: Confirmed 0xe464e24a3aad0aafb1528a873347c98becc77c347f08964ff68d3c3034b7b384 (gas_used=411810)
SUCCESS: Contract 'FundMe' deployed to: 0xBcF7FFFD8B256Ec51a36782a52D0c34f6474D951
Out[3]: <FundMe 0xBcF7FFFD8B256Ec51a36782a52D0c34f6474D951>

In [4]: 
```

**Comment by fubuloubu** [comment]
@SwapOperator if you could please add more context that will help unblock us!

**Comment by SwapOperator** [comment]
> @SwapOperator if you could please add more context that will help unblock us!
sorry I was busy these days.
I made the small video

https://user-images.githubusercontent.com/93691214/166560611-a7849402-cce7-4a63-bdc1-66cf22c74979.mov

**Comment by unparalleled-js** [comment]
@SwapOperator It is strange, because when I do the same thing in your video, I get:

```
Sign:  [y/N]: n
ERROR: (SignatureError) The transaction was not signed.
```

I still need more info!
Perhaps send me your `pip freeze` output as well as Python version and your exact script (just to repro, not anything private).

We will figure this out!

**Comment by SwapOperator** [comment]
> pip freeze

```
aiohttp==3.8.1
aiosignal==1.2.0
ape-alchemy==0.2.0
ape-etherscan==0.2.0
ape-hardhat==0.2.0
ape-infura==0.2.0
ape-vyper==0.2.0
appnope==0.1.3
asttokens==2.0.5
async-timeout==4.0.2
attrs==21.4.0
backcall==0.2.0
base58==2.1.1
bitarray==1.2.2
cached-property==1.5.2
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
click==8.1.2
colorama==0.4.4
commonmark==0.9.1
cytoolz==0.11.2
decorator==5.1.1
Deprecated==1.2.13
eth-abi==2.1.1
eth-account==0.5.7
eth-ape==0.2.1
eth-bloom==1.0.4
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.4
eth-rlp==0.2.1
eth-tester==0.6.0b6
eth-typing==2.3.0
eth-utils==1.10.0
ethpm-types==0.1.1
evm-trace==0.1.0a2
executing==0.8.3
frozenlist==1.3.0
hexbytes==0.2.2
idna==3.3
importlib-metadata==4.11.3
importlib-resources==5.7.1
iniconfig==1.1.1
ipfshttpclient==0.8.0a2
ipython==8.2.0
jedi==0.18.1
jsonschema==4.4.0
lru-dict==1.1.7
matplotlib-inline==0.1.3
multiaddr==0.0.9
multidict==6.0.2
mypy-extensions==0.4.3
netaddr==0.8.0
numpy==1.22.3
packaging==20.9
pandas==1.4.2
parsimonious==0.8.1
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
pluggy==0.13.1
prompt-toolkit==3.0.29
protobuf==3.20.1
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
py-ecc==5.2.0
py-evm==0.5.0a3
py-geth==3.7.0
pycparser==2.21
pycryptodome==3.14.1
pydantic==1.9.0
pyethash==0.1.27
pygit2==1.9.1
PyGithub==1.55
Pygments==2.12.0
PyJWT==2.3.0
PyNaCl==1.5.0
pyparsing==3.0.8
pyrsistent==0.18.1
pysha3==1.0.2
pytest==6.2.5
python-dateutil==2.8.2
pytz==2022.1
PyYAML==6.0
requests==2.27.1
rich==10.16.2
rlp==2.0.1
semantic-version==2.9.0
six==1.16.0
sortedcontainers==2.4.0
stack-data==0.2.0
toml==0.10.2
toolz==0.11.2
tqdm==4.64.0
traitlets==5.1.1
trie==2.0.0a5
typing-extensions==3.10.0.2
urllib3==1.26.9
varint==1.0.2
vvm==0.1.0
wcwidth==0.2.5
web3==5.29.0
websockets==9.1
wrapt==1.14.0
yarl==1.7.2
zipp==3.8.0
```

```
(venv) user@alexey Vyper % python
Python 3.8.2 (default, Jun  8 2021, 11:59:35) 
```

No matter what smart contract I try to deploy. I receive the same result.

**Comment by unparalleled-js** [comment]
@SwapOperator Are you able to share the contents of `deploy_mainnet.py` ?

**Comment by SwapOperator** [comment]
> @SwapOperator Are you able to share the contents of `deploy_mainnet.py` ?

I send you an  invite to my repo. :) enjoy

**Comment by unparalleled-js** [comment]
Ah! I was able to reproduce! When I install the `ape-ethersan` plugin, I have this problem.
Strange!

**Comment by unparalleled-js** [comment]
I was able to reproduce!

**Comment by SwapOperator** [comment]
> I was able to reproduce!

ape-etherscan as I understood? :)

**Comment by unparalleled-js** [comment]
> ape-etherscan as I understood? :)

Ah, no, that was a false hypothesis. The real reason is that I had an issue with the contract I was using to try and re-pro.

**Comment by SwapOperator** [comment]
> > ape-etherscan as I understood? :)
> 
> Ah, no, that was a false hypothesis. The real reason is that I had an issue with the contract I was using to try and re-pro.

Did you try with different contracts or script structure?

**Comment by unparalleled-js** [comment]
> Did you try with different contracts or script structure?

I was able to repro! Just wasn't because of ape-etherscan as I had thought
