### ISSUE TITLE
Allow CompilerAPI to compile things ad-hoc

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#688]
### Overview

Sometimes it's handy to be able to compile a quick smart contract in a given language. `CompilerAPI` should allow that

### Specification

Add a method `compile_code` to `CompilerAPI`

```py
class CompilerAPI:
    ...
    def compile_code(code: str) -> ContractContainer:
    ...
```

### Dependencies
No deps

**Comment by fubuloubu** [comment]
Not sure if method should return exactly one container, or a list

**Comment by antazoey** [comment]
what about something like:

```python
def compile_code(*code: str) -> Iterator[ContractContainer]:
```

so you can give it multiplie codes and it gives you multiple contract  containers

**Comment by fubuloubu** [comment]
> what about something like:
> 
> ```python
> def compile_code(*code: str) -> Iterator[ContractContainer]:
> ```
> 
> so you can give it multiplie codes and it gives you multiple contract  containers

I think too complicated, and you can just replicate with this:

```py
containers = map(compilers["vyper"].compile_code, codes)
```
