### ISSUE TITLE
manifest.py is missing sourceId

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#69]

**Comment by lost-theory** [comment]
I couldn't reproduce this @sabotagebeats. I used the latest version of the ape `main` branch and your  `draft/pysolc` branch of ape-solidity, and an existing brownie solidity project. I was able to look up `sourceId` on the contracts after compiling:

```
$ ape --version
0.1.0a13.dev1+g15edea9

$ ape plugins list
WARNING: $GITHUB_ACCESS_TOKEN not set, skipping 2nd class plugins
Installed plugins:
  ape_vyper (0.1.0a2.dev0+g624e8d3.d20210507)
  ape_solidity (0.1.dev26+g4fed6de)

$ find . -type f -name "*.sol"
./contracts/Token.sol
./contracts/SafeMath.sol

$ ape console
In [1]: project.contracts
# ...this causes the contracts to be compiled...

In [2]: project.cached_manifest.SafeMath.sourceId
Out[2]: 'contracts/SafeMath.sol:SafeMath'
```          

If you remember how we triggered this bug this let me know. Maybe you had an older version of ape installed with your solidity plugin?

**Comment by sabotagebeats** [comment]
Gonna close this for now since this seems like it may have been local to my machine. We can reopen it later if need be.
