### ISSUE TITLE
feat: add return value for transactions

### ISSUE THREAD

**Issue by Ninjagod1251** [ApeWorX/ape#717]
### Overview

Provide a simple overview of what you wish to see added. Please include:

Upon making a test for ERC20 Smart contract. We should add a return value for accounts.

```py
tx = contract.myMutableMethod(...)
assert tx.return_value == ...  # .return_value doesn't exist

```

* What you are trying to do
* Why Ape's current functionality is inadequate to address your goal

### Specification

Describe the syntax and semantics of how you would like to see this feature implemented. The more detailed the better!

Remember, your feature is much more likely to be included if it does not involve any breaking changes.

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by fubuloubu** [comment]
Wait, this issue isn't what I wanted you to open, you can solve this by doing the following (note that list slices are non-inclusive on the right hand side):

```py
receiver, spender = accounts[1:3]
```

**Comment by fubuloubu** [comment]
the actual issue is the following:
```py
tx = contract.myMutableMethod(...)
assert tx.return_value == ...  # .return_value doesn't exist
```

**Comment by unparalleled-js** [comment]
You have to use events for transactions I believe.

https://ethereum.stackexchange.com/questions/73787/solidity-return-value-of-smart-contract-transact

I showed @Ninjagod1251 how to get the events from a receipt!

**Comment by fubuloubu** [comment]
> You have to use events for transactions I believe.
> 
> https://ethereum.stackexchange.com/questions/73787/solidity-return-value-of-smart-contract-transact
> 
> I showed @Ninjagod1251 how to get the events from a receipt!

Not sure if this is event related, might require traces actually... I think the trick is to decode the `debug_traceTransaction` one level and obtain the last structLog item which should contain the return value. Can also use `evm-trace` to return

https://github.com/eth-brownie/brownie/blob/3aecd87f47c9c316c85b0b0c6252ff7d900cca74/brownie/network/transaction.py#L274-L275

**Comment by Ninjagod1251** [comment]
Look like we should research more and I think I might be in over my head. I would love to listen in and test the feature

**Comment by fubuloubu** [comment]
> Look like we should research more and I think I might be in over my head. I would love to listen in and test the feature

Yeah, please hold off on this for now

**Comment by banteg** [comment]
this can be quite easily done now
```python
call_tree = chain.provider.get_call_tree(tx)
method_abi = Contract(tree.address).contract_type.mutable_methods[call_tree.calldata]
output = chain.provider.network.ecosystem.decode_returndata(method_abi, call_tree.returndata)
if isinstance(output, tuple) and len(output) < 2:
    output = output[0] if len(output) == 1 else None
```

**Comment by fubuloubu** [comment]
@helloibis might be able to take a stab at adding this to the `ReceiptAPI` class as a `.return_value` property, and let it raise if the current provider does not implement `.get_call_tree`
