### ISSUE TITLE
Add API method to get virtual machine error in ProviderAPI

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#720]
### Elevator pitch:

Because of this newly found bug: https://github.com/ApeWorX/ape-hardhat/pull/59#issuecomment-1126999704
we need a way to call a provider's custom logic for getting a custom error.

### Value:

fork-networks where the error message format is different than the local provider's.

### Dependencies:

ape
ape-hardhat
ape-foundry

### Design approach:

```python
def get_virtual_machine_error(self, err: Exception) -> VitualMachineError:
   """
   Get a virtual machine error from an error returned from your RPC.
   If from a contract revert / assert statement, you will be given a
   special :class:`~ape.exceptions.ContractLogicError` and can be
   checked in ``ape.reverts()`` tests.
   
   Args:
       err (Exception): The error returned from your RPC client.
   
   Returns:
       :class:`~ape.exceptions.VirtualMachineError`: An error representing what
          went wrong in the call.
   """
```

### Task list:

* [x] - get approval
* [x] - add API
* [x] - make sure works in hardhat and fixes bug
* [x] - release ape
* [x] - update and release ape-hardhat

### Estimated completion date:

It won't take long to implemenet; the design may be the hardest part.

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
Plan seems appropiate, I approve!
