### ISSUE TITLE
feat: Prompt user to install missing required plugins

### ISSUE THREAD

**Issue by Ninjagod1251** [ApeWorX/ape#729]
### Elevator pitch:

Prompt user when they do not have required plugins installed.

### Value:

Users, especially after `ape init` in a fresh environment.

### Design approach:

* Make list of required project plugins accessible from `ConfigManager`
* Prompt user after `ape init` to install them

```
Missing required plugins 'hardhat', 'alchemy', and 'tokens'. Install? [y/N]
```

### Estimated completion date:

No estimate

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by Ninjagod1251** [comment]
@unparalleled-js  and @fubuloubu  please let me know if did to add more to this

**Comment by fubuloubu** [comment]
Would restate this to basically suggest installing a 2nd party plugin if it's not already installed but matches the command selection

The piece of code that does that is here: https://github.com/ApeWorX/ape/blob/main/src/ape/_cli.py#L53

**Comment by unparalleled-js** [comment]
> Would restate this to basically suggest installing a 2nd party plugin if it's not already installed but matches the command selection

This seems different than installing plugins from a script?
I'm confused!

**Comment by unparalleled-js** [comment]
Worked with @Ninjagod1251 and made this into a Work Item based on my understanding of the request.
Feel free to edit / adjust in order to get sign-off and have it meet your needs.

**Comment by fubuloubu** [comment]
> Worked with @Ninjagod1251 and made this into a Work Item based on my understanding of the request. Feel free to edit / adjust in order to get sign-off and have it meet your needs.

Looks good, although I would make sure it's not too annoying with the requests. I think it's okay to run this after `ape init` as a reminder, however it should not run every time you use the command line with a suggested plugin in `ape-config.yaml`

**Comment by unparalleled-js** [comment]
Agreed. Let's limit this just to `ape init` for now.

**Comment by unparalleled-js** [comment]
- [ ] Close and add summary: @Ninjagod1251

**Comment by Ninjagod1251** [comment]
This has been completed:

```
#       Usage example: `pipx install eth-ape[recommended-plugins]`
    "recommended-plugins": [
        "ape-alchemy",  # Alchemy public network provider
        "ape-ens",  # ENS converter
        "ape-etherscan",  # Etherscan explorer plugin
        "ape-foundry",  # Foundry local and fork network EVM provider
        "ape-hardhat",  # Hardhat local and fork network EVM provider
        "ape-infura",  # Infura public network provider
        "ape-ledger",  # Ledger Nano S/X hardware wallet
        "ape-solidity",  # Solidity compiler support
        "ape-template",  # Cookiecutter template support
        "ape-tokens",  # Tokenlists converter
        "ape-trezor",  # Trezor Model T/One hardware wallet
        "ape-vyper",  # Vyper compiler support],
```
