### ISSUE TITLE
Unable to use strings as inputs for bytes32 method parameters

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#737]
### Environment information

* OS: macOS 
* Python Version: 3.7

latest ape

### What went wrong?

Say you have a contract method like this:

```solidity
function methodB1(bytes32 lolol, uint256 dynamo) public {
...
```

and you go to call it like this:

```python
contract_b.methodB1("yo", 4)
```

You get the error:

```
EncodingTypeError: Value `'yo'` of type <class 'str'> cannot be encoded by BytesEncoder
```

### How can it be fixed?

Automatically convert str to bytes when passing it to bytes32 input type

**Comment by fubuloubu** [comment]
I would think you'd have to do `b"yo"` and even then, it's not 32 bytes in length so probably should fail

**Comment by unparalleled-js** [comment]
Also `b"yo"` works!

**Comment by fubuloubu** [comment]
> Also `b"yo"` works!

Wonder how this pads...

**Comment by fubuloubu** [comment]
> @fubuloubu But could we include a converter that does this? Both converts to bytes + pads so its easier to use strings when necessary?

I think it's better to be a little more explicit here. Just add a `b` when asked
