### ISSUE TITLE
General: Add EIP 712 Support

### ISSUE THREAD

**Issue by ShadeUndertree** [ApeWorX/ape#75]
### Elevator pitch:

We already support EIP-712 in the hardware plugins, or at least have a plan to.
We need to also do this for 1st class account plugins, such as `ape-accounts` and `ape-test`.

### Value:

Able to interact in the ecosystem better.

### Dependencies:

https://eth-account.readthedocs.io/en/stable/eth_account.html?highlight=eip-712#eth_account.messages.encode_structured_data

### Design approach:

See `ape-ledger` plugin as an example.

* Step 1: detect message type
* Step 2: If structures, encode it to EIP-191
* Step 3: sign the message (what the two plugins are already doing)

^ Different for non 1st-class account plugin that are based on other libraries. This only applies to account plugin that use `eth-account` (ones that have access to the pkey).

### Task list:

* [ ] Update `ape-accounts` to support signing EIP712 messages
* [ ] Update `ape-test` to support signing EIP712 messages

`ape-ledger` already supports this.
And we have https://github.com/ApeWorX/ape-trezor/issues/8 in `ape-trezor` that can probably be done now (we were waiting on the next release of their lib last I checked).

### Estimated completion date:

TBD.

### Design review:

This is Jules... Signing off!

**Comment by unparalleled-js** [comment]
Upon further investigation, as the `trezorlib` method is finally available to us, it seems we should have a separate API method for this.

Reason:

The trezor lib requires the `dict()` version as it processes and sends over bits in chunks and needs access to the data in other ways.

So using the `eip712.signable_message` property, like we can do in `ape-ledger`, does not work so nicely.
If we had a more generic API method, we can better support EIP-712 messages in `ape-trezor`.
