### ISSUE TITLE
Multiple event with the same name in different contracts error with `as already been declared`

### ISSUE THREAD

**Issue by pandadefi** [ApeWorX/ape#751]
### Environment information

* OS: macOS
* Python Version: x.x.x
* `ape` and plugin versions: 0.2.7

### What went wrong?

After an update from 0.2.2 to 0.2.7 I am getting the following error when trying to run `ape test` on https://github.com/yearn/veYfi/

```
E                   ape.exceptions.ContractError: Multiple events with the same ABI defined in 'Gauge'.
```

**Comment by unparalleled-js** [comment]
I did some digging on this. The `Gauge` contract has two events in its ABI named `Initialize`. They can be described as:

```python
EventABI(type='event', name='Initialized', inputs=[EventABIType(name='stakingToken', type='address', components=None, internalType='address', indexed=True), EventABIType(name='rewardToken', type='address', components=None, internalType='address', indexed=True), EventABIType(name='owner', type='address', components=None, internalType='address', indexed=True), EventABIType(name='rewardManager', type='address', components=None, internalType='address', indexed=False), EventABIType(name='ve', type='address', components=None, internalType='address', indexed=False), EventABIType(name='veYfiRewardPool', type='address', components=None, internalType='address', indexed=False)], anonymous=False)

EventABI(type='event', name='Initialized', inputs=[EventABIType(name='version', type='uint8', components=None, internalType='uint8', indexed=False)], anonymous=False)
```

Only the first one is actually defined in the contract. I have not yet found where the other one is coming from.
I have figured out a solution (check signature instead of name pre-error-ing). However, I don't know how to replicate this issue in the tests yet.

**Comment by unparalleled-js** [comment]
Ope found it: https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/proxy/utils/Initializable.sol#L72
