### ISSUE TITLE
Add ability to disable caching for tests

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#77]
### Overview

Provide a simple overview of what you wish to see added. Please include:

* What you are trying to do
* run testing
* Why Ape's current functionality is inadequate to address your goal
* testing is using cached build 

### Specification

Describe the syntax and semantics of how you would like to see this feature implemented. The more detailed the better!

Remember, your feature is much more likely to be included if it does not involve any breaking changes.

add ability to disable cache in a test with a flag 

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by unparalleled-js** [comment]
what type of caching does this refer to?

**Comment by fubuloubu** [comment]
> what type of caching does this refer to?

I actually have no idea lol

**Comment by unparalleled-js** [comment]
Lol!
