### ISSUE TITLE
Add `%ape` magic to `ape console`

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#778]
### Overview

In IPython, it's sometimes helpful to use magics to process external commands

```py
In [1]: %%shell
  ... :  ape accounts list
```

It'd be really helpful to be able to run certain ape commands this way as well

### Specification

Add a custom magic `%ape` that let's you execute the ape command line

https://ipython.readthedocs.io/en/stable/config/custommagics.html

### Dependencies

n/a

**Comment by banteg** [comment]
you can just run `!ape` which does the same

**Comment by fubuloubu** [comment]
> you can just run `!ape` which does the same

Ah yes, fair
