### ISSUE TITLE
adhoc code compiling 

### ISSUE THREAD

**Issue by pandadefi** [ApeWorX/ape#789]
### Overview

I would like to do something like https://github.com/yearn/yearn-vaults/blob/main/tests/conftest.py#L79 in ape

- get the source code from the Vault object
- replace the vault version
- recompile
- deploy

### Specification

I will need access to the source code and have a function to compile code from arbitrary text.

**Comment by charles-cooper** [comment]
maybe it would be good to add a vyper flag to disable version checking? @pandadefi @fubuloubu

**Comment by fubuloubu** [comment]
> maybe it would be good to add a vyper flag to disable version checking? @pandadefi @fubuloubu 

Generally okay, but I don't think that has any bearing on the solution here. He's talking about the API version variable we maintain in yearn's contracts

**Comment by antazoey** [comment]
Duplicate of https://github.com/ApeWorX/ape/issues/688?
