### ISSUE TITLE
SPIKE: redesign or update manifest

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#794]
### Elevator pitch:
We need to decide if we want to refactor or redesign or update contract manifest in order to support future ape designs

### Value:
If we need to add additional information to the contract manifest we will need to update the way it works and refactor 

### Dependencies:
discussion and brainstorm on what this will look like and whether we should do this 

### Task list:

* [ ] Tasks go here

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by antazoey** [comment]
Is this tracked with @Ninjagod1251 's work?

**Comment by Ninjagod1251** [comment]
It is not atm, but I can link it

**Comment by fubuloubu** [comment]
I don't think there's anything specifically needed by this spike anymore, we can document more specifically any smaller issues we run into
