### ISSUE TITLE
Allow folders inside the scripts folder

### ISSUE THREAD

**Issue by PatrickAlphaC** [ApeWorX/ape#804]
### Overview

Provide a simple overview of what you wish to see added. Please include:

* What you are trying to do
* Why Ape's current functionality is inadequate to address your goal

### Specification

I'd like to have a folder inside the scripts folder and be able to run it as a script.

Let's say I have a file like so:

*scripts/deploy/deploy_me.py*

```python
from ape import project
from ape import accounts

def main():
  print("hi")
  contract = accounts[-1].deploy(project.MyContract)
```

I can't run it with:

```
ape run scripts/deploy/deploy_me.py
```

**Comment by banteg** [comment]
`ape run deploy.deploy_me` also sounds like a good convention, similar to how you'd invoke python modules with `python -m scripts.deploy.deploy_me`

**Comment by fubuloubu** [comment]
> `ape run deploy.deploy_me` also sounds like a good convention, similar to how you'd invoke python modules with `python -m scripts.deploy.deploy_me`

Supporting both should be fine
