### ISSUE TITLE
General: Add support for smart contract verification to ExplorerAPI

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#81]
### Overview

When you deploy a smart contract to a public network, you often want to verify that contract's source code through one (or more) blockchain explorer(s) source code verification API (if it exists).

### Specification

Add a kwarg `verify=None` to `AccountAPI.deploy(ContractType, ..., verify=True)` that will publish the corresponding smart contract code to any loaded `ExplorerAPI` plugin

Also prototype a way to verify source code "after the fact", maybe via `ContractInstance` or `ReceiptAPI` of the deployment txn.

### Dependencies

Have to be able to link back to the `Source`(s) (or just use the package manifest directly) from a `ContractType` of the deployed contract.

**Comment by unparalleled-js** [comment]
there is also an issue for this found in `ape-etherscan`: https://github.com/ApeWorX/ape-etherscan/issues/22
Now, they are linked :)

**Comment by sabotagebeats** [comment]
dependency #792 #530

**Comment by sabotagebeats** [comment]
related: https://github.com/ApeWorX/ape/issues/794

**Comment by sabotagebeats** [comment]
@NotPeopling2day I believe this is the information you were requesting above 👍

**Comment by sabotagebeats** [comment]
dependency: https://github.com/ApeWorX/ape/issues/850

**Comment by sabotagebeats** [comment]
status: blocked by https://github.com/ApeWorX/ape/issues/948 and https://github.com/ApeWorX/ape/issues/530
