### ISSUE TITLE
ape test can't find modules?

### ISSUE THREAD

**Issue by DrawnWren** [ApeWorX/ape#813]
### Environment information

* OS: linux
* Python Version: 3.9.13
* `ape` and plugin versions: ape 0.3.0

* Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

```sh
$ cat ape-config.yaml
name: project_name
```

### What went wrong?
After a fresh install of ape into an existing code repo, running ape test fails to import project modules. pip is latest version and it's being done w/in a venv. 
```
(project_name) prompt :: code/project_name 130 » which ape
$HOME/code/project_name/project_name/bin/ape
```
```
___________________________________________________________________ ERROR collecting tests/unit/test_imp_loss.py ____________________________________________________________________
ImportError while importing test module '$HOME/code/project_name/tests/unit/test_imp_loss.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../.pyenv/versions/3.9.13/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/test_imp_loss.py:4: in <module>
    from logic.exchanges.univ2.helpers import calculate_price_ratio, calculate_impermanent_loss
E   ModuleNotFoundError: No module named 'logic'
```

(There is a module named logic, and brownie had no problem detecting. Seems like a weird issue w/ ape)

**Comment by DrawnWren** [comment]
I'm an idiot, but I'll leave this here in case anyone else isn't smart enough to be an ape. My ``PYTHONPATH`` didn't include the project root.

**Comment by fubuloubu** [comment]
> I'm an idiot, but I'll leave this here in case anyone else isn't smart enough to be an ape. My `PYTHONPATH` didn't include the project root.

Well thank you for sharing your issues for others to find in case they get stuck too!
