### ISSUE TITLE
ability to skip compilation before tests

### ISSUE THREAD

**Issue by ca11ab1e** [ApeWorX/ape#822]
### Overview

I have a setup where both Solidity, and Cairo, contracts live together.
The goal is to be able to test either Solidity contracts, either Cairo contracts, or both at the same time to compare results.

The issue here, is that `ape test` first recompiles all contracts. That is problematic for 3 reasons:

1. If I run tests on Solidity contracts, Ape will compile Cairo contracts too (and there may compilation be errors that would block Solidity tests). Not talking about the overall compilation time.
2. The current behavior does not seem robust (no offense): the recompilation occurs even when files did not change, like every 3 runs, or so. It may be a separate problem, but my proposal could help for such situation.
3. Compilation checks of all files is done before each test case (meaning a test file with 3 test functions will trigger 3 compilation checks of all contracts). Time, and resource consuming?

### Specification

I propose a simple, yet efficient, way of skipping the compilation: `APE_NO_COMPILATION` environment variable. If set to `1`, then no compilation occurs. The name can be debated, of course.
Such change is backward compatible, and does not change the current default behavior.

### Dependencies

None.

**Comment by unparalleled-js** [comment]
We could also add a flag `--skip-compilation` to pytest

`ape test --skip-compilation` or `pytest --skip-compilation`

**Comment by unparalleled-js** [comment]
Item 2 is concerning. I am not sure why that would happen (or even if still does).

`--skip-compilation` seems okay tho because then you can manage your own compilation via `ape compile` commands

**Comment by antazoey** [comment]
this no longer happens. contracts get compiled upon first request now, in a lazy way, regardless of whether you are running tests or not
