### ISSUE TITLE
Package manifest should use relative paths

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#83]
### What went wrong?
The package manifest currently uses absolute paths. This will not create a repeatable build when the packages are uploaded to immutable file storage. The should be relative to the `contracts/` folder (e.g. `Contract.vy` instead of `/home/username/.../project/contracts/Contract.vy`)

### How can it be fixed?
The paths should be relative to the `contracts` folder (or eventually to the other manifests when dependencies have full support)

**Comment by fubuloubu** [comment]
@lost-theory any thoughts on this suggested change?

**Comment by unparalleled-js** [comment]
Fixed in #408 
The source paths are now relative to the contracts folder. AND they have to be per `ethpm-types` `PackageManifest` pydantic validators.
