### ISSUE TITLE
Plugin for Avalanche Network

### ISSUE THREAD

**Issue by Ninjagod1251** [ApeWorX/ape#833]
### Overview

Provide a simple overview of what you wish to see added. Please include:

* What you are trying to do

I would like to make a plugin to connect avalanche

* Why Ape's current functionality is inadequate to address your goal

Ape has Optimism and Polygon. I would like to try and make a plugin for another network and then make a tutorial on it. So other users from other networks can make their own! 

Links for resource and reference:
ape [ecosystem](https://github.com/ApeWorX/ape/blob/main/src/ape_ethereum/ecosystem.py#L114)
[optimism](https://github.com/ApeWorX/ape-optimism)
[Polygon](https://github.com/ApeWorX/ape-polygon) 

### Specification

Describe the syntax and semantics of how you would like to see this feature implemented. The more detailed the better!

Remember, your feature is much more likely to be included if it does not involve any breaking changes.

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by Ninjagod1251** [comment]
@unparalleled-js  what are you thoughts on this?

**Comment by fubuloubu** [comment]
Someone has made one already in Discord

**Comment by unparalleled-js** [comment]
Let the community support it for now! Thanks to whoever did that :) !!!
