### ISSUE TITLE
Include Logs in transaction trace

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#834]
### Overview

Foundry is able to include events in the logs... so should we!
![IMAGE 2022-06-28 11:22:01](https://user-images.githubusercontent.com/19540978/176230726-412250c3-78d1-47bd-92a2-8a49ad44a506.jpg)

**NOTE**: This may only be possible in the geth style logs.

### Specification

See image ! But make fit in . Use your favorite ape crayon colors (pick a new color for the event name but use the input color for the inputs)

### Dependencies

Might need to add support in `evm-trace` first: https://github.com/ApeWorX/evm-trace/issues/9

**Comment by fubuloubu** [comment]
Do you mean displaying logs when printing the tree? Or do you mean logging the events that occur within any transaction you broadcast to the network?

**Comment by banteg** [comment]
one thing to consider is parity-style trace doesn't return logs, only calls, so this would only by possible with geth-style logs by catching `LOG0...LOG4` [opcodes](https://ethervm.io/#A0).
