### ISSUE TITLE
compile filepath

### ISSUE THREAD

**Issue by benjyz** [ApeWorX/ape#85]
### Environment information

* `ape` and plugin versions:

0.1.0a14.dev2+gf51ff39

* Python Version: x.x.x
* OS: osx/linux/win

### What went wrong?

I call compile and have a greeter.sol contract in contracts folder, but not found.
```
ape compile
WARNING: No project files detected in '/Users/ben/dev/apetest/contracts'
ls contracts 
Greeter.sol
```

### How can it be fixed?

investigating

**Comment by benjyz** [comment]
more info

```
INFO: no filepath specified
INFO: project.path '/Users/ben/dev/apetest'
INFO: project.sources []
WARNING: No project files detected in '/Users/ben/dev/apetest/contracts'. 
contract_filepaths: '[]'
```

**Comment by fubuloubu** [comment]
So this bug happens when you have no compiler plugins installed. The error message should be better (maybe summarizing the extensions and saying "no compiler installed to handle extension `*/sol`")
