### ISSUE TITLE
Leverage the mypy configuration file

### ISSUE THREAD

**Issue by ca11ab1e** [ApeWorX/ape#853]
### Overview

There are lots of `type: ignore` comments in imports.

Would you be interested in a PR to create the mypy configuration file to skip that [specific check](https://mypy.readthedocs.io/en/stable/config_file.html#confval-ignore_missing_imports)?

### Specification

Here is the minimal `mypy.ini` file (I will open a PR to update pyproject.toml instead of using mypy.ini):

```ini
[mypy]
ignore_missing_imports = true
```

And a complete example (my preference):

```ini
[mypy]
# Ensure we know what we do
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
# warn_unreachable = true  (to check)

# Imports management
ignore_missing_imports = true
follow_imports = normal
```

### Dependencies

None.

**Comment by fubuloubu** [comment]
Ideally we'd like to find a way to get rid of the ignored if possible, the type hints have found numerous latent bugs for us. There are some scenarios that are difficult to work through though so we take it on a case by case basis
