### ISSUE TITLE
Automine functionality

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#862]
### Overview

Properly support disabling and enabling automine
(Sorry I thought there was a ticket for this already but not seeing it and it's been requested by the community)

### Specification

```python
class ChainManager:
    def set_automine(automine_active: bool): ...
```

```python
class ProviderAPI:
    @raises_not_implemented
    def set_automine(automine_active: bool): ...
```

- [ ] Support in `EthTester` if possible.
- [ ] Support in geth if possible (only applies to ephemeral, local geth)
- [ ] Definitely add support to hardhat plugin next
- [ ] Definitely add support to foundry plugin next

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by fubuloubu** [comment]
I approve of this design

**Comment by banteg** [comment]
could it be a property with a setter?

```python
>>> chain.automine
True
>>> chain.automine = False
(sends rpc request to disable automine if it's enabled)
```

**Comment by fubuloubu** [comment]
> could it be a property with a setter?
> 
> ```python
> >>> chain.automine
> True
> >>> chain.automine = False
> # sends rpc request to disable automine if it was enabled
> ```
> 
> the description could read something like
> 
> > Whether to automatically mine a new block after each transaction submitted. Disable `automine` to pack multiple transactions into a block by hand using `chain.mine()`

That works for me!

**Comment by unparalleled-js** [comment]
> could it be a property with a setter?

I don't like hiding RPC requests because properties. It seems like anything using HTTP should happen in a method.

However, we abuse this everywhere else in the entire framework so I am good with it for consistency's sake.

**Comment by fubuloubu** [comment]
> > could it be a property with a setter?
> 
> I don't like hiding RPC requests behind properties. It seems like anything using HTTP should happen in a method.

It may not be an RPC request, depending on provider. Like, one could imagine for `eth-tester`, it literally is just setting a property.

I think it's important to have it feel consistent, but not entirely sure it should be a property either.

**Comment by fubuloubu** [comment]
> > could it be a property with a setter?
> 
> I don't like hiding RPC requests behind properties. It seems like anything using HTTP should happen in a method.

It may not be an RPC request, depending on provider. Like, one could imagine for `eth-tester`, it literally is just setting a property.

I think it's important to have it feel consistent, but not entirely sure it should be a property either.

**Comment by unparalleled-js** [comment]
> I think it's important to have it feel consistent, but not entirely sure it should be a property either.

Good points!

One other thing I like about methods vs. properties (in general) is that it is easier to add to them without it being as much of a breaking change. For example, adding an optional kwarg-ument.

**Comment by fubuloubu** [comment]
I'm in support of a method for this instead!
