### ISSUE TITLE
Add fee token information to Ecosystem API

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#864]
### Overview

It would be helpful to know information about the base fee currency token for display purposes.
Let's say I am building a display app  / plugin using ape I want to show balances of accounts. Right now, hard to know what "balance" means (from an abstract perspective). Also want the correct symbol when it is not paid in ETH.

### Specification

```
class FeeTokenAPI:
   symbol: str
   decimals: int
   name: str

class EcosystemAPI:
   fee_token: Optional[FeeTokenAPI] = None
```

optional in case it is some alpha chain with no fees yet.

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by banteg** [comment]
maybe it should be called `native_token`

**Comment by unparalleled-js** [comment]
> maybe it should be called `native_token`

It is not always native though. In the case of Starknet, it is an ERC20 at the moment

**Comment by fubuloubu** [comment]
> maybe it should be called `native_token`

It could be `fee_token: Optional[AddressType] = None` where `None` means "use native Ether-like balances", and having one means that it should download and reference the contract address for balance information

**Comment by fubuloubu** [comment]
> > It could be `fee_token: Optional[AddressType] = None` where `None` means "use native Ether-like balances"
> 
> What if the native token is not Ether like?

I would say this semantic would mean "fee token is an ERC-like token" at a specific address, or if it is blank it means "the fee token is the native token, using whatever API the chain has natively for working with it's native tokens"

**Comment by unparalleled-js** [comment]
Even if it is a native token, how can I know how many decimals it uses?
Like say I am building a command that outputs balances in a nicer way, and all I have is a `EcosystemAPI`, how do I know the symbol and decimal amount?

**Comment by antazoey** [comment]
this got done!
