### ISSUE TITLE
Expose a query method for ContractEvents

### ISSUE THREAD

**Issue by johnson2427** [ApeWorX/ape#875]
### Overview

Need to expose a query method for `ContractEvents` so we can set up the `DefaultQueryProvider` and `CacheQueryProvider` to be able to query the provider.

### Specification

add `.query` to `ContractEvents` and then add to the singledispatch methods created in the query providers.

### Dependencies

None

**Comment by banteg** [comment]
i made a small plugin here, feel free to borrow the schema
https://github.com/banteg/ape-events/blob/main/ape_events/__init__.py

**Comment by fubuloubu** [comment]
I think we added this in #923

**Comment by johnson2427** [comment]
> I think we added this in #923

Yes, we did. Not sure why this was left out of there
