### ISSUE TITLE
`cls.compiler_manager.registered_compilers['.sol'].get_version_map(source_paths)` shows `.vy` files

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#880]
### Environment information

* OS: wsl2 ubuntu
* Python Version: 3.9.9
ape: 0.3.1.dev5+g549e6ec6
Installed Plugins:
  etherscan    0.3.1.dev0+g27b52bb.d20220620
  solidity     0.3.0
  ens          0.3.0
  fantom       0.3.0
  alchemy      0.3.0
  infura       0.3.0
  tokens       0.3.0
  vyper        0.3.0
  hardhat      0.3.0

* Contents of your `ape-config.yaml` (NOTE: do not post anything private like RPC urls or secrets!):

$ cat ape-config.yaml 
hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy

meta:
  authors: [sabotage]
  license: MIT
  description: "test token"
  keywords: [hello, world]
  links: {'apeworx.io':'https://apeworx.io'}(apeworx)
### What went wrong?

Please include information like:

* ape compile -f with breakpoint at [119 ](https://github.com/ApeWorX/ape/blob/0c9599e8df7bf6f6cf33c8ac7f17a2139fc9fbca/src/ape/api/projects.py#L108)

* the code that caused the failure `cls.compiler_manager.registered_compilers['.sol'].get_version_map(source_paths)` 
* full output of the error you received
```
(Pdb) cls.compiler_manager.registered_compilers['.sol'].get_version_map(source_paths)
{Version('0.6.12'): {PosixPath('/home/doge/ape/dummyproject/contracts/Token.sol'), PosixPath('/home/doge/ape/dummyproject/contracts/SafeMath.sol'), PosixPath('/home/doge/ape/dummyproject/contracts/payable.sol')}, Version('0.8.15'): {PosixPath('/home/doge/ape/dummyproject/contracts/VyperToken.vy')}}
```

### How can it be fixed?
not sure

**Comment by fubuloubu** [comment]
So that is calling out to this file:
https://github.com/ApeWorX/ape-solidity/blob/main/ape_solidity/compiler.py#L362

I am not sure what `source_paths` is and whether it contains the Vyper file, I don't think it has any particular filtering for when an unsupported file extension is passed through the argument.

**Comment by sabotagebeats** [comment]
closing as this is not a bug in ape.
