### ISSUE TITLE
update pins to be compatible for newest version of eth-rlp 

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#892]
### Elevator pitch:
eth-rlp is throwing errors in docker with the 0.2.1 version. this requires a manual update to 0.3.0 which then will build and work, but throws a bunch of errors about dependencies not being the correct version. If we update our pins for the newest versions of all the deps that depend on eth-rlp then we should be able to update the pin for eth-rlp and then this issue shouldn't be a problem in the future. 

### Value:
eth-rlp won't throw errors anymore and will work in docker without an extra install command.

### Dependencies:
eth-rlp and eth-account, may be more. 

### Design approach:
go through pins and make sure they don't break anything and update them.

### Task list:
[ ] update pin for eth-account
[ ] update pin for eth-rlp

### Estimated completion date:
next sprint 

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by sabotagebeats** [comment]
related: 
https://github.com/ApeWorX/ape/blob/main/setup.py
https://github.com/ethereum/eth-rlp/blob/master/setup.py
https://github.com/ethereum/eth-account/blob/master/setup.py

**Comment by unparalleled-js** [comment]
We are on eth-rlp 0.3.0 now
