### ISSUE TITLE
remove `RUN pip install eth-rlp==0.3.0` from dockerfile (blocked)

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#894]
### Elevator pitch:
this line shouldn't need to be here but is because of a dependency mismatch. if we can resolve that by updating the pins then we can remove that line. This work item is to track that. 

### Value:
cleaner dockerfile, faster build time for docker

### Dependencies:
related: https://github.com/ApeWorX/ape/pull/891
blocked by: https://github.com/ApeWorX/ape/issues/892

### Design approach:
remove that line from dockerfile after pins have been updated

### Task list:
* [ ] https://github.com/ApeWorX/ape/issues/892
* [ ] remove that line from dockerfile after pins have been updated

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by unparalleled-js** [comment]
I tried putting this in setup.py, as this is the version that gets installed anyway. However - it still fails unless present in the Dockerfile so I was not able to get rid of it.

**Comment by unparalleled-js** [comment]
I am guessing `pip install eth-rlp` does something magical...

**Comment by unparalleled-js** [comment]
I researched this more.

In site packages, the install of eth-rlp is corrupt. Everything is fine except the `__init__.py` file is unexpected.
Clearing the install and reinstalling fixes the issue.

However - this smells like an issue somewhere in eth-acount or pyrlp, not in ape.

**Comment by unparalleled-js** [comment]
Was done in python 3.7 removal PR
