### ISSUE TITLE
change dockerfile back to `pip install .[recommended-plugins]` (blocked)

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#895]
### Elevator pitch:
we should be using [recommended-plugins]

### Value:
this is better because it installs based on the recommended-plugins in setup.py so we can change it one place instead of many places.

### Dependencies:
blocked by: https://github.com/ApeWorX/ape/issues/893

### Design approach:
change dockerfile back to recommended-plugins once  https://github.com/ApeWorX/ape/issues/893 is resolved

### Task list:
[ ]  https://github.com/ApeWorX/ape/issues/893
[ ] change dockerfile back to recommended-plugins 

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
Another thing to follow up on here is if a person uses pip to install ape using `recommended-plugins` extra in a clean environment, are there issues with installation that take time to resolve, and how do we fix those?

**Comment by unparalleled-js** [comment]
Do we still want to do this? The way it is now, we are able to parametrize it. If we use `recommended-plugins` extra, it is always the same set.

**Comment by fubuloubu** [comment]
> Do we still want to do this? The way it is now, we are able to parametrize it. If we use `recommended-plugins` extra, it is always the same set.

I think your most recent update to the container is a much better solution
