### ISSUE TITLE
build out deployment, testing, and IPFS architecture for ape academy nft 

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#912]
### Elevator pitch:
@Ninjagod1251 is working on ape academy NFT. I have been tasked to help him with the scripting and testing of this project. 

### Value:
Have an NFT project to use for Ape Academy that works out of the box 

### Design approach:
build tests in pytest
build deployment scripts
build out IPFS backend / integration

### Task list:
not sure yet

* [ ] Tasks go here

### Estimated completion date:
not sure yet

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
One note: there is no need to do the IPFS stuff now

Simply create, deploy and pin default "coming soon" OpenSea-compatible metadata file for the NFT, and have that be the CID used in the deploy script. So when they run the deploy script, it just uses the default, which they can override with their own if they have one

Make a separate issue to actually build out the IPFS publishing step for the metadata/asset files, which will be a more involved scripting operation that can be completed at a later time.

This way, we get an out of the box experience for our ape NFT, without having to learn how to do all the more complicated NFT stuff

**Comment by Ninjagod1251** [comment]
this needs to be tracked in [academy](https://github.com/ApeWorX/academy)
not here

**Comment by fubuloubu** [comment]
> this needs to be tracked in [academy](https://github.com/ApeWorX/academy)
> not here
>  

BTW, you can just transfer issues between repos in the same org

**Comment by sabotagebeats** [comment]
@fubuloubu the way this is architected in the mint and seturi functions it is set to be able to mint specific token ids and then the uri will be updatable for specific token ID's. If I have 10,000 sabbysnakes and I want to reveal them, I will have to make 10,000 update uri calls to do so. Is this how we want this to be? I would think it might be better to set the uri in one call and have it populate to all tokenids.

**Comment by NotPeopling2day** [comment]
Closing this issue for Linear
