### ISSUE TITLE
consider dropping python 3.7 support

### ISSUE THREAD

**Issue by banteg** [ApeWorX/ape#914]
see https://github.com/ApeWorX/evm-trace/issues/11 for the rationale

**Comment by johnson2427** [comment]
Agreed, 3.7 is Ubuntu 19.04's version, and it is missing quite a bit of support for many packages.

**Comment by unparalleled-js** [comment]
We will be able to upgrade `ipython` to the 8.0 range once we do this

**Comment by fubuloubu** [comment]
Plan 3.7 deprecation for v0.5.0?

**Comment by unparalleled-js** [comment]
Done
