### ISSUE TITLE
Adding Property Based Testing To Ape (Fuzz tests)

### ISSUE THREAD

**Issue by franfran18** [ApeWorX/ape#916]
### Overview

When working with brownie you have the option of working with fuzz tests via hypothesis configured to work with testing data types specific to smart contracts e.g uint8, addresses, Booleans, bytes8, string e.t.c. Right now I don't think ape has this functionality out of the box. I'm not too sure how hypothesis works under the hood but I think brownie made this as easy as possible for devs to pass in those parameters without bothering too much about hypothesis works. Check out [the docs here](https://eth-brownie.readthedocs.io/en/stable/tests-hypothesis-property.html#what-is-property-based-testing).

```python
@given(
    to=strategy('address', exclude=accounts[0]),
    value=strategy('uint256', max_value=10000),
)
def test_transfer_amount(token, to, value):
    balance = token.balanceOf(accounts[0])
    token.transfer(to, value, {'from': accounts[0]})

    assert token.balanceOf(accounts[0]) == balance - value
    assert token.balanceOf(to) == value
```

Currently I don't' think ape  supports this.
I understand ape and brownie have slight similarities but i think making this feature less ugly when porting over to ape would be a plus.
In my opinion, I think the way brownie does this, does the job but is kinda ugly :|

I don't know how possible this is but i think it'd be nicer to abstract away the @given and replace it with something like this

```python

def test_transfer_amount(token, to=address , value=uint256):
    balance = token.balanceOf(accounts[0])
    token.transfer(to, value, {'from': accounts[0]})

    assert token.balanceOf(accounts[0]) == balance - value
    assert token.balanceOf(to) == value
```

If its not possible this way, the way brownie does it is also totally fine!

**Comment by fubuloubu** [comment]
Also, this is being tracked here https://github.com/ApeWorX/ape/issues/351, so closing this issue in favor of that one

**Comment by franfran20** [comment]
Awesome thanks
