### ISSUE TITLE
Adding a way to get a contract address before its deployed

### ISSUE THREAD

**Issue by franfran20** [ApeWorX/ape#926]
### Overview

Adding an in-built function that allows a user to get the contract of an address before the contract gets deployed.
This would be useful when you need to pass the contract address of a contract yet to be deployed as a parameter to another contracts deployment.

### Specification
Using hardhat you could do something like this..
```javascript
import { hexlify, keccak256, RLP } from 'ethers/lib/utils';

const followNFTNonce = hexlify(deployerNonce);

const followNFTImplAddress =
    '0x' + keccak256(RLP.encode([deployer.address, followNFTNonce])).substr(26);
```

OR

You could use the ethersproject package and do something like this

```javascript
const { ethers } = require('hardhat')
const { getContractAddress } = require('@ethersproject/address')

async function main() {
  const [owner] = await ethers.getSigners()

  const transactionCount = await owner.getTransactionCount()

  const futureAddress = getContractAddress({
    from: owner.address,
    nonce: transactionCount
  })
}

```
If we could have something similar to the second that'd be great for both local and live scripting and testing!

**Comment by fubuloubu** [comment]
can be something like `AccountAPI.next_deployment_address -> AddressType`

**Comment by franfran20** [comment]
This works.
I think it'd be nice to make it more flexible.
So you could manipulate the nonce.

A case for this would be if I need three contract addresses that haven't been deployed as params for a single contract. Then I could do have way to change the nonce as an option to get the next next deployment address and so on
If that makes sense

**Comment by fubuloubu** [comment]
> This works.
> I think it'd be nice to make it more flexible.
> So you could manipulate the nonce.
> 
> A case for this would be if I need three contract addresses that haven't been deployed as params for a single contract. Then I could do have way to change the nonce as an option to get the next next deployment address and so on
> If that makes sense

Okay yeah sure, `AccountAPI.get_deployment_address(nonce=current) -> AddressType`
