### ISSUE TITLE
Convert float to int for XeX style numbers

### ISSUE THREAD

**Issue by PatrickAlphaC** [ApeWorX/ape#928]
### Overview

If I try to deploy a contract with a number with many decimal places like so:

```python
account.deploy(project.MyContract, 1e18)
```

I get the following error: 

```
*** eth_abi.exceptions.EncodingTypeError: Value `2e+21` of type <class 'float'> cannot be encoded by SignedIntegerEncoder
```

Which makes sense:

```python
(Pdb) type(1e18)
<class 'float'>
(Pdb) type(1000000000000000000)
<class 'int'>
```

It would be great if ape could auto convert floats to int to allow these to go through.

**Comment by fubuloubu** [comment]
> It would be great if ape could auto convert floats to int to allow these to go through.

I would argue against this a bit because that would be kind of magical and lead to some strange off-by-one errors at times. Much better to just convert to integer like `int(1e18)` or something else.

**Comment by antazoey** [comment]
Closing as "Won't Do"
