### ISSUE TITLE
spike: github action should run off of docker

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#938]
### Elevator pitch:
github action should run off of docker to prevent installation during every action

### Value:
improve github action performance and efficiency

### Dependencies:
docker has to be perfect

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
talking about this repo btw: https://github.com/ApeWorX/github-action

**Comment by antazoey** [comment]
Closing as it not a core problem.
Use https://github.com/ApeWorX/github-action/issues/6 for tracking or re-word ticket to be core-specific.
