### ISSUE TITLE
Better error message if required plugin is not installed 

### ISSUE THREAD

**Issue by dtdang** [ApeWorX/ape#946]
### Overview

Deploying a contract without having the right plugins (like vyper) gives the error message `AttributeError: 'ProjectManager' object has no attribute 'NFT'`. The error is not clear enough for the user to know what the problem is to solve the error. 

### Specification

Instead of raising an attribute error, check to see if there is a file in the contracts/ directory with this name. If yes, check the extension. Then raise a better error like `Missing compiler for '.vy' source extension` 

### Dependencies

None

**Comment by antazoey** [comment]
the error message has improved since the ticket was opened. Now it says a bunch of stuff, like:

```
ERROR: (ApeAttributeError) ProjectManager has no attribute or contract named 'Test'. However, there is a source file named 'Test', did you mean to reference a contract name from this source file? Else, could it be from one of the missing compilers for extensions: .sol?
```

This seems to cover what is being asked for!
