### ISSUE TITLE
Decode calldata using ContractInstance

### ISSUE THREAD

**Issue by bout3fiddy** [ApeWorX/ape#947]
### Overview

Provide a simple overview of what you wish to see added. Please include:

* What you are trying to do
* Why Ape's current functionality is inadequate to address your goal

In CurveDAO, DAO-controlled voting entities (AragonDAO contracts) can execute random calldata if governance meets quorum. It's important hence to be able to decode the calldata and verify if it isn't malicious. In brownie, this can be achieved by:

```
decoded_calldata = contract.decode_input(calldata)
```
but this is currently not available on the contract instance. 

### Specification

Describe the syntax and semantics of how you would like to see this feature implemented. The more detailed the better!

Remember, your feature is much more likely to be included if it does not involve any breaking changes.

Ape already has this implementation in [ape > utils > trace.py](https://github.com/ApeWorX/ape/blob/main/src/ape/utils/trace.py#L215-L236 ) : 

```
def decode_calldata(self, method: MethodABI, raw_data: bytes) -> Dict:
    input_types = [i.canonical_type for i in method.inputs]  # type: ignore

    try:
        raw_input_values = decode_abi(input_types, raw_data)
        input_values = [
            self.decode_value(
                self._ecosystem.decode_primitive_value(v, parse_type(t)),
            )
            for v, t in zip(raw_input_values, input_types)
        ]
    except (DecodingError, InsufficientDataBytes):
        input_values = ["<?>" for _ in input_types]

    arguments = {}
    index = 0
    for i, v in zip(method.inputs, input_values):
        name = i.name or f"{index}"
        arguments[name] = v
        index += 1

    return arguments
```
The goal would be to allow the contractinstance to be able to do this by:

```
decoded_calldata: Dict = contract.decode_calldata(raw_data: bytes)
```
the decode_calldata would need to figure out the method automagically.

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by fubuloubu** [comment]
We have something similar
https://docs.apeworx.io/ape/stable/methoddocs/api.html#ape.api.networks.EcosystemAPI.decode_returndata

But obviously this doesn't work quite as nicely

**Comment by unparalleled-js** [comment]
> We have something similar https://docs.apeworx.io/ape/stable/methoddocs/api.html#ape.api.networks.EcosystemAPI.decode_returndata
> 
> But obviously this doesn't work quite as nicely

That is only the outputs though and not the inputs right?
They want to decode already encoded inputs, to my understanding, so like backwards then the normal flow for inputs.

**Comment by unparalleled-js** [comment]
This ticket should also include encoding e.g .`encode_input()` and `decode_input()`

**Comment by unparalleled-js** [comment]
Can you let me know how this works for you? https://github.com/ApeWorX/ape/pull/1160
