### ISSUE TITLE
feat: add settings data to compiler data 

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#948]
### Elevator pitch:
In this PR(https://github.com/ApeWorX/ape/issues/792) we got the functionality to work to add compiler data to the package manifest

However we still lack the settings data which will need to be filled in from another source 

### Value:
will be needed for https://github.com/ApeWorX/ape/issues/81

### Design approach:

* Add `get_settings() -> Dict[Version, Dict]` API method to `CompilerAPI`. The method can be `@raised_not_implemented` by default to as not cause breaking change and we can later discus making it abstract.
* Where we create the `Compiler` Ethpm-types data, include the settings (where the last TODO is).
* Implement `get_settings()` in `ape-solidity` to return what gets used as the I/O args to the compiler (https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-input-and-output-json-description ) _per_ version used in the project.
* Implement `get_settings()` in vyper similarly

### Task list:

* [ ] Tasks go here

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by sabotagebeats** [comment]
https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-input-and-output-json-description h/t @unparalleled-js

**Comment by sabotagebeats** [comment]
https://github.com/ApeWorX/ape-solidity/pull/64

**Comment by sabotagebeats** [comment]
https://github.com/ApeWorX/ape/pull/979

**Comment by sabotagebeats** [comment]
needs vyper

**Comment by sabotagebeats** [comment]
needs vyper settings: https://github.com/ApeWorX/ape-vyper/pull/54

**Comment by unparalleled-js** [comment]
This work has been completed
