### ISSUE TITLE
Change `receiver` and `sender` to `bytes` datatype in `TransactionAPI`

### ISSUE THREAD

**Issue by johnson2427** [ApeWorX/ape#967]
### Overview

Currently `sender` and `receiver` are of type `str` in `TransactionAPI`, would like to change these to `bytes`.
Also, the `signature` is excluded from the pydantic model, we should keep this data.

### Specification

```python
class TransactionAPI(BaseInterfaceModel):
    chain_id: int = Field(0, alias="chainId")
    hash: Any = Field(None, alias="txn_hash")
    receiver: Optional[bytes] = Field(None, alias="to")
    sender: Optional[bytes] = Field(None, alias="from")
    gas_limit: Optional[int] = Field(None, alias="gas")
    nonce: Optional[int] = None  # NOTE: `Optional` only to denote using default behavior
    value: int = 0
    data: bytes = b""
    type: Union[int, bytes, str]
    max_fee: Optional[int] = None
    max_priority_fee: Optional[int] = None

    # If left as None, will get set to the network's default required confirmations.
    required_confirmations: Optional[int] = Field(None, exclude=True)

    signature: Optional[TransactionSignature] = Field(...)
...
```

### Dependencies

There will be some tests that are broken from this, need to update the tests to be able to handle the `bytes` datatype

**Comment by johnson2427** [comment]
This is a light suggestion, if we do not want to implement this, then I can convert the string to bytes from the cache side

**Comment by johnson2427** [comment]
@fubuloubu @unparalleled-js lmk what you think

**Comment by fubuloubu** [comment]
To better store Addresses on disk/in SQL/using inside of Ape, worth a bit of a dive one what's the best option for each and what the tradeoffs might be to choose one

However, I would say the type should eventually be `AddressType` and not `str` so as to have better type safety in the library as well.
