### ISSUE TITLE
Configurable Gas Limit For Networks

### ISSUE THREAD

**Issue by helloibis** [ApeWorX/ape#985]
### Overview

Support setting maximum `gas_limit` values for networks in configuration of `ape` projects. 

This will be used to facilitate https://github.com/ApeWorX/ape/issues/937 

#### Config

In `ape-config.yaml` a user will be able to specify a `gas_limit` configuration:

```yaml
default_ecosystem: <ecosystem-name>

<ecosystem-name>:
  default_network: <network-name>
  <network-name>:
    gas_limit: <gas-limit>
    default_provider: <provider-name>
```

The `gas_limit` parameter(s) will support one of four value types:

- `int`: Gas limit is set to the specified amount
- `"auto"`: Gas limit is automatic, calculated via gas estimation
- `"max"`: Gas limit is based on the max gas limit for the chain

---

#### Implementation Details

The limit will be available as a private attribute under `NetworkAPI._gas_limit` (which could have an associated `@property` method getter), and should only be set at the time the configuration is loaded.

In `ProviderAPI.estimate_gas_cost()` the provider will check `self.network.gas_limit` and decide what to do based off of the value. The function will return the integer for `gas_limit` if one was used, `"max"` will use the chain's max limit, and `"auto"` will let gas estimation run as normal.

If the user is specifying a gas limit override on a transaction none of this will apply, since `estimate_gas_cost()` won't be running anyway.

---

#### Default Values

By default the value will be `"auto"` which will essentially keep the same behavior we already have (where gas estimation runs if you aren't specifying a gas limit override on a transaction).

For local networks (e.g. `ethereum:local:test`) the default value can be `"max"` so that gas estimation problems don't have to cause exceptions during testing.

### Dependencies

N/A

**Comment by helloibis** [comment]
Opening up to start accounting for the gas limit configuration as discussed in https://github.com/ApeWorX/ape/pull/957, will be adding more details after our Wednesday meeting

**Comment by fubuloubu** [comment]
This is a great feature, and also probably a good heuristic to add is to raise a warning when you are using like 50% of the block space, because it's probably unlikely to get mined, and an error if it's over the max

**Comment by helloibis** [comment]
Still in research mode, collecting info about how Brownie does it and how we might want to implement it. May have to break from this though this week for the Nashville trip / project with @NotPeopling2day

**Comment by helloibis** [comment]
[This is Brownie's implementation](https://eth-brownie.readthedocs.io/en/stable/config.html?highlight=gas_limit#networks.gas_limit)

With regards to the discussion in https://github.com/ApeWorX/ape/pull/957 I think we'll differ from Brownie's default values. For this issue I have the default as `None` but in Brownie their _development default_ is actually `"max"`.

Is this behavior something that we'll want/need to match?
